#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/FluffyUnderware/DevTools/DTVersionedMonoBehaviour.h"

#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_CGSPOTCAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE86140)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_FLOATCAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE86050)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_INTCAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85F60)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_LOGALLOCATIONS_OFFSET UNITYSDK_OFFSET(0x1AE86230)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_VECTOR2CAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85C90)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_VECTOR3CAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85D80)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_VECTOR4CAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85E70)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_ONENABLE_OFFSET UNITYSDK_OFFSET(0x1AE86690)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_ONVALIDATE_OFFSET UNITYSDK_OFFSET(0x1AE865D0)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_CGSPOTCAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE86150)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_FLOATCAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE86060)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_INTCAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85F70)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_LOGALLOCATIONS_OFFSET UNITYSDK_OFFSET(0x1AE86240)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_VECTOR2CAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85CA0)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_VECTOR3CAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85D90)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_VECTOR4CAPACITY_OFFSET UNITYSDK_OFFSET(0x1AE85E80)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_START_OFFSET UNITYSDK_OFFSET(0x1AE86710)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_VALIDATEANDAPPLY_OFFSET UNITYSDK_OFFSET(0x1AE86630)
#define FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS__CTOR_OFFSET UNITYSDK_OFFSET(0x1AE86770)

namespace FluffyUnderware::Curvy::Pools
{
	inline static constexpr unsigned int ArrayPoolsSettings_TypeDefinitionIndex = 35684;

	class ArrayPoolsSettings : public ::FluffyUnderware::DevTools::DTVersionedMonoBehaviour
	{
	public:
		::System::Int64 vector2Capacity; // 0x28
		::System::Int64 vector3Capacity; // 0x30
		::System::Int64 vector4Capacity; // 0x38
		::System::Int64 intCapacity; // 0x40
		::System::Int64 floatCapacity; // 0x48
		::System::Int64 cgSpotCapacity; // 0x50
		::System::Boolean logAllocations; // 0x58

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS__CTOR_OFFSET))(this);
		}

		::System::Int64 get_Vector2Capacity()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_VECTOR2CAPACITY_OFFSET))(this);
		}

		::System::Void set_Vector2Capacity(::System::Int64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_VECTOR2CAPACITY_OFFSET))(this, value);
		}

		::System::Int64 get_Vector3Capacity()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_VECTOR3CAPACITY_OFFSET))(this);
		}

		::System::Void set_Vector3Capacity(::System::Int64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_VECTOR3CAPACITY_OFFSET))(this, value);
		}

		::System::Int64 get_Vector4Capacity()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_VECTOR4CAPACITY_OFFSET))(this);
		}

		::System::Void set_Vector4Capacity(::System::Int64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_VECTOR4CAPACITY_OFFSET))(this, value);
		}

		::System::Int64 get_IntCapacity()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_INTCAPACITY_OFFSET))(this);
		}

		::System::Void set_IntCapacity(::System::Int64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_INTCAPACITY_OFFSET))(this, value);
		}

		::System::Int64 get_FloatCapacity()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_FLOATCAPACITY_OFFSET))(this);
		}

		::System::Void set_FloatCapacity(::System::Int64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_FLOATCAPACITY_OFFSET))(this, value);
		}

		::System::Int64 get_CGSpotCapacity()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_CGSPOTCAPACITY_OFFSET))(this);
		}

		::System::Void set_CGSpotCapacity(::System::Int64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_CGSPOTCAPACITY_OFFSET))(this, value);
		}

		::System::Boolean get_LogAllocations()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_GET_LOGALLOCATIONS_OFFSET))(this);
		}

		::System::Void set_LogAllocations(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_SET_LOGALLOCATIONS_OFFSET))(this, value);
		}

		::System::Void OnValidate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_ONVALIDATE_OFFSET))(this);
		}

		::System::Void OnEnable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_ONENABLE_OFFSET))(this);
		}

		::System::Void Start()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_START_OFFSET))(this);
		}

		::System::Void ValidateAndApply()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FLUFFYUNDERWARE_CURVY_POOLS_ARRAYPOOLSSETTINGS_VALIDATEANDAPPLY_OFFSET))(this);
		}
	};
}
