#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/BehaviorDesigner/Runtime/Behavior_EventTypes.h"
#include "unitysdk/BehaviorDesigner/Runtime/Tasks/Conditional.h"
#include "unitysdk/BehaviorDesigner/Runtime/Tasks/StackedConditional_ComparisonType.h"
#include "unitysdk/BehaviorDesigner/Runtime/Tasks/TaskStatus.h"

namespace System { class String; }
namespace UnityEngine { class Collider2D; }
namespace UnityEngine { class Collider; }
namespace UnityEngine { class Collision2D; }
namespace UnityEngine { class Collision; }

#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONAWAKE_OFFSET UNITYSDK_OFFSET(0x1ABD74E0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONENTER2D_OFFSET UNITYSDK_OFFSET(0x1ABD7CC0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONENTER_OFFSET UNITYSDK_OFFSET(0x1ABD7C10)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONEXIT2D_OFFSET UNITYSDK_OFFSET(0x1ABD7E20)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONEXIT_OFFSET UNITYSDK_OFFSET(0x1ABD7D70)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONDRAWNODETEXT_OFFSET UNITYSDK_OFFSET(0x1ABD7ED0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONEND_OFFSET UNITYSDK_OFFSET(0x1ABD78B0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONFIXEDUPDATE_OFFSET UNITYSDK_OFFSET(0x1ABD7770)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONLATEUPDATE_OFFSET UNITYSDK_OFFSET(0x1ABD7810)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONRESET_OFFSET UNITYSDK_OFFSET(0x1ABD8030)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONSTART_OFFSET UNITYSDK_OFFSET(0x1ABD7600)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGERENTER2D_OFFSET UNITYSDK_OFFSET(0x1ABD7A00)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGERENTER_OFFSET UNITYSDK_OFFSET(0x1ABD7950)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGEREXIT2D_OFFSET UNITYSDK_OFFSET(0x1ABD7B60)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGEREXIT_OFFSET UNITYSDK_OFFSET(0x1ABD7AB0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONUPDATE_OFFSET UNITYSDK_OFFSET(0x1ABD76A0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_SELFCONTAINSMETHOD_OFFSET UNITYSDK_OFFSET(0x1ABD7460)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL__CTOR_OFFSET UNITYSDK_OFFSET(0x1ABD80D0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONAWAKE_OFFSET UNITYSDK_OFFSET(0x1ABD8110)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONENTER2D_OFFSET UNITYSDK_OFFSET(0x1ABD8230)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONENTER_OFFSET UNITYSDK_OFFSET(0x1ABD81A0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONEXIT2D_OFFSET UNITYSDK_OFFSET(0x1ABD8350)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONEXIT_OFFSET UNITYSDK_OFFSET(0x1ABD82C0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONDRAWNODETEXT_OFFSET UNITYSDK_OFFSET(0x1ABD83E0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONEND_OFFSET UNITYSDK_OFFSET(0x1ABD8470)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONFIXEDUPDATE_OFFSET UNITYSDK_OFFSET(0x1ABD8500)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONLATEUPDATE_OFFSET UNITYSDK_OFFSET(0x1ABD8590)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONRESET_OFFSET UNITYSDK_OFFSET(0x1ABD8620)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONSTART_OFFSET UNITYSDK_OFFSET(0x1ABD86B0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGERENTER2D_OFFSET UNITYSDK_OFFSET(0x1ABD87D0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGERENTER_OFFSET UNITYSDK_OFFSET(0x1ABD8740)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGEREXIT2D_OFFSET UNITYSDK_OFFSET(0x1ABD88F0)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGEREXIT_OFFSET UNITYSDK_OFFSET(0x1ABD8860)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONUPDATE_OFFSET UNITYSDK_OFFSET(0x1ABD8980)
#define BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_SELFCONTAINSMETHOD_OFFSET UNITYSDK_OFFSET(0x1ABD8A10)

namespace BehaviorDesigner::Runtime::Tasks
{
	inline static constexpr unsigned int StackedConditional_TypeDefinitionIndex = 31238;

	class StackedConditional : public ::BehaviorDesigner::Runtime::Tasks::Conditional
	{
	public:
		::Il2CppArray<::BehaviorDesigner::Runtime::Tasks::Conditional*>* conditionals; // 0x50
		::System::Boolean graphLabel; // 0x58
		::BehaviorDesigner::Runtime::Tasks::StackedConditional_ComparisonType comparisonType; // 0x5C

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL__CTOR_OFFSET))(this);
		}

		::System::Boolean SelfContainsMethod(::BehaviorDesigner::Runtime::Behavior_EventTypes evt)
		{
			return ((::System::Boolean(*)(::PVOID, ::BehaviorDesigner::Runtime::Behavior_EventTypes))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_SELFCONTAINSMETHOD_OFFSET))(this, evt);
		}

		::System::Void OnAwake()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONAWAKE_OFFSET))(this);
		}

		::System::Void OnStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONSTART_OFFSET))(this);
		}

		::BehaviorDesigner::Runtime::Tasks::TaskStatus OnUpdate()
		{
			return ((::BehaviorDesigner::Runtime::Tasks::TaskStatus(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONUPDATE_OFFSET))(this);
		}

		::System::Void OnFixedUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONFIXEDUPDATE_OFFSET))(this);
		}

		::System::Void OnLateUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONLATEUPDATE_OFFSET))(this);
		}

		::System::Void OnEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONEND_OFFSET))(this);
		}

		::System::Void OnTriggerEnter(::UnityEngine::Collider* other)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGERENTER_OFFSET))(this, other);
		}

		::System::Void OnTriggerEnter2D(::UnityEngine::Collider2D* other)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGERENTER2D_OFFSET))(this, other);
		}

		::System::Void OnTriggerExit(::UnityEngine::Collider* other)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGEREXIT_OFFSET))(this, other);
		}

		::System::Void OnTriggerExit2D(::UnityEngine::Collider2D* other)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONTRIGGEREXIT2D_OFFSET))(this, other);
		}

		::System::Void OnCollisionEnter(::UnityEngine::Collision* collision)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONENTER_OFFSET))(this, collision);
		}

		::System::Void OnCollisionEnter2D(::UnityEngine::Collision2D* collision)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONENTER2D_OFFSET))(this, collision);
		}

		::System::Void OnCollisionExit(::UnityEngine::Collision* collision)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONEXIT_OFFSET))(this, collision);
		}

		::System::Void OnCollisionExit2D(::UnityEngine::Collision2D* collision)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONCOLLISIONEXIT2D_OFFSET))(this, collision);
		}

		::System::String* OnDrawNodeText()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONDRAWNODETEXT_OFFSET))(this);
		}

		::System::Void OnReset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL_ONRESET_OFFSET))(this);
		}

		::System::Void __base_OnAwake()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONAWAKE_OFFSET))(this);
		}

		::System::Void __base_OnCollisionEnter(::UnityEngine::Collision* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONENTER_OFFSET))(this, P0);
		}

		::System::Void __base_OnCollisionEnter2D(::UnityEngine::Collision2D* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONENTER2D_OFFSET))(this, P0);
		}

		::System::Void __base_OnCollisionExit(::UnityEngine::Collision* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONEXIT_OFFSET))(this, P0);
		}

		::System::Void __base_OnCollisionExit2D(::UnityEngine::Collision2D* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collision2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONCOLLISIONEXIT2D_OFFSET))(this, P0);
		}

		::System::String* __base_OnDrawNodeText()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONDRAWNODETEXT_OFFSET))(this);
		}

		::System::Void __base_OnEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONEND_OFFSET))(this);
		}

		::System::Void __base_OnFixedUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONFIXEDUPDATE_OFFSET))(this);
		}

		::System::Void __base_OnLateUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONLATEUPDATE_OFFSET))(this);
		}

		::System::Void __base_OnReset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONRESET_OFFSET))(this);
		}

		::System::Void __base_OnStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONSTART_OFFSET))(this);
		}

		::System::Void __base_OnTriggerEnter(::UnityEngine::Collider* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGERENTER_OFFSET))(this, P0);
		}

		::System::Void __base_OnTriggerEnter2D(::UnityEngine::Collider2D* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGERENTER2D_OFFSET))(this, P0);
		}

		::System::Void __base_OnTriggerExit(::UnityEngine::Collider* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGEREXIT_OFFSET))(this, P0);
		}

		::System::Void __base_OnTriggerExit2D(::UnityEngine::Collider2D* P0)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider2D*))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONTRIGGEREXIT2D_OFFSET))(this, P0);
		}

		::BehaviorDesigner::Runtime::Tasks::TaskStatus __base_OnUpdate()
		{
			return ((::BehaviorDesigner::Runtime::Tasks::TaskStatus(*)(::PVOID))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_ONUPDATE_OFFSET))(this);
		}

		::System::Boolean __base_SelfContainsMethod(::BehaviorDesigner::Runtime::Behavior_EventTypes P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::BehaviorDesigner::Runtime::Behavior_EventTypes))((::PBYTE)hIl2Cpp + BEHAVIORDESIGNER_RUNTIME_TASKS_STACKEDCONDITIONAL___BASE_SELFCONTAINSMETHOD_OFFSET))(this, P0);
		}
	};
}
