#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace ICSharpCode::SharpZipLib::Zip::Compression { class Inflater; }
namespace System::IO { class Stream; }
namespace System::Security::Cryptography { class ICryptoTransform; }

#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_FILL_OFFSET UNITYSDK_OFFSET(0x1B60F0E0)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_AVAILABLE_OFFSET UNITYSDK_OFFSET(0x1B60F060)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_CLEARTEXTLENGTH_OFFSET UNITYSDK_OFFSET(0x1B60F040)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_CLEARTEXT_OFFSET UNITYSDK_OFFSET(0x1B60F050)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_RAWDATA_OFFSET UNITYSDK_OFFSET(0x1B60F030)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_RAWLENGTH_OFFSET UNITYSDK_OFFSET(0x1B60F020)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READCLEARTEXTBUFFER_OFFSET UNITYSDK_OFFSET(0x1B60F320)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLEBYTE_OFFSET UNITYSDK_OFFSET(0x1B60F400)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLEINT_OFFSET UNITYSDK_OFFSET(0x1B60F4E0)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLELONG_OFFSET UNITYSDK_OFFSET(0x1B60F530)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLESHORT_OFFSET UNITYSDK_OFFSET(0x1B60F4B0)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READRAWBUFFER_1_OFFSET UNITYSDK_OFFSET(0x1B60F240)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READRAWBUFFER_OFFSET UNITYSDK_OFFSET(0x1B60F220)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_SETINFLATERINPUT_OFFSET UNITYSDK_OFFSET(0x1B60F080)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_SET_AVAILABLE_OFFSET UNITYSDK_OFFSET(0x1B60F070)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_SET_CRYPTOTRANSFORM_OFFSET UNITYSDK_OFFSET(0x1B60F5C0)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER__CTOR_1_OFFSET UNITYSDK_OFFSET(0x1B60EFE0)
#define ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER__CTOR_OFFSET UNITYSDK_OFFSET(0x1B60EFB0)

namespace ICSharpCode::SharpZipLib::Zip::Compression::Streams
{
	inline static constexpr unsigned int InflaterInputBuffer_TypeDefinitionIndex = 6691;

	class InflaterInputBuffer : public ::System::Object
	{
	public:
		::Il2CppArray<::System::Byte>* internalClearText; // 0x10
		::System::Security::Cryptography::ICryptoTransform* cryptoTransform; // 0x18
		::Il2CppArray<::System::Byte>* clearText; // 0x20
		::System::IO::Stream* inputStream; // 0x28
		::Il2CppArray<::System::Byte>* rawData; // 0x30
		::System::Int32 rawLength; // 0x38
		::System::Int32 clearTextLength; // 0x3C
		::System::Int32 available; // 0x40

		::System::Void _ctor(::System::IO::Stream* stream)
		{
			return ((::System::Void(*)(::PVOID, ::System::IO::Stream*))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER__CTOR_OFFSET))(this, stream);
		}

		::System::Void _ctor_1(::System::IO::Stream* stream, ::System::Int32 bufferSize)
		{
			return ((::System::Void(*)(::PVOID, ::System::IO::Stream*, ::System::Int32))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER__CTOR_1_OFFSET))(this, stream, bufferSize);
		}

		::System::Int32 get_RawLength()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_RAWLENGTH_OFFSET))(this);
		}

		::Il2CppArray<::System::Byte>* get_RawData()
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_RAWDATA_OFFSET))(this);
		}

		::System::Int32 get_ClearTextLength()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_CLEARTEXTLENGTH_OFFSET))(this);
		}

		::Il2CppArray<::System::Byte>* get_ClearText()
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_CLEARTEXT_OFFSET))(this);
		}

		::System::Int32 get_Available()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_GET_AVAILABLE_OFFSET))(this);
		}

		::System::Void set_Available(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_SET_AVAILABLE_OFFSET))(this, value);
		}

		::System::Void SetInflaterInput(::ICSharpCode::SharpZipLib::Zip::Compression::Inflater* inflater)
		{
			return ((::System::Void(*)(::PVOID, ::ICSharpCode::SharpZipLib::Zip::Compression::Inflater*))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_SETINFLATERINPUT_OFFSET))(this, inflater);
		}

		::System::Void Fill()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_FILL_OFFSET))(this);
		}

		::System::Int32 ReadRawBuffer(::Il2CppArray<::System::Byte>* buffer)
		{
			return ((::System::Int32(*)(::PVOID, ::Il2CppArray<::System::Byte>*))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READRAWBUFFER_OFFSET))(this, buffer);
		}

		::System::Int32 ReadRawBuffer_1(::Il2CppArray<::System::Byte>* outBuffer, ::System::Int32 offset, ::System::Int32 length)
		{
			return ((::System::Int32(*)(::PVOID, ::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READRAWBUFFER_1_OFFSET))(this, outBuffer, offset, length);
		}

		::System::Int32 ReadClearTextBuffer(::Il2CppArray<::System::Byte>* outBuffer, ::System::Int32 offset, ::System::Int32 length)
		{
			return ((::System::Int32(*)(::PVOID, ::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READCLEARTEXTBUFFER_OFFSET))(this, outBuffer, offset, length);
		}

		::System::Int32 ReadLeByte()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLEBYTE_OFFSET))(this);
		}

		::System::Int32 ReadLeShort()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLESHORT_OFFSET))(this);
		}

		::System::Int32 ReadLeInt()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLEINT_OFFSET))(this);
		}

		::System::Int64 ReadLeLong()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_READLELONG_OFFSET))(this);
		}

		::System::Void set_CryptoTransform(::System::Security::Cryptography::ICryptoTransform* value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Security::Cryptography::ICryptoTransform*))((::PBYTE)hIl2Cpp + ICSHARPCODE_SHARPZIPLIB_ZIP_COMPRESSION_STREAMS_INFLATERINPUTBUFFER_SET_CRYPTOTRANSFORM_OFFSET))(this, value);
		}
	};
}
