#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/UnityEngine/NAPRenderPipeline0/LensFlareComponentSRP_NativeSRP.h"

#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONDISABLE_OFFSET UNITYSDK_OFFSET(0x197D62E0)
#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONENABLE_OFFSET UNITYSDK_OFFSET(0x197D6070)
#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONLIGHTWEIGHTACTIVE_OFFSET UNITYSDK_OFFSET(0x197D6400)
#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONLIGHTWEIGHTDEACTIVE_OFFSET UNITYSDK_OFFSET(0x197D6460)
#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONREALDISABLE_OFFSET UNITYSDK_OFFSET(0x197D6380)
#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONREALENABLE_OFFSET UNITYSDK_OFFSET(0x197D6110)
#define UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP__CTOR_OFFSET UNITYSDK_OFFSET(0x197D64C0)

namespace UnityEngine::NAPRenderPipeline0
{
	inline static constexpr unsigned int LensFlareComponentSRP_TypeDefinitionIndex = 29241;

	class LensFlareComponentSRP : public ::UnityEngine::NAPRenderPipeline0::LensFlareComponentSRP_NativeSRP
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP__CTOR_OFFSET))(this);
		}

		::System::Void OnEnable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONENABLE_OFFSET))(this);
		}

		::System::Void OnDisable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONDISABLE_OFFSET))(this);
		}

		::System::Void OnLightweightActive()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONLIGHTWEIGHTACTIVE_OFFSET))(this);
		}

		::System::Void OnLightweightDeactive()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONLIGHTWEIGHTDEACTIVE_OFFSET))(this);
		}

		::System::Void OnRealEnable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONREALENABLE_OFFSET))(this);
		}

		::System::Void OnRealDisable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_NAPRENDERPIPELINE0_LENSFLARECOMPONENTSRP_ONREALDISABLE_OFFSET))(this);
		}
	};
}
