#pragma once
#include "unitysdk/unitysdk.h"

inline static constexpr unsigned int Enum_3_74B8771726734F6D_TypeDefinitionIndex = 65998;

enum class Enum_3_74B8771726734F6D : ::System::Int32
{
	HollowResultYorozuyaLevelUp = 42,
	NodeChanged_ShowEventToLock = 22,
	HpToSafe = 12,
	ChessboardPlayerMove_BM = 38,
	LostBless = 6,
	LoadingSingleLost = 39,
	StanimaDown = 4,
	MuteCard = 2,
	MainStory_BackAnim = 32,
	GetItem = 0,
	StanimaToSafe = 8,
	ChessboardPlayerMove_LF = 35,
	EnterBattle = 10,
	GetCurse = 27,
	MainStory_Click = 30,
	MainStory_Move = 29,
	NodeChanged_FinishToLock = 24,
	SubstateChange_In = 43,
	MainStory_Anim = 31,
	ContinueMove = 15,
	StanimaOverload = 5,
	ChessboardPlayerMove_UP = 37,
	ChallengeTaskUnlock = 18,
	NodeChanged_VisibleToInVisible = 19,
	HollowResultRewardItem = 40,
	HollowTaskFinish = 16,
	StanimaToDanger = 7,
	NodeChanged_InVisibleToVisible = 20,
	ToNextLevel = 9,
	NodeChanged_ShowEventToFinish = 26,
	NodeChanged_LockToShowEvent = 21,
	ChallengeTaskFinish = 17,
	HpToDanger = 11,
	MainStory_Create = 28,
	LostItem = 1,
	StanimaUp = 3,
	HollowStartPerform = 13,
	MainStory_ClickStar = 34,
	NodeChanged_LockToFinish = 23,
	ChessboardPlayerMove_RT = 36,
	Move = 14,
	HollowResultYorozuyaExpUp = 41,
	MainStory_ClickLevel = 33,
	NodeChanged_FinishToShowEvent = 25,
	SubstateChange_Out = 44,
};
