#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_543B6B88E17BAFE0.h"
#include "unitysdk/MoleMole/EnumSettingEntry.h"

class Class_1_CDA44BE4158CAA8A;

#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GETDEFAULTINDEX_OFFSET UNITYSDK_OFFSET(0x9918F80)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GETSETTINGCONTROLUNIT_OFFSET UNITYSDK_OFFSET(0x9918EE0)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GET_SETTINGCONTENTTYPE_OFFSET UNITYSDK_OFFSET(0x9918EC0)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GET__ISHIDEDEFAULTINDEX_OFFSET UNITYSDK_OFFSET(0x9918ED0)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_ISSHOWONUIINNER_OFFSET UNITYSDK_OFFSET(0x99190D0)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY__CTOR_OFFSET UNITYSDK_OFFSET(0x9919270)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY___BASE_GETDEFAULTINDEX_OFFSET UNITYSDK_OFFSET(0x9919310)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY___BASE_GETSETTINGCONTROLUNIT_OFFSET UNITYSDK_OFFSET(0x9919370)
#define MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY___BASE_ISSHOWONUIINNER_OFFSET UNITYSDK_OFFSET(0x9919380)

namespace MoleMole
{
	inline static constexpr unsigned int LanguageKeyboardLayoutSettingEntry_TypeDefinitionIndex = 65361;

	class LanguageKeyboardLayoutSettingEntry : public ::MoleMole::EnumSettingEntry
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY__CTOR_OFFSET))(this);
		}

		::Enum_3_543B6B88E17BAFE0 get_SettingContentType()
		{
			return ((::Enum_3_543B6B88E17BAFE0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GET_SETTINGCONTENTTYPE_OFFSET))(this);
		}

		::System::Boolean get__isHideDefaultIndex()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GET__ISHIDEDEFAULTINDEX_OFFSET))(this);
		}

		::Class_1_CDA44BE4158CAA8A* GetSettingControlUnit()
		{
			return ((::Class_1_CDA44BE4158CAA8A*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GETSETTINGCONTROLUNIT_OFFSET))(this);
		}

		::System::Int32 GetDefaultIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_GETDEFAULTINDEX_OFFSET))(this);
		}

		::System::Boolean IsShowOnUIInner()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY_ISSHOWONUIINNER_OFFSET))(this);
		}

		::System::Int32 __base_GetDefaultIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY___BASE_GETDEFAULTINDEX_OFFSET))(this);
		}

		::Class_1_CDA44BE4158CAA8A* __base_GetSettingControlUnit()
		{
			return ((::Class_1_CDA44BE4158CAA8A*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY___BASE_GETSETTINGCONTROLUNIT_OFFSET))(this);
		}

		::System::Boolean __base_IsShowOnUIInner()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_LANGUAGEKEYBOARDLAYOUTSETTINGENTRY___BASE_ISSHOWONUIINNER_OFFSET))(this);
		}
	};
}
