#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_1_F0E4E2848B1D52CE;
class Class_2_4BE21148C8967B21;
class Class_2_C7387D40D4120A48_2_Class_2_CF95F81DB4449032;
namespace MoleMole { class UIABStandbyPhaseWidgetController; }
namespace System { class Action; }

#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__0_OFFSET UNITYSDK_OFFSET(0x8FAC150)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__11_OFFSET UNITYSDK_OFFSET(0x8FAD120)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__13_OFFSET UNITYSDK_OFFSET(0x8FADFD0)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__1_OFFSET UNITYSDK_OFFSET(0x8FAC5C0)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__2_OFFSET UNITYSDK_OFFSET(0x8FAC700)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__3_OFFSET UNITYSDK_OFFSET(0x8FAC790)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__4_OFFSET UNITYSDK_OFFSET(0x8FAD280)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__5_OFFSET UNITYSDK_OFFSET(0x8FAD550)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__6_OFFSET UNITYSDK_OFFSET(0x8FAD590)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__7_OFFSET UNITYSDK_OFFSET(0x8FAD6C0)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__8_OFFSET UNITYSDK_OFFSET(0x8FAD7F0)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__9_OFFSET UNITYSDK_OFFSET(0x8FADB50)
#define MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__CTOR_OFFSET UNITYSDK_OFFSET(0x8FAC140)

namespace MoleMole
{
	inline static constexpr unsigned int UIABStandbyPhaseWidgetController___c__DisplayClass43_0_TypeDefinitionIndex = 39597;

	class UIABStandbyPhaseWidgetController___c__DisplayClass43_0 : public ::System::Object
	{
	public:
		::Class_2_4BE21148C8967B21* gold; // 0x10
		::Class_2_4BE21148C8967B21* rankProperty; // 0x18
		::Class_2_4BE21148C8967B21* bangbooNum; // 0x20
		::System::Action* __9__11; // 0x28
		::Class_1_F0E4E2848B1D52CE* viewModel; // 0x30
		::Class_2_C7387D40D4120A48_2_Class_2_CF95F81DB4449032* bangbooNumView; // 0x38
		::System::Action* __9__13; // 0x40
		::Class_2_4BE21148C8967B21* expProperty; // 0x48
		::MoleMole::UIABStandbyPhaseWidgetController* __4__this; // 0x50

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__CTOR_OFFSET))(this);
		}

		::System::Void _BindView_b__0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__0_OFFSET))(this);
		}

		::System::Void _BindView_b__1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__1_OFFSET))(this);
		}

		::System::Void _BindView_b__2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__2_OFFSET))(this);
		}

		::System::Void _BindView_b__3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__3_OFFSET))(this);
		}

		::System::Void _BindView_b__11()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__11_OFFSET))(this);
		}

		::System::Void _BindView_b__4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__4_OFFSET))(this);
		}

		::System::Void _BindView_b__5()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__5_OFFSET))(this);
		}

		::System::Void _BindView_b__6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__6_OFFSET))(this);
		}

		::System::Void _BindView_b__7()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__7_OFFSET))(this);
		}

		::System::Void _BindView_b__8()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__8_OFFSET))(this);
		}

		::System::Void _BindView_b__9()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__9_OFFSET))(this);
		}

		::System::Void _BindView_b__13()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABSTANDBYPHASEWIDGETCONTROLLER___C__DISPLAYCLASS43_0__BINDVIEW_B__13_OFFSET))(this);
		}
	};
}
