#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_8E90989A26BC6232.h"
#include "unitysdk/MoleMole/UIWindowController.h"

class Class_0_16E4307DCC419505_5;
class Class_1_A2FCB0C4C9740099;
class Class_2_208CC9941471731A_784;
class Class_2_79AE422BA06F6D26_258;
namespace MoleMole { class UIAbyssArpeggioTalentItemWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralTokenWidgetController; }
namespace System { class EventArgs; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET UNITYSDK_OFFSET(0x986C560)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x986C550)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONARPEGGIODATAREFRESH_OFFSET UNITYSDK_OFFSET(0x986D560)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONARPEGGIOTALENTUPGRADECLOSE_OFFSET UNITYSDK_OFFSET(0x986D6B0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONCLICKINFOBTN_OFFSET UNITYSDK_OFFSET(0x986DF00)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONCLICKOKBTN_OFFSET UNITYSDK_OFFSET(0x986DBA0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x986C570)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONITEMCHANGED_OFFSET UNITYSDK_OFFSET(0x986D740)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONSCROLLVIEWREFRESHDATA_OFFSET UNITYSDK_OFFSET(0x986D7B0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x986D3E0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x986C610)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x986CB80)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUPGRADESUCCESS_OFFSET UNITYSDK_OFFSET(0x986E110)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHARPEGGIODATA_OFFSET UNITYSDK_OFFSET(0x986D5F0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHBTNTEXT_OFFSET UNITYSDK_OFFSET(0x986BD60)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHRIGHTTALENTINFO_OFFSET UNITYSDK_OFFSET(0x986B480)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHTALENTICON_OFFSET UNITYSDK_OFFSET(0x986B7E0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHTALENTSKILLINFO_OFFSET UNITYSDK_OFFSET(0x986B6F0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHUPGRADEINFO_OFFSET UNITYSDK_OFFSET(0x986C040)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_SELECTTARGETCHAPTERSLOTITEM_OFFSET UNITYSDK_OFFSET(0x986D230)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_SETNOWCLICKSELECTITEM_OFFSET UNITYSDK_OFFSET(0x986D9B0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x986E370)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x986E380)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x986E3F0)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x986E400)
#define MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x986E410)

namespace MoleMole
{
	inline static constexpr unsigned int UIAbyssArpeggioTalentPageController_TypeDefinitionIndex = 78747;

	class UIAbyssArpeggioTalentPageController : public ::MoleMole::UIWindowController
	{
	public:
		::Class_2_79AE422BA06F6D26_258* _view; // 0x2F8
		::System::Collections::Generic::List_1<::Class_1_A2FCB0C4C9740099*>* talentDataList; // 0x300
		::MoleMole::UIAbyssArpeggioTalentItemWidgetController* nowSelectItem; // 0x308
		::MoleMole::UIGeneralTokenWidgetController* _tokenWidget; // 0x310
		::System::Boolean isScrollViewInit; // 0x318
		::System::Int32 nowSelectChapter; // 0x31C
		::System::Int32 nowSelectSlot; // 0x320
		::System::Boolean isOpneUpgrade; // 0x324
		::System::Boolean isDataDirty; // 0x325

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void RefreshRightTalentInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHRIGHTTALENTINFO_OFFSET))(this);
		}

		::System::Void RefreshTalentSkillInfo(::Class_2_208CC9941471731A_784* talentTemplate)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_208CC9941471731A_784*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHTALENTSKILLINFO_OFFSET))(this, talentTemplate);
		}

		::System::Void RefreshTalentIcon(::Class_2_208CC9941471731A_784* talentTemplate)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_208CC9941471731A_784*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHTALENTICON_OFFSET))(this, talentTemplate);
		}

		::System::Void RefreshBtnText()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHBTNTEXT_OFFSET))(this);
		}

		::System::Void RefreshUpgradeInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHUPGRADEINFO_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::Enum_3_8E90989A26BC6232 get_HotSwitchRootLayerState()
		{
			return ((::Enum_3_8E90989A26BC6232(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnArpeggioDataRefresh(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONARPEGGIODATAREFRESH_OFFSET))(this, args);
		}

		::System::Void OnArpeggioTalentUpgradeClose(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONARPEGGIOTALENTUPGRADECLOSE_OFFSET))(this, args);
		}

		::System::Void RefreshArpeggioData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_REFRESHARPEGGIODATA_OFFSET))(this);
		}

		::System::Void OnItemChanged(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONITEMCHANGED_OFFSET))(this, args);
		}

		::System::Void OnScrollViewRefreshData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONSCROLLVIEWREFRESHDATA_OFFSET))(this);
		}

		::System::Void SelectTargetChapterSlotItem(::System::Int32 chapterIndex, ::System::Int32 slotIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_SELECTTARGETCHAPTERSLOTITEM_OFFSET))(this, chapterIndex, slotIndex);
		}

		::System::Void SetNowClickSelectItem(::MoleMole::UIAbyssArpeggioTalentItemWidgetController* newSelectItem)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIAbyssArpeggioTalentItemWidgetController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_SETNOWCLICKSELECTITEM_OFFSET))(this, newSelectItem);
		}

		::System::Void OnClickOKBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONCLICKOKBTN_OFFSET))(this);
		}

		::System::Void OnClickInfoBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONCLICKINFOBTN_OFFSET))(this);
		}

		::System::Void OnUpgradeSuccess(::Class_0_16E4307DCC419505_5* rcvMessage)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_5*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER_ONUPGRADESUCCESS_OFFSET))(this, rcvMessage);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIABYSSARPEGGIOTALENTPAGECONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
