#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_6341039499F27211;
class Class_1_FAC248BEAF244E87;
class Class_2_69CBB7FF0BE6A673_4;
namespace MoleMole { class UIActivityCompRowTaskList02WidgetController; }
namespace MoleMole { class UIActivityCompRowTaskListWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }

#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_GETVIEW_OFFSET UNITYSDK_OFFSET(0xD856CE0)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xD856B50)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xD856BF0)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xD856A00)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xD856AA0)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_OPENROWTASKLIST02WIDGET_OFFSET UNITYSDK_OFFSET(0xD856E20)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_OPENROWTASKLISTWIDGET_OFFSET UNITYSDK_OFFSET(0xD856D50)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_SETACTIVITYQUESTONEROWSTATE_OFFSET UNITYSDK_OFFSET(0xD856FB0)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_SETACTIVITYQUESTTWOROWSTATE_OFFSET UNITYSDK_OFFSET(0xD856EF0)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xD857030)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xD857060)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xD8570D0)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xD857150)
#define MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xD8571B0)

namespace MoleMole
{
	inline static constexpr unsigned int UIActivityCompTaskList2WidgetController_TypeDefinitionIndex = 38445;

	class UIActivityCompTaskList2WidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_2_69CBB7FF0BE6A673_4* _view; // 0x2A0
		::Class_1_FAC248BEAF244E87* twoRowQuestHandler; // 0x2A8

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::Class_2_69CBB7FF0BE6A673_4* GetView()
		{
			return ((::Class_2_69CBB7FF0BE6A673_4*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_GETVIEW_OFFSET))(this);
		}

		::MoleMole::UIActivityCompRowTaskListWidgetController* OpenRowTaskListWidget()
		{
			return ((::MoleMole::UIActivityCompRowTaskListWidgetController*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_OPENROWTASKLISTWIDGET_OFFSET))(this);
		}

		::MoleMole::UIActivityCompRowTaskList02WidgetController* OpenRowTaskList02Widget()
		{
			return ((::MoleMole::UIActivityCompRowTaskList02WidgetController*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_OPENROWTASKLIST02WIDGET_OFFSET))(this);
		}

		::System::Void SetActivityQuestTwoRowState(::Class_1_FAC248BEAF244E87* newQuestHandler)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FAC248BEAF244E87*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_SETACTIVITYQUESTTWOROWSTATE_OFFSET))(this, newQuestHandler);
		}

		::System::Void SetActivityQuestOneRowState(::Class_1_6341039499F27211* questHandler)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_6341039499F27211*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER_SETACTIVITYQUESTONEROWSTATE_OFFSET))(this, questHandler);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMPTASKLIST2WIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
