#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_4_D06919D0930604DE_Enum_3_05BF65C41833FF20.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_48D56DACBE4271BC;
class Class_2_26C3D75B2738301A_1;
class Class_2_55792E721774BF92;
namespace MoleMole { class ActivityCombatPauseStageWidgetContext; }
namespace MoleMole { class UIActivityCombatPauseStageWidgetController_ViewModel; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_BUILDVIEWMODELDATABINDING_OFFSET UNITYSDK_OFFSET(0xA57A270)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_FINDQUESTINDEX_OFFSET UNITYSDK_OFFSET(0xA57B2B0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_GETLASTUNLOCKQUESTID_OFFSET UNITYSDK_OFFSET(0xA57AFF0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_GET_SELECTINDEX_OFFSET UNITYSDK_OFFSET(0xA57A4C0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_GET_SELECTQUESTID_OFFSET UNITYSDK_OFFSET(0xA57A5D0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_INITAUTODISPOSEDATABIND_OFFSET UNITYSDK_OFFSET(0xA57A1C0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xA57B5B0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONSELECTQUEST_OFFSET UNITYSDK_OFFSET(0xA57BCC0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0xA57AAE0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xA57B650)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xA57A810)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xA57AA30)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_REFRESHDATAS_OFFSET UNITYSDK_OFFSET(0xA57B3F0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_REFRESHQUESTDATA_OFFSET UNITYSDK_OFFSET(0xA57AD50)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_REFRESHSCROLLVIEW_OFFSET UNITYSDK_OFFSET(0xA57B7A0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_SET_SELECTQUESTID_OFFSET UNITYSDK_OFFSET(0xA57A6C0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0xA57B730)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__BUILDVIEWMODELDATABINDING_B__4_0_OFFSET UNITYSDK_OFFSET(0xA57BFE0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__BUILDVIEWMODELDATABINDING_B__4_1_OFFSET UNITYSDK_OFFSET(0xA57BFF0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xA57BEC0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__GET_SELECTINDEX_B__14_0_OFFSET UNITYSDK_OFFSET(0xA57C000)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_INITAUTODISPOSEDATABIND_OFFSET UNITYSDK_OFFSET(0xA57C030)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xA57C090)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0xA57C100)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xA57C170)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xA57C1F0)
#define MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xA57C250)

namespace MoleMole
{
	inline static constexpr unsigned int UIActivityCombatPauseStageWidgetController_TypeDefinitionIndex = 41257;

	class UIActivityCombatPauseStageWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		::Class_1_48D56DACBE4271BC* _propertySyncHelperForViewModel; // 0x2A0
		::MoleMole::UIActivityCombatPauseStageWidgetController_ViewModel* _viewModel; // 0x2A8
		::Class_2_26C3D75B2738301A_1* _view; // 0x2B0
		::MoleMole::ActivityCombatPauseStageWidgetContext* _context; // 0x2B8
		::System::Int32 _activityID; // 0x2C0
		::Class_4_D06919D0930604DE_Enum_3_05BF65C41833FF20 _activityBattleType; // 0x2C4
		::System::Collections::Generic::List_1<::Class_2_55792E721774BF92*>* _questDataList; // 0x2C8
		::System::Boolean _scrollViewDirty; // 0x2D0
		::System::Boolean _scrollViewSelectIndexDirty; // 0x2D1
		::System::Boolean _scrollToQuest; // 0x2D2

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void InitAutoDisposeDataBind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_INITAUTODISPOSEDATABIND_OFFSET))(this);
		}

		::System::Void BuildViewModelDataBinding()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_BUILDVIEWMODELDATABINDING_OFFSET))(this);
		}

		::System::Int32 get_SelectIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_GET_SELECTINDEX_OFFSET))(this);
		}

		::System::Int32 get_SelectQuestID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_GET_SELECTQUESTID_OFFSET))(this);
		}

		::System::Void set_SelectQuestID(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_SET_SELECTQUESTID_OFFSET))(this, value);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void RefreshDatas()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_REFRESHDATAS_OFFSET))(this);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Int32 FindQuestIndex(::System::Int32 questID)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_FINDQUESTINDEX_OFFSET))(this, questID);
		}

		::System::Void RefreshQuestData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_REFRESHQUESTDATA_OFFSET))(this);
		}

		::System::Int32 GetLastUnlockQuestID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_GETLASTUNLOCKQUESTID_OFFSET))(this);
		}

		::System::Void RefreshScrollView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_REFRESHSCROLLVIEW_OFFSET))(this);
		}

		::System::Void OnSelectQuest(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER_ONSELECTQUEST_OFFSET))(this, index);
		}

		::System::Void _BuildViewModelDataBinding_b__4_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__BUILDVIEWMODELDATABINDING_B__4_0_OFFSET))(this);
		}

		::System::Void _BuildViewModelDataBinding_b__4_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__BUILDVIEWMODELDATABINDING_B__4_1_OFFSET))(this);
		}

		::System::Boolean _get_SelectIndex_b__14_0(::Class_2_55792E721774BF92* x)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_2_55792E721774BF92*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER__GET_SELECTINDEX_B__14_0_OFFSET))(this, x);
		}

		::System::Void __base_InitAutoDisposeDataBind()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_INITAUTODISPOSEDATABIND_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYCOMBATPAUSESTAGEWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
