#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_5D3AF1309617E53D.h"
#include "unitysdk/MoleMole/BackFlowWidget.h"

class Class_0_16E4307DCC419505_7;
class Class_1_B5CB9AB596223833;
class Class_1_D4A342310E41758F;
class Class_1_E9D523024A7C9384;
class Class_2_5049726E037956C4;
class Class_2_CC8926C75B527F8D;
class Class_2_CC8926C75B527F8D_Class_2_1EE30F7DE42DCBDA;
namespace MoleMole { class UIBackFlowContext; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class EventArgs; }
namespace System::Collections::Generic { template <typename T> class List_1; }
template <typename T> class Class_2_0D31A1661D004892;

#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_CLICKCONSOLEMOVETAB_OFFSET UNITYSDK_OFFSET(0xB5E4410)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_GETVIEW_OFFSET UNITYSDK_OFFSET(0xB5E3FA0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_INITRETURNTABS_OFFSET UNITYSDK_OFFSET(0xB5E1240)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ISTASKTABALLSTATUS_OFFSET UNITYSDK_OFFSET(0xB5E22D0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONBACKFLOWAXLEDATACHANGED_OFFSET UNITYSDK_OFFSET(0xB5E42E0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONBACKFLOWTASKCHANGED_OFFSET UNITYSDK_OFFSET(0xB5E41F0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONBACKFLOWTASKTABCHANGED_OFFSET UNITYSDK_OFFSET(0xB5E4260)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCLICKFETCHALL_OFFSET UNITYSDK_OFFSET(0xB5E4580)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCLICKTAB_OFFSET UNITYSDK_OFFSET(0xB5E1E00)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCONSOLECLICKLEFTTAB_OFFSET UNITYSDK_OFFSET(0xB5E43A0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCONSOLECLICKRIGHTTAB_OFFSET UNITYSDK_OFFSET(0xB5E4510)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xB5E3880)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0xB5E3CA0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONITEMCHANGED_OFFSET UNITYSDK_OFFSET(0xB5E4010)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONRPCTAKESUCCESS_OFFSET UNITYSDK_OFFSET(0xB5E4A60)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0xB5E3920)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xB5E3EB0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xB5E2F80)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xB5E34E0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_OPENREWARDTAB_OFFSET UNITYSDK_OFFSET(0xB5E1970)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHFETCHALLBTN_OFFSET UNITYSDK_OFFSET(0xB5E2530)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHTABBUTTONSTATUS_OFFSET UNITYSDK_OFFSET(0xB5E2710)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHTABSTATUS_OFFSET UNITYSDK_OFFSET(0xB5E2000)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHTASKTABSCROLLVIEW_OFFSET UNITYSDK_OFFSET(0xB5E28F0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_SETTABBUTTONVIEWSTATE_OFFSET UNITYSDK_OFFSET(0xB5E2790)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_SHOWRETURNAXLE_OFFSET UNITYSDK_OFFSET(0xB5E3C20)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_SORTTABROWDATA_OFFSET UNITYSDK_OFFSET(0xB5E2CE0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xB5E4AD0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER__ONUIOPEN_B__18_0_OFFSET UNITYSDK_OFFSET(0xB5E4B00)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xB5E4B20)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0xB5E4B90)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0xB5E4BF0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xB5E4C60)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xB5E4CE0)
#define MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xB5E4CF0)

namespace MoleMole
{
	inline static constexpr unsigned int UIActivityReturningRewardWidgetController_TypeDefinitionIndex = 54101;

	class UIActivityReturningRewardWidgetController : public ::MoleMole::BackFlowWidget
	{
	public:
		::System::Collections::Generic::List_1<::Class_2_0D31A1661D004892<::Class_2_CC8926C75B527F8D_Class_2_1EE30F7DE42DCBDA*>*>* _tabBtnsArray; // 0x2C8
		::Class_2_CC8926C75B527F8D* _view; // 0x2D0
		::MoleMole::UIBackFlowContext* _context; // 0x2D8
		::Il2CppArray<::Class_1_D4A342310E41758F*>* taskTabDataArray; // 0x2E0
		::Il2CppArray<::Class_1_E9D523024A7C9384*>* taskTabViewArray; // 0x2E8
		::System::Int32 nowTaskTabIndex; // 0x2F0
		::System::Collections::Generic::List_1<::Class_1_B5CB9AB596223833*>* activityTabRowDataList; // 0x2F8
		::Class_2_5049726E037956C4* axleHandler; // 0x300

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void InitReturnTabs()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_INITRETURNTABS_OFFSET))(this);
		}

		::System::Void OpenRewardTab()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_OPENREWARDTAB_OFFSET))(this);
		}

		::System::Void RefreshTabStatus()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHTABSTATUS_OFFSET))(this);
		}

		::System::Boolean IsTaskTabAllStatus(::Class_1_D4A342310E41758F* tabData, ::Enum_3_5D3AF1309617E53D status)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_D4A342310E41758F*, ::Enum_3_5D3AF1309617E53D))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ISTASKTABALLSTATUS_OFFSET))(this, tabData, status);
		}

		::System::Void RefreshTabButtonStatus(::System::Int32 taskTabIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHTABBUTTONSTATUS_OFFSET))(this, taskTabIndex);
		}

		::System::Void SetTabButtonViewState(::System::Int32 targetIndex, ::System::Boolean isClick)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_SETTABBUTTONVIEWSTATE_OFFSET))(this, targetIndex, isClick);
		}

		::System::Void RefreshTaskTabScrollView(::System::Int32 taskTabIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHTASKTABSCROLLVIEW_OFFSET))(this, taskTabIndex);
		}

		::System::Int32 SortTabRowData(::Class_1_B5CB9AB596223833* a, ::Class_1_B5CB9AB596223833* b)
		{
			return ((::System::Int32(*)(::PVOID, ::Class_1_B5CB9AB596223833*, ::Class_1_B5CB9AB596223833*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_SORTTABROWDATA_OFFSET))(this, a, b);
		}

		::System::Void RefreshFetchAllBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_REFRESHFETCHALLBTN_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::Class_2_CC8926C75B527F8D* GetView()
		{
			return ((::Class_2_CC8926C75B527F8D*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_GETVIEW_OFFSET))(this);
		}

		::System::Void ShowReturnAxle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_SHOWRETURNAXLE_OFFSET))(this);
		}

		::System::Void OnItemChanged(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONITEMCHANGED_OFFSET))(this, args);
		}

		::System::Void OnBackFlowTaskChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONBACKFLOWTASKCHANGED_OFFSET))(this);
		}

		::System::Void OnBackFlowTaskTabChanged(::Class_1_D4A342310E41758F* activityTaskTab)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D4A342310E41758F*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONBACKFLOWTASKTABCHANGED_OFFSET))(this, activityTaskTab);
		}

		::System::Void OnBackFlowAxleDataChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONBACKFLOWAXLEDATACHANGED_OFFSET))(this);
		}

		::System::Void OnConsoleClickLeftTab()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCONSOLECLICKLEFTTAB_OFFSET))(this);
		}

		::System::Void OnConsoleClickRightTab()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCONSOLECLICKRIGHTTAB_OFFSET))(this);
		}

		::System::Void ClickConsoleMoveTab(::System::Boolean rightDir)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_CLICKCONSOLEMOVETAB_OFFSET))(this, rightDir);
		}

		::System::Void OnClickTab(::System::Int32 taskTabIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCLICKTAB_OFFSET))(this, taskTabIndex);
		}

		::System::Void OnClickFetchAll()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONCLICKFETCHALL_OFFSET))(this);
		}

		::System::Void OnRPCTakeSuccess(::Class_0_16E4307DCC419505_7* rcvMessage)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_7*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER_ONRPCTAKESUCCESS_OFFSET))(this, rcvMessage);
		}

		::System::Void _OnUIOpen_b__18_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER__ONUIOPEN_B__18_0_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIACTIVITYRETURNINGREWARDWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
