#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/ScrollViewItemWidgetController.h"

class Class_1_6D3ECB4C39924DFD;
class Class_1_BDEEA5009A8A636E;
class Class_2_637BE876956F8885;
class Class_2_F51BBF303F6FB2C0;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_CLEARPROPERTIES_OFFSET UNITYSDK_OFFSET(0xD0220A0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xD021A40)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xD021AE0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xD0218F0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xD021990)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_SETEMPTY_OFFSET UNITYSDK_OFFSET(0xD022340)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_SETMAX_OFFSET UNITYSDK_OFFSET(0xD0222E0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_UPDATEUI_OFFSET UNITYSDK_OFFSET(0xD021BC0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xD022430)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xD0224C0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xD022530)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xD0225B0)
#define MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xD022610)

namespace MoleMole
{
	inline static constexpr unsigned int UIBangbooStarUpAttributeRowWidgetController_TypeDefinitionIndex = 79071;

	class UIBangbooStarUpAttributeRowWidgetController : public ::MoleMole::ScrollViewItemWidgetController
	{
	public:
		::Class_2_637BE876956F8885* _view; // 0x2D0
		::Class_2_F51BBF303F6FB2C0* _data; // 0x2D8
		::Class_1_6D3ECB4C39924DFD* skill; // 0x2E0
		::System::Collections::Generic::List_1<::Class_1_BDEEA5009A8A636E*>* _propertyItems; // 0x2E8

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void UpdateUI(::Class_2_F51BBF303F6FB2C0* data, ::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_F51BBF303F6FB2C0*, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_UPDATEUI_OFFSET))(this, data, index);
		}

		::System::Void SetEmpty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_SETEMPTY_OFFSET))(this);
		}

		::System::Void ClearProperties()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_CLEARPROPERTIES_OFFSET))(this);
		}

		::System::Void SetMax()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER_SETMAX_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBANGBOOSTARUPATTRIBUTEROWWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
