#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_DB663931210BBC27_2.h"
#include "unitysdk/MoleMole/UIWindowController.h"
#include "unitysdk/Struct_2_49ABC235CB23B56F.h"

class Class_1_5A23D92A403D3CEB;
class Class_1_D12E4BF61CBE42EF;
class Class_2_79F6D62CE30E3F8E_40;
namespace MoleMole { class MonoGamepadModule; }
namespace MoleMole { class UIBPPurchaseContext; }
namespace MoleMole { class UIBPPurchseInfoWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralBtn03WidgetController; }
namespace System { class EventArgs; }

#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_BUYFAILCALLBACK_OFFSET UNITYSDK_OFFSET(0xC8FD340)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_BUYSUCCESSCALLBACK_OFFSET UNITYSDK_OFFSET(0xC8FD2B0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0xC8FAA70)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONCHECKSHOWPSSTOREICON_OFFSET UNITYSDK_OFFSET(0xC8FA980)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xC8FB790)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONGAMEPADMODULEFOCUS_OFFSET UNITYSDK_OFFSET(0xC8FBBE0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONGAMEPADMODULELOSTFOCUS_OFFSET UNITYSDK_OFFSET(0xC8FBDB0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0xC8FB6B0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONPURCHASEENDREFRESH_OFFSET UNITYSDK_OFFSET(0xC8FD1D0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONSHOPPINGMALLREQUESTREFRESHUPDATE_OFFSET UNITYSDK_OFFSET(0xC8FD3C0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0xC8FB620)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0xC8FB830)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xC8FB9C0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xC8FAB00)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xC8FACC0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_REFRESHBATTLEPASSSHOPGOOD_OFFSET UNITYSDK_OFFSET(0xC8FB300)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SETBPPURCHASECLOSETIMER_OFFSET UNITYSDK_OFFSET(0xC8FC0F0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SHOWADVANCEPURCHASEBPSHOP_OFFSET UNITYSDK_OFFSET(0xC8FCA20)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SHOWLUXURYPURCHASEBPSHOP_OFFSET UNITYSDK_OFFSET(0xC8FCE40)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SHOWNONEPURCHASEBPSHOP_OFFSET UNITYSDK_OFFSET(0xC8FC4D0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_TRYOVERRIDESELECTONFOCUS_OFFSET UNITYSDK_OFFSET(0xC8FBF80)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0xC8FAA80)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xC8FD440)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xC8FD450)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONGAMEPADMODULEFOCUS_OFFSET UNITYSDK_OFFSET(0xC8FD4C0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONGAMEPADMODULELOSTFOCUS_OFFSET UNITYSDK_OFFSET(0xC8FD530)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0xC8FD5A0)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0xC8FD600)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0xC8FD610)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xC8FD620)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xC8FD630)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xC8FD640)
#define MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_TRYOVERRIDESELECTONFOCUS_OFFSET UNITYSDK_OFFSET(0xC8FD6B0)

namespace MoleMole
{
	inline static constexpr unsigned int UIBPPurchaseDialogPopWindowController_TypeDefinitionIndex = 78690;

	class UIBPPurchaseDialogPopWindowController : public ::MoleMole::UIWindowController
	{
	public:
		::Class_2_79F6D62CE30E3F8E_40* _view; // 0x2F8
		::Struct_2_49ABC235CB23B56F _timerHandle; // 0x300
		::Class_1_5A23D92A403D3CEB* purchaseInfoHandler; // 0x310
		::MoleMole::UIBPPurchaseContext* context; // 0x318
		::MoleMole::UIBPPurchseInfoWidgetController* infoWidgetController; // 0x320
		::MoleMole::UIGeneralBtn03WidgetController* infoBtn; // 0x328

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnCheckShowPSStoreIcon(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONCHECKSHOWPSSTOREICON_OFFSET))(this, args);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnGamepadModuleFocus(::MoleMole::MonoGamepadModule* gamepadModule)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONGAMEPADMODULEFOCUS_OFFSET))(this, gamepadModule);
		}

		::System::Void OnGamepadModuleLostFocus(::MoleMole::MonoGamepadModule* gamepadModule)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONGAMEPADMODULELOSTFOCUS_OFFSET))(this, gamepadModule);
		}

		::System::Boolean TryOverrideSelectOnFocus(::MoleMole::MonoGamepadModule* gamepadModule, ::System::Int32& selectIndex)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::MonoGamepadModule*, ::System::Int32&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_TRYOVERRIDESELECTONFOCUS_OFFSET))(this, gamepadModule, selectIndex);
		}

		::System::Void RefreshBattlePassShopGood()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_REFRESHBATTLEPASSSHOPGOOD_OFFSET))(this);
		}

		::System::Void SetBPPurchaseCloseTimer(::Class_1_D12E4BF61CBE42EF* goodItem)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D12E4BF61CBE42EF*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SETBPPURCHASECLOSETIMER_OFFSET))(this, goodItem);
		}

		::System::Void OnPurchaseEndRefresh()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONPURCHASEENDREFRESH_OFFSET))(this);
		}

		::System::Void ShowNonePurchaseBPShop(::Class_1_D12E4BF61CBE42EF* advanceItem, ::Class_1_D12E4BF61CBE42EF* luxuryItem, ::Class_1_D12E4BF61CBE42EF* improveItem)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D12E4BF61CBE42EF*, ::Class_1_D12E4BF61CBE42EF*, ::Class_1_D12E4BF61CBE42EF*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SHOWNONEPURCHASEBPSHOP_OFFSET))(this, advanceItem, luxuryItem, improveItem);
		}

		::System::Void ShowAdvancePurchaseBPShop(::Class_1_D12E4BF61CBE42EF* improveItem)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D12E4BF61CBE42EF*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SHOWADVANCEPURCHASEBPSHOP_OFFSET))(this, improveItem);
		}

		::System::Void ShowLuxuryPurchaseBPShop()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_SHOWLUXURYPURCHASEBPSHOP_OFFSET))(this);
		}

		::System::Void BuySuccessCallback(::Class_1_D12E4BF61CBE42EF* battlePassItem, ::Enum_3_DB663931210BBC27_2 purchaseType)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D12E4BF61CBE42EF*, ::Enum_3_DB663931210BBC27_2))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_BUYSUCCESSCALLBACK_OFFSET))(this, battlePassItem, purchaseType);
		}

		::System::Void BuyFailCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_BUYFAILCALLBACK_OFFSET))(this);
		}

		::System::Void OnShoppingMallRequestRefreshUpdate(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER_ONSHOPPINGMALLREQUESTREFRESHUPDATE_OFFSET))(this, args);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnGamepadModuleFocus(::MoleMole::MonoGamepadModule* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONGAMEPADMODULEFOCUS_OFFSET))(this, P0);
		}

		::System::Void __base_OnGamepadModuleLostFocus(::MoleMole::MonoGamepadModule* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONGAMEPADMODULELOSTFOCUS_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Boolean __base_TryOverrideSelectOnFocus(::MoleMole::MonoGamepadModule* P0, ::System::Int32& P1)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::MonoGamepadModule*, ::System::Int32&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIBPPURCHASEDIALOGPOPWINDOWCONTROLLER___BASE_TRYOVERRIDESELECTONFOCUS_OFFSET))(this, P0, P1);
		}
	};
}
