#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_B13993C64A516F80_Enum_3_3535D88093A528E5.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_2D436BB26C69B677;
class Class_2_50EEBE86A7ED1CAF_1;
namespace MoleMole { class UICinemaMultiClickBubbleIndicatorWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class String; }

#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_CALLREMOVE_OFFSET UNITYSDK_OFFSET(0xBB13560)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_FORCEFADEOUT_OFFSET UNITYSDK_OFFSET(0xBB13210)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ISWAITINGTOBEREMOVED_OFFSET UNITYSDK_OFFSET(0xBB134E0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xBB12F30)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xBB12E80)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0xBB126A0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xBB12FD0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xBB12600)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_PAUSE_OFFSET UNITYSDK_OFFSET(0xBB13400)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_RESETBUBBLE_OFFSET UNITYSDK_OFFSET(0xBB13640)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_RESUME_OFFSET UNITYSDK_OFFSET(0xBB13470)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_SETGAMEPADUI_OFFSET UNITYSDK_OFFSET(0xBB12CF0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_TRIGGERFADEOUTBYCLEARALLBUBBLE_OFFSET UNITYSDK_OFFSET(0xBB13290)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_TRYCLICKBUBBLE_OFFSET UNITYSDK_OFFSET(0xBB130B0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_UPDATEPLAY_OFFSET UNITYSDK_OFFSET(0xBB13310)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xBB13780)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER__ONSHOW_B__6_0_OFFSET UNITYSDK_OFFSET(0xBB137B0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xBB137C0)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xBB13830)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0xBB13890)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xBB13900)
#define MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xBB13980)

namespace MoleMole
{
	inline static constexpr unsigned int UICinemaSingleMultiClickBubbleRightWidgetController_TypeDefinitionIndex = 41206;

	class UICinemaSingleMultiClickBubbleRightWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		// static const ::System::String* FADE_IN_ANIM; // 0x0
		// static const ::System::String* FADE_OUT_ANIM; // 0x0
		// static const ::System::String* FADE_OUT_WHEN_SUCCESS; // 0x0
		// static const ::System::String* CLICK_ANIM; // 0x0
		::Class_2_50EEBE86A7ED1CAF_1* _view; // 0x2A0
		::Class_1_2D436BB26C69B677* _baseController; // 0x2A8
		::System::Int32 _hitNum; // 0x2B0
		::System::Int32 _currEmptyIdx; // 0x2B4
		::Il2CppArray<::MoleMole::UICinemaMultiClickBubbleIndicatorWidgetController*>* _hitIndiControllerArray; // 0x2B8
		::Class_1_B13993C64A516F80_Enum_3_3535D88093A528E5 _bubbleLocation; // 0x2C0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Boolean TryClickBubble()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_TRYCLICKBUBBLE_OFFSET))(this);
		}

		::System::Void ForceFadeOut(::System::Boolean isImmediate)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_FORCEFADEOUT_OFFSET))(this, isImmediate);
		}

		::System::Void TriggerFadeOutByClearAllBubble()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_TRIGGERFADEOUTBYCLEARALLBUBBLE_OFFSET))(this);
		}

		::System::Void UpdatePlay(::System::Single deltaTime)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_UPDATEPLAY_OFFSET))(this, deltaTime);
		}

		::System::Void Pause()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_PAUSE_OFFSET))(this);
		}

		::System::Void Resume()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_RESUME_OFFSET))(this);
		}

		::System::Boolean IsWaitingToBeRemoved()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_ISWAITINGTOBEREMOVED_OFFSET))(this);
		}

		::System::Void CallRemove()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_CALLREMOVE_OFFSET))(this);
		}

		::System::Void ResetBubble()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_RESETBUBBLE_OFFSET))(this);
		}

		::System::Void SetGamepadUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER_SETGAMEPADUI_OFFSET))(this);
		}

		::System::Void _OnShow_b__6_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER__ONSHOW_B__6_0_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UICINEMASINGLEMULTICLICKBUBBLERIGHTWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
