#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_F57C3EEEB03201AF.h"

namespace System { class String; }
template <typename T> class Class_0_16E4307DCC419505_119;

#define MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_GET_NAME_OFFSET UNITYSDK_OFFSET(0xCC7E9E0)
#define MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_GET_PATH_OFFSET UNITYSDK_OFFSET(0xCC7EA00)
#define MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_ONCREATEPROPERTY_OFFSET UNITYSDK_OFFSET(0xCC7EA20)
#define MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_SET_NAME_OFFSET UNITYSDK_OFFSET(0xCC7E9F0)
#define MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_SET_PATH_OFFSET UNITYSDK_OFFSET(0xCC7EA10)
#define MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xCC7E230)

namespace MoleMole
{
	inline static constexpr unsigned int UIDevFlowerArrangementRowWidgetController_ViewModel_TypeDefinitionIndex = 42712;

	class UIDevFlowerArrangementRowWidgetController_ViewModel : public ::Class_1_F57C3EEEB03201AF
	{
	public:
		::Class_0_16E4307DCC419505_119<::System::String*>* _Name_k__BackingField; // 0x60
		::Class_0_16E4307DCC419505_119<::System::String*>* _Path_k__BackingField; // 0x68

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL__CTOR_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_119<::System::String*>* get_Name()
		{
			return ((::Class_0_16E4307DCC419505_119<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_GET_NAME_OFFSET))(this);
		}

		::System::Void set_Name(::Class_0_16E4307DCC419505_119<::System::String*>* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_119<::System::String*>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_SET_NAME_OFFSET))(this, value);
		}

		::Class_0_16E4307DCC419505_119<::System::String*>* get_Path()
		{
			return ((::Class_0_16E4307DCC419505_119<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_GET_PATH_OFFSET))(this);
		}

		::System::Void set_Path(::Class_0_16E4307DCC419505_119<::System::String*>* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_119<::System::String*>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_SET_PATH_OFFSET))(this, value);
		}

		::System::Void OnCreateProperty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIDEVFLOWERARRANGEMENTROWWIDGETCONTROLLER_VIEWMODEL_ONCREATEPROPERTY_OFFSET))(this);
		}
	};
}
