#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_2_6D99A03C58ED2B6E_Enum_3_838CCC65057AB833.h"
#include "unitysdk/Cysharp/Threading/Tasks/UniTaskVoid.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/InputLogicEventType.h"
#include "unitysdk/MoleMole/UIGeneral3DModelDialogPopWindowController_SeekState.h"
#include "unitysdk/MoleMole/UIGeneral3DModelDialogPopWindowController___c__DisplayClass27_0.h"
#include "unitysdk/MoleMole/UIWindowController.h"
#include "unitysdk/UnityEngine/Quaternion.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_30;
class Class_2_79AE422BA06F6D26_60;
class Class_2_B19769B3B0092EA9;
class Class_2_C2B4B123B5A9B78A;
class MonoUITableScrollV2;
class TouchEventDispatcher;
namespace MoleMole { class TweenFov; }
namespace MoleMole { class TweenPosition; }
namespace MoleMole { class TweenQuaternion; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneral3DModelDialogPopWindowController_Context; }
namespace MoleMole { class UIGeneral3DModelDialogPopWindowController_General3DModelDialogSubtitleViewer; }
namespace MoleMole::Config { class ConfigSoundWave; }
namespace MoleMole::Config { class ConfigSoundWaveKey; }
namespace System { class Action; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace System::Threading { class CancellationTokenSource; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine::EventSystems { class PointerEventData; }
namespace UnityEngine::UI::Extension { class InteractionRangeProcessor_Fov_ByScrollY; }
namespace UnityEngine::UI::Extension { class UISlider; }

#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_CLICKPAUSEBTN_OFFSET UNITYSDK_OFFSET(0xDFB4560)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_CLICKPLAYBTN_OFFSET UNITYSDK_OFFSET(0xDFB3D80)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_FORCESIMULATETWOPOINTDRAG_OFFSET UNITYSDK_OFFSET(0xDFB6800)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELCURCAMERAFOV_OFFSET UNITYSDK_OFFSET(0xDFB7D70)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELCURCAMERASTICKPOS_OFFSET UNITYSDK_OFFSET(0xDFB7FF0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELCURROTATION_OFFSET UNITYSDK_OFFSET(0xDFB7A50)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELINITCAMERAFOV_OFFSET UNITYSDK_OFFSET(0xDFB5000)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELINITCAMERASTICKPOS_OFFSET UNITYSDK_OFFSET(0xDFB7EE0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELINITROTATION_OFFSET UNITYSDK_OFFSET(0xDFB7B40)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_CONFIG_OFFSET UNITYSDK_OFFSET(0xDFB31D0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_DRAGPENETRATEDISPATCHER_OFFSET UNITYSDK_OFFSET(0xDFB27E0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_ISPAUSE_OFFSET UNITYSDK_OFFSET(0xDFB9480)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_RESETDURATION_OFFSET UNITYSDK_OFFSET(0xDFB7C90)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_SCROLLVIEW_OFFSET UNITYSDK_OFFSET(0xDFB24F0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_SUBTITLEVIEWER_OFFSET UNITYSDK_OFFSET(0xDFB9490)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0xDFAEEF0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_HANDLESPECIALWEAPON_OFFSET UNITYSDK_OFFSET(0xDFB4BB0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_HIDEDIALOG_OFFSET UNITYSDK_OFFSET(0xDFB9650)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_INITMAXSIZEFOV_OFFSET UNITYSDK_OFFSET(0xDFB50E0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_INITPROCESSORS_OFFSET UNITYSDK_OFFSET(0xDFB5FD0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_INITSLIDER_OFFSET UNITYSDK_OFFSET(0xDFB4E60)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_KILLPROCESSORS_OFFSET UNITYSDK_OFFSET(0xDFB5D90)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_LATEUPDATE_OFFSET UNITYSDK_OFFSET(0xDFB3250)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKBACKSPACE_OFFSET UNITYSDK_OFFSET(0xDFAF980)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKHIDEORSHOWUI_IMPL_OFFSET UNITYSDK_OFFSET(0xDFB6F80)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKHIDEORSHOWUI_OFFSET UNITYSDK_OFFSET(0xDFAF8A0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKRESET_OFFSET UNITYSDK_OFFSET(0xDFB7150)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKSCALESLIDERBTN_OFFSET UNITYSDK_OFFSET(0xDFB58B0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKSCALESLIDERLEFT_OFFSET UNITYSDK_OFFSET(0xDFB57E0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKSCALESLIDERRIGHT_OFFSET UNITYSDK_OFFSET(0xDFB5BB0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xDFB1B00)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONENDOFVOICE_OFFSET UNITYSDK_OFFSET(0xDFB43F0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0xDFB1BA0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0xDFB2C30)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONINTERACTCALLBACK_OFFSET UNITYSDK_OFFSET(0xDFB6670)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONISPAUSECHANGED_OFFSET UNITYSDK_OFFSET(0xDFB4740)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xDFB2AC0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONLOGICPOINTDOWNHANDLE_OFFSET UNITYSDK_OFFSET(0xDFB3840)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONLOGICPOINTUPHANDLE_OFFSET UNITYSDK_OFFSET(0xDFB3320)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONPOINTCLICK_OFFSET UNITYSDK_OFFSET(0xDFAF740)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONPOINTDOWNHANDLE_OFFSET UNITYSDK_OFFSET(0xDFB37C0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONPOINTUPHANDLE_OFFSET UNITYSDK_OFFSET(0xDFB3D10)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONRTMODELLOADED_OFFSET UNITYSDK_OFFSET(0xDFB68F0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONSCALESLIDERVALUECHANGE_OFFSET UNITYSDK_OFFSET(0xDFB5750)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONSLIDERVALUECHANGE_OFFSET UNITYSDK_OFFSET(0xDFB3740)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0xDFB1E00)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xDFB1F70)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xDFAEF00)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xDFAFA50)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONVOICEPOSTSUCCESS_OFFSET UNITYSDK_OFFSET(0xDFB4220)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_PROCESSUIAVATAR_OFFSET UNITYSDK_OFFSET(0xDFB29E0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHDRAGPENETRATEENABLE_OFFSET UNITYSDK_OFFSET(0xDFB2690)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHRTOFFSET_OFFSET UNITYSDK_OFFSET(0xDFB1840)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHRTVIEW_OFFSET UNITYSDK_OFFSET(0xDFB13D0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHSCALEUI_OFFSET UNITYSDK_OFFSET(0xDFB10F0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_RELEASERTMODEL_OFFSET UNITYSDK_OFFSET(0xDFB1C60)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_RELEASERTUNIT_1_OFFSET UNITYSDK_OFFSET(0xDFB2230)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_RELEASERTUNIT_OFFSET UNITYSDK_OFFSET(0xDFB1EE0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SETENDCB_OFFSET UNITYSDK_OFFSET(0xDFB2A50)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SET_ISPAUSE_OFFSET UNITYSDK_OFFSET(0xDFB1340)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SHOWDIALOGID_OFFSET UNITYSDK_OFFSET(0xDFB9540)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SHOWHIDESLIDERUI_OFFSET UNITYSDK_OFFSET(0xDFB7010)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SHOWSLIDER_OFFSET UNITYSDK_OFFSET(0xDFB5C80)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_TRYFADEINUI_OFFSET UNITYSDK_OFFSET(0xDFAF820)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATEPLAYPOSITION_OFFSET UNITYSDK_OFFSET(0xDFB8280)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATEPROGRESSINFOSLIDER_OFFSET UNITYSDK_OFFSET(0xDFB8400)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATESOUNDWAVE_OFFSET UNITYSDK_OFFSET(0xDFB8720)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATESUBTITLE_OFFSET UNITYSDK_OFFSET(0xDFB88E0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0xDFB8200)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xDFB9790)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__INITPROCESSORS_B__64_0_OFFSET UNITYSDK_OFFSET(0xDFB9AC0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__ONINPUTACTION_G__CALSPEED_27_1_OFFSET UNITYSDK_OFFSET(0xDFB98E0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__ONINPUTACTION_G__HANDLESLIDER_27_0_OFFSET UNITYSDK_OFFSET(0xDFB3050)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__ONUIINIT_B__4_0_OFFSET UNITYSDK_OFFSET(0xDFB98B0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xDFB9AD0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0xDFB9B40)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0xDFB9BA0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xDFB9BD0)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0xDFB9C30)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xDFB9C40)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xDFB9C50)
#define MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xDFB9C60)

namespace MoleMole
{
	inline static constexpr unsigned int UIGeneral3DModelDialogPopWindowController_TypeDefinitionIndex = 42254;

	class UIGeneral3DModelDialogPopWindowController : public ::MoleMole::UIWindowController
	{
	public:
		// static const ::System::String* DragPenetrateKey; // 0x0
		::Class_2_79AE422BA06F6D26_60* _view; // 0x2F8
		::System::String* voicePath; // 0x300
		::System::Boolean enableScale; // 0x308
		::MonoUITableScrollV2* m_scrollView; // 0x310
		::TouchEventDispatcher* m_dragPenetrateDispatcher; // 0x318
		::System::Collections::Generic::List_1<::MoleMole::InputLogicEventType>* FadeinUIEvents; // 0x320
		::System::Boolean needRePlay; // 0x328
		::System::Threading::CancellationTokenSource* m_taskSource; // 0x330
		::System::Boolean isLoadingRTModel; // 0x338
		::System::Collections::Generic::List_1<::System::Int32>* oldTabHandles; // 0x340
		::System::Boolean sliderInited; // 0x348
		::System::Single m_maxSizeFov; // 0x34C
		::System::Boolean m_maxSizeFovInited; // 0x350
		::System::String* NonScaleRootFadein; // 0x358
		::System::String* NonScaleRootFadeout; // 0x360
		::UnityEngine::UI::Extension::InteractionRangeProcessor_Fov_ByScrollY* fovProcessor; // 0x368
		::System::Int32 scalePatternID; // 0x370
		::System::Boolean showingUI; // 0x374
		::MoleMole::TweenQuaternion* m_modelRotTween; // 0x378
		::MoleMole::TweenPosition* m_stickScaleTween; // 0x380
		::MoleMole::TweenFov* m_fovTween; // 0x388
		::System::Single playPosition; // 0x390
		::System::Single lastRefreshTime; // 0x394
		::MoleMole::UIGeneral3DModelDialogPopWindowController_Context* _context; // 0x398
		::Class_2_6D99A03C58ED2B6E_Enum_3_838CCC65057AB833 clueType; // 0x3A0
		::System::Int32 showSettingType; // 0x3A4
		::System::Boolean useParallelLayer; // 0x3A8
		::System::UInt32 soundPlayingId; // 0x3AC
		::System::UInt32 soundPendingId; // 0x3B0
		::System::Boolean _isPause; // 0x3B4
		::Il2CppArray<::MoleMole::Config::ConfigSoundWaveKey*>* soundWaveArr; // 0x3B8
		::System::Single maxSoundLen; // 0x3C0
		::Class_2_C2B4B123B5A9B78A* _rtUnit; // 0x3C8
		::System::Single endVoiceTime; // 0x3D0
		::MoleMole::Config::ConfigSoundWave* configSoundWave; // 0x3D8
		::System::Boolean _pointerUpFromEventSystem; // 0x3E0
		::System::Boolean _triggerSliderThisFrame; // 0x3E1
		::System::Boolean _sliderDragging; // 0x3E2
		::System::Single _sliderDraggingTime; // 0x3E4
		::System::Action* endCb; // 0x3E8
		::MoleMole::UIGeneral3DModelDialogPopWindowController_SeekState _seekState; // 0x3F0
		::System::Single _seekTimeOut; // 0x3F4
		::MoleMole::UIGeneral3DModelDialogPopWindowController_General3DModelDialogSubtitleViewer* _subtitleViewer; // 0x3F8
		::Class_2_B19769B3B0092EA9* curSubTitle; // 0x400
		::Class_2_B19769B3B0092EA9* nextSubTitle; // 0x408
		::System::Int32 nextIndex; // 0x410

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnPointClick(::UnityEngine::EventSystems::PointerEventData* eventdata)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::EventSystems::PointerEventData*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONPOINTCLICK_OFFSET))(this, eventdata);
		}

		::System::Boolean TryFadeinUI()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_TRYFADEINUI_OFFSET))(this);
		}

		::System::Void OnClickBackSpace()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKBACKSPACE_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::MonoUITableScrollV2* get_ScrollView()
		{
			return ((::MonoUITableScrollV2*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_SCROLLVIEW_OFFSET))(this);
		}

		::System::Void RefreshDragPenetrateEnable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHDRAGPENETRATEENABLE_OFFSET))(this);
		}

		::TouchEventDispatcher* get_DragPenetrateDispatcher()
		{
			return ((::TouchEventDispatcher*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_DRAGPENETRATEDISPATCHER_OFFSET))(this);
		}

		::System::Void ProcessUIAvatar(::System::Int32 avatarConfig, ::System::Int32 showTypeIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_PROCESSUIAVATAR_OFFSET))(this, avatarConfig, showTypeIndex);
		}

		::System::Void SetEndCb(::System::Action* callback)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SETENDCB_OFFSET))(this, callback);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::Class_0_16E4307DCC419505_30* get_Config()
		{
			return ((::Class_0_16E4307DCC419505_30*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_CONFIG_OFFSET))(this);
		}

		::System::Void LateUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_LATEUPDATE_OFFSET))(this);
		}

		::System::Void OnSliderValueChange(::System::Single progress)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONSLIDERVALUECHANGE_OFFSET))(this, progress);
		}

		::System::Void OnPointDownHandle(::UnityEngine::EventSystems::PointerEventData* obj)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::EventSystems::PointerEventData*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONPOINTDOWNHANDLE_OFFSET))(this, obj);
		}

		::System::Void OnLogicPointDownHandle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONLOGICPOINTDOWNHANDLE_OFFSET))(this);
		}

		::System::Void OnPointUpHandle(::UnityEngine::EventSystems::PointerEventData* obj)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::EventSystems::PointerEventData*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONPOINTUPHANDLE_OFFSET))(this, obj);
		}

		::System::Void OnLogicPointUpHandle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONLOGICPOINTUPHANDLE_OFFSET))(this);
		}

		::System::Void ClickPlayBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_CLICKPLAYBTN_OFFSET))(this);
		}

		::System::Void OnVoicePostSuccess(::System::UInt32 pendingId, ::System::UInt32 playingId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONVOICEPOSTSUCCESS_OFFSET))(this, pendingId, playingId);
		}

		::System::Void OnEndOfVoice(::System::UInt32 pendingId, ::System::UInt32 playingId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONENDOFVOICE_OFFSET))(this, pendingId, playingId);
		}

		::System::Void ClickPauseBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_CLICKPAUSEBTN_OFFSET))(this);
		}

		::System::Void OnIsPauseChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONISPAUSECHANGED_OFFSET))(this);
		}

		::System::Void RefreshRTView(::System::Boolean showRT)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHRTVIEW_OFFSET))(this, showRT);
		}

		::System::Void HandleSpecialWeapon()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_HANDLESPECIALWEAPON_OFFSET))(this);
		}

		::System::Void InitSlider(::UnityEngine::UI::Extension::UISlider* slider)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::UI::Extension::UISlider*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_INITSLIDER_OFFSET))(this, slider);
		}

		::System::Void InitMaxSizeFov()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_INITMAXSIZEFOV_OFFSET))(this);
		}

		::System::Void OnScaleSliderValueChange(::System::Single value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONSCALESLIDERVALUECHANGE_OFFSET))(this, value);
		}

		::System::Void OnClickScaleSliderLeft()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKSCALESLIDERLEFT_OFFSET))(this);
		}

		::System::Void OnClickScaleSliderRight()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKSCALESLIDERRIGHT_OFFSET))(this);
		}

		::System::Void OnClickScaleSliderBtn(::System::Boolean plusOrMinus)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKSCALESLIDERBTN_OFFSET))(this, plusOrMinus);
		}

		::System::Void RefreshScaleUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHSCALEUI_OFFSET))(this);
		}

		::System::Void RefreshRTOffset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_REFRESHRTOFFSET_OFFSET))(this);
		}

		::System::Void ShowSlider(::System::Boolean state)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SHOWSLIDER_OFFSET))(this, state);
		}

		::System::Void KillProcessors()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_KILLPROCESSORS_OFFSET))(this);
		}

		::System::Void InitProcessors()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_INITPROCESSORS_OFFSET))(this);
		}

		::System::Void OnInteractCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONINTERACTCALLBACK_OFFSET))(this);
		}

		::System::Void ForceSimulateTwoPointDrag(::System::Single delta)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_FORCESIMULATETWOPOINTDRAG_OFFSET))(this, delta);
		}

		::System::Void OnRTModelLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONRTMODELLOADED_OFFSET))(this);
		}

		::System::Void OnClickHideOrShowUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKHIDEORSHOWUI_OFFSET))(this);
		}

		::Cysharp::Threading::Tasks::UniTaskVoid OnClickHideOrShowUI_Impl()
		{
			return ((::Cysharp::Threading::Tasks::UniTaskVoid(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKHIDEORSHOWUI_IMPL_OFFSET))(this);
		}

		::System::Void ShowHideSliderUI(::System::Boolean show)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SHOWHIDESLIDERUI_OFFSET))(this, show);
		}

		::System::Void OnClickReset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_ONCLICKRESET_OFFSET))(this);
		}

		::System::Single get_ResetDuration()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_RESETDURATION_OFFSET))(this);
		}

		::UnityEngine::Quaternion GetModelInitRotation()
		{
			return ((::UnityEngine::Quaternion(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELINITROTATION_OFFSET))(this);
		}

		::UnityEngine::Quaternion GetModelCurRotation()
		{
			return ((::UnityEngine::Quaternion(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELCURROTATION_OFFSET))(this);
		}

		::UnityEngine::Vector3 GetModelInitCameraStickPos()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELINITCAMERASTICKPOS_OFFSET))(this);
		}

		::UnityEngine::Vector3 GetModelCurCameraStickPos()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELCURCAMERASTICKPOS_OFFSET))(this);
		}

		::System::Single GetModelInitCameraFov()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELINITCAMERAFOV_OFFSET))(this);
		}

		::System::Single GetModelCurCameraFov()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GETMODELCURCAMERAFOV_OFFSET))(this);
		}

		::System::Void ReleaseRTModel(::Class_2_C2B4B123B5A9B78A* rtUnit)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_C2B4B123B5A9B78A*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_RELEASERTMODEL_OFFSET))(this, rtUnit);
		}

		::System::Void ReleaseRTUnit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_RELEASERTUNIT_OFFSET))(this);
		}

		::System::Void ReleaseRTUnit_1(::Class_2_C2B4B123B5A9B78A*& rtUnit)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_C2B4B123B5A9B78A*&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_RELEASERTUNIT_1_OFFSET))(this, rtUnit);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void UpdatePlayPosition()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATEPLAYPOSITION_OFFSET))(this);
		}

		::System::Void UpdateProgressInfoSlider()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATEPROGRESSINFOSLIDER_OFFSET))(this);
		}

		::System::Void UpdateSoundWave()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATESOUNDWAVE_OFFSET))(this);
		}

		::System::Boolean get_isPause()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_ISPAUSE_OFFSET))(this);
		}

		::System::Void set_isPause(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SET_ISPAUSE_OFFSET))(this, value);
		}

		::MoleMole::UIGeneral3DModelDialogPopWindowController_General3DModelDialogSubtitleViewer* get_subtitleViewer()
		{
			return ((::MoleMole::UIGeneral3DModelDialogPopWindowController_General3DModelDialogSubtitleViewer*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_GET_SUBTITLEVIEWER_OFFSET))(this);
		}

		::System::Void ShowDialogId(::System::String* subtitleKey)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_SHOWDIALOGID_OFFSET))(this, subtitleKey);
		}

		::System::Void HideDialog()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_HIDEDIALOG_OFFSET))(this);
		}

		::System::Void UpdateSubTitle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER_UPDATESUBTITLE_OFFSET))(this);
		}

		::UnityEngine::GameObject* _OnUIInit_b__4_0()
		{
			return ((::UnityEngine::GameObject*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__ONUIINIT_B__4_0_OFFSET))(this);
		}

		::System::Boolean _OnInputAction_g__HandleSlider_27_0(::MoleMole::UIGeneral3DModelDialogPopWindowController___c__DisplayClass27_0& a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::UIGeneral3DModelDialogPopWindowController___c__DisplayClass27_0&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__ONINPUTACTION_G__HANDLESLIDER_27_0_OFFSET))(this, a1);
		}

		::System::Single _OnInputAction_g__CalSpeed_27_1(::MoleMole::UIGeneral3DModelDialogPopWindowController___c__DisplayClass27_0& a1)
		{
			return ((::System::Single(*)(::PVOID, ::MoleMole::UIGeneral3DModelDialogPopWindowController___c__DisplayClass27_0&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__ONINPUTACTION_G__CALSPEED_27_1_OFFSET))(this, a1);
		}

		::System::Void _InitProcessors_b__64_0(::System::Single _)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER__INITPROCESSORS_B__64_0_OFFSET))(this, _);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIGENERAL3DMODELDIALOGPOPWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
