#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_8E90989A26BC6232.h"
#include "unitysdk/MoleMole/UIWindowController.h"
#include "unitysdk/System/ValueTuple_2.h"

class Class_1_1685EC66FBD28897;
class Class_1_4791AD8D44B5F712;
class Class_1_D375C91CCE5D3999;
class Class_2_1A3197598F874EB7_Class_1_813FCA7056778864;
class Class_2_79AE422BA06F6D26_108;
class Class_3_31FA216B8128BBFD_1;
class MonoUIDoubleWeekConfig;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class EventArgs; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_BINDEVENT_OFFSET UNITYSDK_OFFSET(0x9D90750)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_DOREFRESHBINGOFORSINGLEGRID_OFFSET UNITYSDK_OFFSET(0x9D95B10)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET UNITYSDK_OFFSET(0x9D90620)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x9D90610)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_INITVIEW_OFFSET UNITYSDK_OFFSET(0x9D90D30)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x9D90630)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONSELECTGRID_OFFSET UNITYSDK_OFFSET(0x9D945E0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONSELECTREWARDBTN_OFFSET UNITYSDK_OFFSET(0x9D931D0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0x9D91200)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONTAKEBINGOREWARD_OFFSET UNITYSDK_OFFSET(0x9D965B0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONTAKEGRIDREWARDS_OFFSET UNITYSDK_OFFSET(0x9D96F00)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x9D91B30)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x9D906D0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_OPENINFO_OFFSET UNITYSDK_OFFSET(0x9D96870)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_PLAYBINGOREWARDGETEFFECT_OFFSET UNITYSDK_OFFSET(0x9D96620)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_PLAYFINALBINGOSHOW_OFFSET UNITYSDK_OFFSET(0x9D951A0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHBINGOFORGRID_OFFSET UNITYSDK_OFFSET(0x9D96960)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHBINGOREWARDSTATE_OFFSET UNITYSDK_OFFSET(0x9D930C0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHBINGO_OFFSET UNITYSDK_OFFSET(0x9D92150)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHGRIDS_OFFSET UNITYSDK_OFFSET(0x9D929B0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHREWARDITEMLIST_OFFSET UNITYSDK_OFFSET(0x9D95E10)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHUIDATA_OFFSET UNITYSDK_OFFSET(0x9D944A0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x9D91D20)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_SELECTTAB_OFFSET UNITYSDK_OFFSET(0x9D93700)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_SHOWBINGOTIP_OFFSET UNITYSDK_OFFSET(0x9D93BE0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_TRYLOCATECURRENTAVAILABLEQUEST_OFFSET UNITYSDK_OFFSET(0x9D96180)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_TRYTAKEALLBINGOREWARDS_OFFSET UNITYSDK_OFFSET(0x9D933B0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__BINDEVENT_B__9_0_OFFSET UNITYSDK_OFFSET(0x9D97010)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__BINDEVENT_B__9_1_OFFSET UNITYSDK_OFFSET(0x9D97080)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__BINDEVENT_B__9_2_OFFSET UNITYSDK_OFFSET(0x9D970F0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x9D96F80)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__REFRESHBINGOFORGRID_B__26_0_OFFSET UNITYSDK_OFFSET(0x9D97200)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x9D972A0)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0x9D97310)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x9D97320)
#define MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x9D97330)

namespace MoleMole
{
	inline static constexpr unsigned int UIHIADoubleWeekActivityPopWindowController_TypeDefinitionIndex = 46331;

	class UIHIADoubleWeekActivityPopWindowController : public ::MoleMole::UIWindowController
	{
	public:
		// static const ::System::String* DIALOG_CLICK_TAB_ANIM; // 0x0
		// static const ::System::Int32 HIA_INFO_DAILOG_ID = 0x2DCC39; // 0x0
		::Class_2_79AE422BA06F6D26_108* _view; // 0x2F8
		::System::Int32 _currTabIdx; // 0x300
		::System::Int32 _currGridIdx; // 0x304
		::Class_2_1A3197598F874EB7_Class_1_813FCA7056778864* _currActivityQuestGroup; // 0x308
		::System::Collections::Generic::List_1<::Class_1_1685EC66FBD28897*>* _rewardItemDataList; // 0x310
		::Class_1_D375C91CCE5D3999* _activityData; // 0x318
		::Class_1_4791AD8D44B5F712* bingoProgressHandler; // 0x320
		::System::Single _prevProgressRatio; // 0x328
		::System::Collections::Generic::List_1<::Class_3_31FA216B8128BBFD_1*>* _grids; // 0x330
		::MonoUIDoubleWeekConfig* _config; // 0x338
		::System::Boolean _isLastGridCollecting; // 0x340

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::Enum_3_8E90989A26BC6232 get_HotSwitchRootLayerState()
		{
			return ((::Enum_3_8E90989A26BC6232(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void BindEvent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_BINDEVENT_OFFSET))(this);
		}

		::System::Void InitView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_INITVIEW_OFFSET))(this);
		}

		::System::Void RefreshView(::System::Boolean init, ::System::Boolean playProgressAnim)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHVIEW_OFFSET))(this, init, playProgressAnim);
		}

		::System::Void RefreshBingo(::System::Boolean playProgressAnim)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHBINGO_OFFSET))(this, playProgressAnim);
		}

		::System::Void RefreshBingoRewardState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHBINGOREWARDSTATE_OFFSET))(this);
		}

		::System::Void OnSelectRewardBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONSELECTREWARDBTN_OFFSET))(this);
		}

		::System::Void SelectTab(::System::Int32 nextTabIdx)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_SELECTTAB_OFFSET))(this, nextTabIdx);
		}

		::System::Void RefreshUIData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHUIDATA_OFFSET))(this);
		}

		::System::Void RefreshGrids(::System::Boolean init)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHGRIDS_OFFSET))(this, init);
		}

		::System::Void PlayFinalBingoShow(::System::Collections::Generic::List_1<::System::ValueTuple_2<::System::Int32, ::System::Int32>>* convertToBingoList)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::ValueTuple_2<::System::Int32, ::System::Int32>>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_PLAYFINALBINGOSHOW_OFFSET))(this, convertToBingoList);
		}

		::System::Void OnSelectGrid(::System::Int32 idx)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONSELECTGRID_OFFSET))(this, idx);
		}

		::System::Boolean TryLocateCurrentAvailableQuest(::System::Int32 questId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_TRYLOCATECURRENTAVAILABLEQUEST_OFFSET))(this, questId);
		}

		::System::Void RefreshRewardItemList(::System::Int32 onceRewardID, ::System::Boolean isShowGot)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHREWARDITEMLIST_OFFSET))(this, onceRewardID, isShowGot);
		}

		::System::Void OnTakeBingoReward()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONTAKEBINGOREWARD_OFFSET))(this);
		}

		::System::Void TryTakeAllBingoRewards()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_TRYTAKEALLBINGOREWARDS_OFFSET))(this);
		}

		::System::Void PlayBingoRewardGetEffect(::System::Collections::Generic::List_1<::System::Int32>* claimBingoIdxList)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::Int32>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_PLAYBINGOREWARDGETEFFECT_OFFSET))(this, claimBingoIdxList);
		}

		::System::Void OpenInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_OPENINFO_OFFSET))(this);
		}

		::System::Void RefreshBingoForGrid(::System::Int32 row, ::System::Int32 col)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_REFRESHBINGOFORGRID_OFFSET))(this, row, col);
		}

		::System::Void DoRefreshBingoForSingleGrid(::System::Int32 row, ::System::Int32 col, ::System::Int32 bingoIdx, ::System::Single delayTime)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32, ::System::Int32, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_DOREFRESHBINGOFORSINGLEGRID_OFFSET))(this, row, col, bingoIdx, delayTime);
		}

		::System::Void OnTakeGridRewards(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_ONTAKEGRIDREWARDS_OFFSET))(this, args);
		}

		::System::Void ShowBingoTip()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER_SHOWBINGOTIP_OFFSET))(this);
		}

		::System::Void _BindEvent_b__9_0(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__BINDEVENT_B__9_0_OFFSET))(this, args);
		}

		::System::Void _BindEvent_b__9_1(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__BINDEVENT_B__9_1_OFFSET))(this, args);
		}

		::System::Void _BindEvent_b__9_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__BINDEVENT_B__9_2_OFFSET))(this);
		}

		::System::Void _RefreshBingoForGrid_b__26_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER__REFRESHBINGOFORGRID_B__26_0_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIHIADOUBLEWEEKACTIVITYPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}
	};
}
