#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_1_8289F2785D9AA990;

#define MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_MOVENEXT_OFFSET UNITYSDK_OFFSET(0x9C134F0)
#define MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_SINGLE__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x9C13610)
#define MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x9C13670)
#define MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0x9C13620)
#define MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x9C134E0)
#define MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26__CTOR_OFFSET UNITYSDK_OFFSET(0x9C134D0)

namespace MoleMole
{
	inline static constexpr unsigned int UIInLevelCountDownUIChildWindowController___EaseAddTime_d__26_TypeDefinitionIndex = 39681;

	class UIInLevelCountDownUIChildWindowController___EaseAddTime_d__26 : public ::System::Object
	{
	public:
		::Class_1_8289F2785D9AA990* timer; // 0x10
		::System::Single tBonus; // 0x18
		::System::Single __2__current; // 0x1C
		::System::Int32 __1__state; // 0x20
		::System::Boolean _isPositive_5__2; // 0x24
		::System::Single _speed_5__3; // 0x28

		::System::Void _ctor(::System::Int32 __1__state)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26__CTOR_OFFSET))(this, __1__state);
		}

		::System::Void System_IDisposable_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
		}

		::System::Boolean MoveNext()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_MOVENEXT_OFFSET))(this);
		}

		::System::Single System_Collections_Generic_IEnumerator_System_Single__get_Current()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_SINGLE__GET_CURRENT_OFFSET))(this);
		}

		::System::Void System_Collections_IEnumerator_Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
		}

		::System::Object* System_Collections_IEnumerator_get_Current()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELCOUNTDOWNUICHILDWINDOWCONTROLLER___EASEADDTIME_D__26_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
		}
	};
}
