#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIWidgetController.h"
#include "unitysdk/Struct_2_037D21AC29ED1130.h"
#include "unitysdk/Struct_2_D35A83CFEBC4DDA6.h"
#include "unitysdk/UnityEngine/Vector2.h"

class Class_1_00C315291498A552;
class Class_1_84288157D4F72E4C;
class Class_1_8922DBE482CC1BA4;
class Class_1_8BABEB2BC6365EFE;
class Class_1_CF8E829F802476F6;
class Class_1_F42B4A17001C2F64;
class Class_2_14A21C97B2AEB8D2;
class Class_2_79AE422BA06F6D26_68;
class Class_2_9A16BB53176B1EDB;
namespace MoleMole { class MonoGamepadModule; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralBtn03WidgetController; }
namespace MoleMole { class UIInterKnowCoursePanelWidgetController_CoursePanelContext; }
namespace System { class Action; }
namespace System { class EventArgs; }
namespace System { class String; }
namespace System { template <typename T> class Action_1; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace System::Threading { class CancellationTokenSource; }
namespace UnityEngine { class Animation; }
namespace UnityEngine { class Coroutine; }
namespace UnityEngine { class Material; }

#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_CLEARALLNOWSHOWNODES_OFFSET UNITYSDK_OFFSET(0xC1182F0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_CLEARNODEANIMSTATE_OFFSET UNITYSDK_OFFSET(0xC1142C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_CLOSEDETAILINFOPANEL_OFFSET UNITYSDK_OFFSET(0xC116150)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_DOCHAPTERCLICK_OFFSET UNITYSDK_OFFSET(0xC115FD0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_EXTENDSEENODES_OFFSET UNITYSDK_OFFSET(0xC119220)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_FINDCENTERNODE_OFFSET UNITYSDK_OFFSET(0xC114530)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENALLJOURNEYNODETREE_OFFSET UNITYSDK_OFFSET(0xC117CD0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENDROPDOWNPARAMS_OFFSET UNITYSDK_OFFSET(0xC11A970)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENNODEUIWIDGETBYSITE_OFFSET UNITYSDK_OFFSET(0xC118990)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENNODEUIWIDGET_1_OFFSET UNITYSDK_OFFSET(0xC118910)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENNODEUIWIDGET_OFFSET UNITYSDK_OFFSET(0xC1187C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GETSEENODESLEFTRIGHTSITE_OFFSET UNITYSDK_OFFSET(0xC119040)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GET_ISINOVERNIGHTSHOW_OFFSET UNITYSDK_OFFSET(0xC11AC60)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GET_OVERNIGHTREWARDNODESET_OFFSET UNITYSDK_OFFSET(0xC11AC70)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GOTOINTERKNOTMISSION_OFFSET UNITYSDK_OFFSET(0xC1176C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITBGMATERIAL_OFFSET UNITYSDK_OFFSET(0xC1143C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITCHAPTERSCROLLVIEW_OFFSET UNITYSDK_OFFSET(0xC115BF0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITENTERSEAON_OFFSET UNITYSDK_OFFSET(0xC11A270)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITOVERNIGHTDROPDOWN_OFFSET UNITYSDK_OFFSET(0xC11A370)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITOVERNIGHTENTERSEASON_OFFSET UNITYSDK_OFFSET(0xC11A880)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITRESETBUTTON_OFFSET UNITYSDK_OFFSET(0xC119AF0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITSCROLLTONODE_OFFSET UNITYSDK_OFFSET(0xC11A5C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITSETIMAGESCALE_OFFSET UNITYSDK_OFFSET(0xC115280)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INNEROPENDETAILINFOPANEL_OFFSET UNITYSDK_OFFSET(0xC1166C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONANIMALLEND_OFFSET UNITYSDK_OFFSET(0xC113C30)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONCLICKNEWSEASON_OFFSET UNITYSDK_OFFSET(0xC11AB80)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONCONSOLELEFTRIGHTBTN_OFFSET UNITYSDK_OFFSET(0xC115E80)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xC11B860)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONGAMEPADMODULEFOCUS_OFFSET UNITYSDK_OFFSET(0xC11C0F0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONINFOPANELANIMATIONEND_OFFSET UNITYSDK_OFFSET(0xC117C30)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0xC11BF80)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONJOURNEYNODECHANGED_OFFSET UNITYSDK_OFFSET(0xC11C4F0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xC11C350)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONLINEANIMEND_OFFSET UNITYSDK_OFFSET(0xC114240)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONNODEANIMFINISH_OFFSET UNITYSDK_OFFSET(0xC113AB0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSCROLLVIEWDRAGEND_OFFSET UNITYSDK_OFFSET(0xC11C410)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSCROLLVIEWDRAGSTART_OFFSET UNITYSDK_OFFSET(0xC11C480)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSHOWINEND_OFFSET UNITYSDK_OFFSET(0xC115110)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0xC11B790)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xC11B900)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xC11AC80)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xC11AFC0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_OPENDETAILINFOPANEL_OFFSET UNITYSDK_OFFSET(0xC116410)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_PLAYNOWINDEX_OFFSET UNITYSDK_OFFSET(0xC113930)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_PLAYQUICKDOWNANIM_OFFSET UNITYSDK_OFFSET(0xC113160)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_REFRESHALLNOWSHOWNODES_OFFSET UNITYSDK_OFFSET(0xC1185C0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_REFRESHNODEDETAILBUTTON_OFFSET UNITYSDK_OFFSET(0xC116E00)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_REFRESHNODEDETAILMISSION_OFFSET UNITYSDK_OFFSET(0xC1168F0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_RESETTONOWNODE_OFFSET UNITYSDK_OFFSET(0xC11A1A0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLDELTA_OFFSET UNITYSDK_OFFSET(0xC11C560)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLFOCUSCHAPTER_OFFSET UNITYSDK_OFFSET(0xC114B20)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLTOFINALCOMPLETE_OFFSET UNITYSDK_OFFSET(0xC11A710)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLTOTARGETTREENODE_OFFSET UNITYSDK_OFFSET(0xC113D60)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SETDETAILMISSIONEMPTY_OFFSET UNITYSDK_OFFSET(0xC117340)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SETINFOTEXT_OFFSET UNITYSDK_OFFSET(0xC1173F0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SETNODEANIMSTATE_OFFSET UNITYSDK_OFFSET(0xC1133D0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SHOWNEXTBG_OFFSET UNITYSDK_OFFSET(0xC114C90)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_TRIGGERCENTERBGEXCHANGE_OFFSET UNITYSDK_OFFSET(0xC114990)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_TRIGGERCENTERNODEEXCHANGE_OFFSET UNITYSDK_OFFSET(0xC114840)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATEMOVEBG_OFFSET UNITYSDK_OFFSET(0xC115820)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATERESETBUTTONSHOW_OFFSET UNITYSDK_OFFSET(0xC119D50)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATESEENODE_OFFSET UNITYSDK_OFFSET(0xC118B20)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0xC11BE80)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xC11C610)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__ONUIOPEN_B__93_0_OFFSET UNITYSDK_OFFSET(0xC11C680)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__ONUIOPEN_B__93_1_OFFSET UNITYSDK_OFFSET(0xC11C690)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__PLAYQUICKDOWNANIM_B__7_0_OFFSET UNITYSDK_OFFSET(0xC11C670)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xC11C6A0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONGAMEPADMODULEFOCUS_OFFSET UNITYSDK_OFFSET(0xC11C710)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0xC11C780)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xC11C7B0)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0xC11C810)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xC11C880)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xC11C900)
#define MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xC11C960)

namespace MoleMole
{
	inline static constexpr unsigned int UIInterKnowCoursePanelWidgetController_TypeDefinitionIndex = 69419;

	class UIInterKnowCoursePanelWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		// static const ::System::Int32 maxIterationCount = 0x12C; // 0x0
		::System::Int32 animStartIndex; // 0x2A0
		::System::Int32 animEndIndex; // 0x2A4
		::Class_2_9A16BB53176B1EDB* nowAnimNode; // 0x2A8
		::System::Action_1<::System::Int32>* nodeFinishCallback; // 0x2B0
		::System::Action* finishCallback; // 0x2B8
		::System::Boolean isOvernightAnimating; // 0x2C0
		::Class_2_9A16BB53176B1EDB* centerNode; // 0x2C8
		::Class_1_CF8E829F802476F6* bgChapter; // 0x2D0
		::UnityEngine::Material* rightToLeft; // 0x2D8
		::UnityEngine::Material* leftToRight; // 0x2E0
		::Il2CppArray<::UnityEngine::Vector2>* imageCorners; // 0x2E8
		::Il2CppArray<::UnityEngine::Vector2>* viewScreenCorners; // 0x2F0
		::System::Boolean isExchangingBG; // 0x2F8
		::System::Single dragMinDis; // 0x2FC
		::System::Single dragMaxDis; // 0x300
		::Class_2_9A16BB53176B1EDB* nowDetailNode; // 0x308
		::UnityEngine::Coroutine* nowArrowCoroutine; // 0x310
		::System::Int32 extraCount; // 0x318
		::UnityEngine::Vector2 contextScale; // 0x31C
		::System::Collections::Generic::List_1<::Class_2_9A16BB53176B1EDB*>* seeNodes; // 0x328
		::Class_2_9A16BB53176B1EDB* finalCompleteNode; // 0x330
		::System::Collections::Generic::List_1<::Struct_2_D35A83CFEBC4DDA6>* journeyLineStructList; // 0x338
		::System::Collections::Generic::List_1<::Struct_2_D35A83CFEBC4DDA6>* journeyNodeStructList; // 0x340
		::MoleMole::UIGeneralBtn03WidgetController* leftBtnWidget; // 0x348
		::MoleMole::UIGeneralBtn03WidgetController* rightBtnWidget; // 0x350
		::Class_1_F42B4A17001C2F64* nowSeaon; // 0x358
		::Class_1_8BABEB2BC6365EFE* seasonDropDownViewModel; // 0x360
		::System::Int32 nowSeaonIndex; // 0x368
		::UnityEngine::Animation* pageRootAnim; // 0x370
		::System::Threading::CancellationTokenSource* cts; // 0x378
		::Class_2_79AE422BA06F6D26_68* _view; // 0x380
		::Class_2_14A21C97B2AEB8D2* journeyModel; // 0x388
		::MoleMole::UIInterKnowCoursePanelWidgetController_CoursePanelContext* nowContext; // 0x390
		::Class_1_00C315291498A552* nodeFactory; // 0x398
		::System::Collections::Generic::List_1<::Class_1_84288157D4F72E4C*>* chapterRowDataList; // 0x3A0
		::System::Collections::Generic::Dictionary_2<::System::Int32, ::Class_2_9A16BB53176B1EDB*>* nowShowNodes; // 0x3A8
		::System::Collections::Generic::Dictionary_2<::System::Int32, ::Class_2_9A16BB53176B1EDB*>* depthNodes; // 0x3B0
		::Class_1_8922DBE482CC1BA4* navHandler; // 0x3B8
		::System::Boolean _isInOvernightShow; // 0x3C0
		::System::Collections::Generic::HashSet_1<::System::Int32>* _overnightRewardNodeSet; // 0x3C8
		::System::Boolean centerUpdateBG; // 0x3D0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void PlayQuickDownAnim(::System::Int32 startIndex, ::System::Int32 endIndex, ::System::Action_1<::System::Int32>* nodeCallback, ::System::Action* allCallback)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32, ::System::Action_1<::System::Int32>*, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_PLAYQUICKDOWNANIM_OFFSET))(this, startIndex, endIndex, nodeCallback, allCallback);
		}

		::System::Void PlayNowIndex()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_PLAYNOWINDEX_OFFSET))(this);
		}

		::System::Void OnNodeAnimFinish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONNODEANIMFINISH_OFFSET))(this);
		}

		::System::Void OnLineAnimEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONLINEANIMEND_OFFSET))(this);
		}

		::System::Void OnAnimAllEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONANIMALLEND_OFFSET))(this);
		}

		::System::Void SetNodeAnimState(::System::Int32 startIndex, ::System::Int32 endIndex, ::System::Boolean isSetToFinalState, ::System::Boolean withRefreshState)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SETNODEANIMSTATE_OFFSET))(this, startIndex, endIndex, isSetToFinalState, withRefreshState);
		}

		::System::Void ClearNodeAnimState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_CLEARNODEANIMSTATE_OFFSET))(this);
		}

		::System::Void InitBGMaterial()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITBGMATERIAL_OFFSET))(this);
		}

		::System::Void FindCenterNode(::System::Boolean updateBG)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_FINDCENTERNODE_OFFSET))(this, updateBG);
		}

		::System::Void TriggerCenterNodeExchange(::Class_2_9A16BB53176B1EDB* nowCheckNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_TRIGGERCENTERNODEEXCHANGE_OFFSET))(this, nowCheckNode);
		}

		::System::Void TriggerCenterBGExchange(::Class_2_9A16BB53176B1EDB* treeNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_TRIGGERCENTERBGEXCHANGE_OFFSET))(this, treeNode);
		}

		::System::Void ShowNextBG(::Class_1_CF8E829F802476F6* showChapter)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_CF8E829F802476F6*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SHOWNEXTBG_OFFSET))(this, showChapter);
		}

		::System::Void OnShowInEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSHOWINEND_OFFSET))(this);
		}

		::System::Void InitSetImageScale()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITSETIMAGESCALE_OFFSET))(this);
		}

		::System::Void UpdateMoveBg()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATEMOVEBG_OFFSET))(this);
		}

		::System::Void InitChapterScrollView(::Class_2_9A16BB53176B1EDB* treeNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITCHAPTERSCROLLVIEW_OFFSET))(this, treeNode);
		}

		::System::Void OnConsoleLeftRightBtn(::System::Int32 offset)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONCONSOLELEFTRIGHTBTN_OFFSET))(this, offset);
		}

		::System::Void DoChapterClick(::Class_1_CF8E829F802476F6* treeChapter)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_CF8E829F802476F6*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_DOCHAPTERCLICK_OFFSET))(this, treeChapter);
		}

		::System::Void ScrollFocusChapter(::Class_1_CF8E829F802476F6* treeChapter, ::System::Boolean hasAnim)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_CF8E829F802476F6*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLFOCUSCHAPTER_OFFSET))(this, treeChapter, hasAnim);
		}

		::System::Void OpenDetailInfoPanel(::Class_2_9A16BB53176B1EDB* showNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_OPENDETAILINFOPANEL_OFFSET))(this, showNode);
		}

		::System::Void InnerOpenDetailInfoPanel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INNEROPENDETAILINFOPANEL_OFFSET))(this);
		}

		::System::Void RefreshNodeDetailMission(::Class_2_9A16BB53176B1EDB* showNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_REFRESHNODEDETAILMISSION_OFFSET))(this, showNode);
		}

		::System::Void SetDetailMissionEmpty(::System::Boolean isEmpty)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SETDETAILMISSIONEMPTY_OFFSET))(this, isEmpty);
		}

		::System::Void RefreshNodeDetailButton(::Class_2_9A16BB53176B1EDB* showNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_REFRESHNODEDETAILBUTTON_OFFSET))(this, showNode);
		}

		::System::Void SetInfoText(::System::String* textKey)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SETINFOTEXT_OFFSET))(this, textKey);
		}

		::System::Void GoToInterKnotMission()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GOTOINTERKNOTMISSION_OFFSET))(this);
		}

		::System::Void CloseDetailInfoPanel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_CLOSEDETAILINFOPANEL_OFFSET))(this);
		}

		::System::Void OnInfoPanelAnimationEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONINFOPANELANIMATIONEND_OFFSET))(this);
		}

		::System::Void GenAllJourneyNodeTree()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENALLJOURNEYNODETREE_OFFSET))(this);
		}

		::System::Void ClearAllNowShowNodes()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_CLEARALLNOWSHOWNODES_OFFSET))(this);
		}

		::System::Void RefreshAllNowShowNodes()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_REFRESHALLNOWSHOWNODES_OFFSET))(this);
		}

		::System::Boolean GenNodeUIWidget(::System::Int32 nodeIndex, ::Class_2_9A16BB53176B1EDB*& treeNode)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32, ::Class_2_9A16BB53176B1EDB*&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENNODEUIWIDGET_OFFSET))(this, nodeIndex, treeNode);
		}

		::System::Void GenNodeUIWidget_1(::Class_2_9A16BB53176B1EDB* treeNode)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_9A16BB53176B1EDB*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENNODEUIWIDGET_1_OFFSET))(this, treeNode);
		}

		::System::Void GenNodeUIWidgetBySite(::System::Int32 nodeSite, ::Class_2_9A16BB53176B1EDB*& journeyNode)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::Class_2_9A16BB53176B1EDB*&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENNODEUIWIDGETBYSITE_OFFSET))(this, nodeSite, journeyNode);
		}

		::System::Void UpdateSeeNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATESEENODE_OFFSET))(this);
		}

		::System::Void ExtendSeeNodes(::System::Single seeMin, ::System::Single seeMax)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_EXTENDSEENODES_OFFSET))(this, seeMin, seeMax);
		}

		::System::Void GetSeeNodesLeftRightSite(::System::Single& leftSite, ::System::Single& rightSite)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single&, ::System::Single&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GETSEENODESLEFTRIGHTSITE_OFFSET))(this, leftSite, rightSite);
		}

		::System::Void InitResetButton()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITRESETBUTTON_OFFSET))(this);
		}

		::System::Void UpdateResetButtonShow()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATERESETBUTTONSHOW_OFFSET))(this);
		}

		::System::Void ResetToNowNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_RESETTONOWNODE_OFFSET))(this);
		}

		::System::Void InitEnterSeaon()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITENTERSEAON_OFFSET))(this);
		}

		::System::Void InitOvernightEnterSeason(::System::Int32 overnighStartIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITOVERNIGHTENTERSEASON_OFFSET))(this, overnighStartIndex);
		}

		::System::Void InitOvernightDropDown()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITOVERNIGHTDROPDOWN_OFFSET))(this);
		}

		::Il2CppArray<::Struct_2_037D21AC29ED1130>* GenDropDownParams()
		{
			return ((::Il2CppArray<::Struct_2_037D21AC29ED1130>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GENDROPDOWNPARAMS_OFFSET))(this);
		}

		::System::Void OnClickNewSeason(::System::Int32 index)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONCLICKNEWSEASON_OFFSET))(this, index);
		}

		::System::Boolean get_IsInOvernightShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GET_ISINOVERNIGHTSHOW_OFFSET))(this);
		}

		::System::Collections::Generic::HashSet_1<::System::Int32>* get_OvernightRewardNodeSet()
		{
			return ((::System::Collections::Generic::HashSet_1<::System::Int32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_GET_OVERNIGHTREWARDNODESET_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void OnGamepadModuleFocus(::MoleMole::MonoGamepadModule* gamepadModule)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONGAMEPADMODULEFOCUS_OFFSET))(this, gamepadModule);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void ScrollToFinalComplete()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLTOFINALCOMPLETE_OFFSET))(this);
		}

		::System::Void InitScrollToNode(::System::Int32 nodeIndex)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_INITSCROLLTONODE_OFFSET))(this, nodeIndex);
		}

		::System::Void OnScrollViewDragEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSCROLLVIEWDRAGEND_OFFSET))(this);
		}

		::System::Void OnScrollViewDragStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONSCROLLVIEWDRAGSTART_OFFSET))(this);
		}

		::System::Void OnJourneyNodeChanged(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_ONJOURNEYNODECHANGED_OFFSET))(this, args);
		}

		::System::Void ScrollToTargetTreeNode(::System::Int32 nodeIndex, ::System::Single viewRatio, ::System::Single rectRatio, ::System::Boolean hasAnim)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Single, ::System::Single, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLTOTARGETTREENODE_OFFSET))(this, nodeIndex, viewRatio, rectRatio, hasAnim);
		}

		::System::Void ScrollDelta(::System::Single moveDelta)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER_SCROLLDELTA_OFFSET))(this, moveDelta);
		}

		::System::Void _PlayQuickDownAnim_b__7_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__PLAYQUICKDOWNANIM_B__7_0_OFFSET))(this);
		}

		::System::Void _OnUIOpen_b__93_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__ONUIOPEN_B__93_0_OFFSET))(this);
		}

		::System::Void _OnUIOpen_b__93_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER__ONUIOPEN_B__93_1_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnGamepadModuleFocus(::MoleMole::MonoGamepadModule* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::MonoGamepadModule*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONGAMEPADMODULEFOCUS_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINTERKNOWCOURSEPANELWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
