#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIInLevelSpecialDamageTextBaseController.h"

class Class_2_69CBB7FF0BE6A673_35;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }

#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_INITVIEWCONTROL_OFFSET UNITYSDK_OFFSET(0xC0FF4B0)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xC0FF380)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xC0FF420)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xC0FF210)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xC0FF2D0)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xC0FF530)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_INITVIEWCONTROL_OFFSET UNITYSDK_OFFSET(0xC0FF5D0)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xC0FF630)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xC0FF6A0)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xC0FF6B0)
#define MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xC0FF730)

namespace MoleMole
{
	inline static constexpr unsigned int UIInLevelSpecialDamageTextAssaultChildWindowController_TypeDefinitionIndex = 75297;

	class UIInLevelSpecialDamageTextAssaultChildWindowController : public ::MoleMole::UIInLevelSpecialDamageTextBaseController
	{
	public:
		::Class_2_69CBB7FF0BE6A673_35* _view; // 0x3A0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void InitViewControl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER_INITVIEWCONTROL_OFFSET))(this);
		}

		::System::Void __base_InitViewControl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_INITVIEWCONTROL_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELSPECIALDAMAGETEXTASSAULTCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
