#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIInLevelMonsterHudChildWindowControllerBase.h"

class Class_2_319F4867396B6D08;
class Class_3_F35B080B137ECC46;
class Class_4_E2880458FFC7DD8C;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class EventArgs; }
namespace System { class String; }
namespace UnityEngine { class Animation; }
namespace UnityEngine { class CanvasGroup; }
namespace UnityEngine { class Material; }
namespace UnityEngine { class RectTransform; }

#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_DOONENTERBATTLESTATECHANGE_OFFSET UNITYSDK_OFFSET(0xA1CCBE0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_DOONRECYCLE_OFFSET UNITYSDK_OFFSET(0xA1CD1C0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_FADEINANIMCLIP_OFFSET UNITYSDK_OFFSET(0xA1CBA60)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_FADEOUTANIMCLIP_OFFSET UNITYSDK_OFFSET(0xA1CBAA0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_ROOTANIM_OFFSET UNITYSDK_OFFSET(0xA1CBA30)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_ROOTCANVASGROUP_OFFSET UNITYSDK_OFFSET(0xA1CBA10)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_SHOULDSHOW_OFFSET UNITYSDK_OFFSET(0xA1CB1F0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_VIEWROOT_OFFSET UNITYSDK_OFFSET(0xA1CB9F0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xA1CBC00)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONENTERBATTLESTATECHANGE_OFFSET UNITYSDK_OFFSET(0xA1CD8B0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONHIDEVIEWIGNOREANIMATION_OFFSET UNITYSDK_OFFSET(0xA1CCFE0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONHIDEVIEWWITHANIMATION_OFFSET UNITYSDK_OFFSET(0xA1CD100)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONSETENTITY_OFFSET UNITYSDK_OFFSET(0xA1CBD30)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONSHOWVIEW_OFFSET UNITYSDK_OFFSET(0xA1CCEF0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xA1CBCA0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xA1CBAE0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xA1CBB50)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUPDATEVIEW_OFFSET UNITYSDK_OFFSET(0xA1CD3F0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_SETGAMEOBJECTNAME_OFFSET UNITYSDK_OFFSET(0xA1CCCD0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_SET_SHOULDSHOW_OFFSET UNITYSDK_OFFSET(0xA1CB200)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_SHOWINFORMATION_OFFSET UNITYSDK_OFFSET(0xA1CC310)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_UPDATEPOSWHENINVISIBLE_OFFSET UNITYSDK_OFFSET(0xA1CD390)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_UPDATEVIEWWHENCONTAINSSHOWFLAG_OFFSET UNITYSDK_OFFSET(0xA1CD160)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xA1CDA20)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xA1CDA30)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xA1CDAA0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xA1CDAB0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xA1CDAC0)
#define MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUPDATEVIEW_OFFSET UNITYSDK_OFFSET(0xA1CDB30)

namespace MoleMole
{
	inline static constexpr unsigned int UIInLevelMonsterHudLevelChildWindowController_TypeDefinitionIndex = 64282;

	class UIInLevelMonsterHudLevelChildWindowController : public ::MoleMole::UIInLevelMonsterHudChildWindowControllerBase
	{
	public:
		::Class_2_319F4867396B6D08* _view; // 0x348
		::System::Single _enterBattleShowTimer; // 0x350
		::System::Single _idleHideDelayTimer; // 0x354
		::Class_4_E2880458FFC7DD8C* _enterBattleComponent; // 0x358
		::Class_3_F35B080B137ECC46* _modelComp; // 0x360
		::UnityEngine::Material* _whiteMat; // 0x368
		::UnityEngine::Material* _redMat; // 0x370
		::System::Boolean _shouldShow; // 0x378

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Boolean get_shouldShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_SHOULDSHOW_OFFSET))(this);
		}

		::System::Void set_shouldShow(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_SET_SHOULDSHOW_OFFSET))(this, value);
		}

		::UnityEngine::RectTransform* get_ViewRoot()
		{
			return ((::UnityEngine::RectTransform*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_VIEWROOT_OFFSET))(this);
		}

		::UnityEngine::CanvasGroup* get_RootCanvasGroup()
		{
			return ((::UnityEngine::CanvasGroup*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_ROOTCANVASGROUP_OFFSET))(this);
		}

		::UnityEngine::Animation* get_RootAnim()
		{
			return ((::UnityEngine::Animation*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_ROOTANIM_OFFSET))(this);
		}

		::System::String* get_FadeInAnimClip()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_FADEINANIMCLIP_OFFSET))(this);
		}

		::System::String* get_FadeOutAnimClip()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_GET_FADEOUTANIMCLIP_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnSetEntity()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONSETENTITY_OFFSET))(this);
		}

		::System::Void SetGameObjectName(::System::UInt32 entityID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_SETGAMEOBJECTNAME_OFFSET))(this, entityID);
		}

		::System::Void OnShowView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONSHOWVIEW_OFFSET))(this);
		}

		::System::Void OnHideViewIgnoreAnimation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONHIDEVIEWIGNOREANIMATION_OFFSET))(this);
		}

		::System::Void OnHideViewWithAnimation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONHIDEVIEWWITHANIMATION_OFFSET))(this);
		}

		::System::Void UpdateViewWhenContainsShowFlag()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_UPDATEVIEWWHENCONTAINSSHOWFLAG_OFFSET))(this);
		}

		::System::Void DoOnRecycle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_DOONRECYCLE_OFFSET))(this);
		}

		::System::Void UpdatePosWhenInvisible()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_UPDATEPOSWHENINVISIBLE_OFFSET))(this);
		}

		::System::Void OnUpdateView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONUPDATEVIEW_OFFSET))(this);
		}

		::System::Void ShowInformation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_SHOWINFORMATION_OFFSET))(this);
		}

		::System::Void OnEnterBattleStateChange(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_ONENTERBATTLESTATECHANGE_OFFSET))(this, obj);
		}

		::System::Void DoOnEnterBattleStateChange()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER_DOONENTERBATTLESTATECHANGE_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}

		::System::Void __base_OnUpdateView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIINLEVELMONSTERHUDLEVELCHILDWINDOWCONTROLLER___BASE_ONUPDATEVIEW_OFFSET))(this);
		}
	};
}
