#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Enum_3_8E90989A26BC6232.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIWindowController.h"

class Class_2_2EBEB2C1900114A8;
class Class_2_B56C2ACF632023E4;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIMonsterFantasyTransitionWidgetController; }
namespace System { class Action; }
namespace System { class String; }

#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ACTIVELOADINGUI_OFFSET UNITYSDK_OFFSET(0x6CA8EF0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_BINDINTERFACE_OFFSET UNITYSDK_OFFSET(0x6CA8D10)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_CHECKCLOSELOADING_OFFSET UNITYSDK_OFFSET(0x6CA9AC0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET UNITYSDK_OFFSET(0x6CA8B60)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_GET_PERMANENT_OFFSET UNITYSDK_OFFSET(0x6CA8B50)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0x6CA8B40)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x6CA98B0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x6CA9D10)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x6CA9950)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x6CA99E0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_PLAYFADEIN_OFFSET UNITYSDK_OFFSET(0x6CA9310)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_PLAYFADEOUT_OFFSET UNITYSDK_OFFSET(0x6CA9710)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_RESET_OFFSET UNITYSDK_OFFSET(0x6CA9F60)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_SETNEXTBTNACTIVE_OFFSET UNITYSDK_OFFSET(0x6CA8D80)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_SETTEXTACTIVE_OFFSET UNITYSDK_OFFSET(0x6CA8E60)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_SETUIWINDOWSETTING_OFFSET UNITYSDK_OFFSET(0x6CA8B70)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_UNACTIVELOADINGUI_OFFSET UNITYSDK_OFFSET(0x6CA9470)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x6CAA1C0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x6CAA1D0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0x6CAA240)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x6CAA270)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x6CAA280)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_PLAYFADEIN_OFFSET UNITYSDK_OFFSET(0x6CAA290)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_PLAYFADEOUT_OFFSET UNITYSDK_OFFSET(0x6CAA2A0)
#define MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_SETUIWINDOWSETTING_OFFSET UNITYSDK_OFFSET(0x6CAA2B0)

namespace MoleMole
{
	inline static constexpr unsigned int UILoadingTransitionPopWindowController_TypeDefinitionIndex = 66131;

	class UILoadingTransitionPopWindowController : public ::MoleMole::UIWindowController
	{
	public:
		::Class_2_B56C2ACF632023E4* _view; // 0x2F8
		::Class_2_2EBEB2C1900114A8* _owner; // 0x300
		::MoleMole::UIMonsterFantasyTransitionWidgetController* _monsterFantasyWidget; // 0x308

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::System::Boolean get_Permanent()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_GET_PERMANENT_OFFSET))(this);
		}

		::Enum_3_8E90989A26BC6232 get_HotSwitchRootLayerState()
		{
			return ((::Enum_3_8E90989A26BC6232(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_GET_HOTSWITCHROOTLAYERSTATE_OFFSET))(this);
		}

		::System::Void SetUIWindowSetting()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_SETUIWINDOWSETTING_OFFSET))(this);
		}

		::System::Void BindInterface(::Class_2_2EBEB2C1900114A8* owner)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_2EBEB2C1900114A8*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_BINDINTERFACE_OFFSET))(this, owner);
		}

		::System::Void SetNextBtnActive(::System::Boolean active)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_SETNEXTBTNACTIVE_OFFSET))(this, active);
		}

		::System::Void SetTextActive(::System::Boolean active)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_SETTEXTACTIVE_OFFSET))(this, active);
		}

		::System::Void ActiveLoadingUI(::System::String* text, ::System::Action* callback)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ACTIVELOADINGUI_OFFSET))(this, text, callback);
		}

		::System::Void UnActiveLoadingUI(::System::Action* endcallback)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_UNACTIVELOADINGUI_OFFSET))(this, endcallback);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void CheckCloseLoading()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_CHECKCLOSELOADING_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void PlayFadeIn(::System::Action* callback)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_PLAYFADEIN_OFFSET))(this, callback);
		}

		::System::Void PlayFadeOut(::System::Action* callback, ::System::Single animSpeed)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_PLAYFADEOUT_OFFSET))(this, callback, animSpeed);
		}

		::System::Void Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER_RESET_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_PlayFadeIn(::System::Action* P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_PLAYFADEIN_OFFSET))(this, P0);
		}

		::System::Void __base_PlayFadeOut(::System::Action* P0, ::System::Single P1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_PLAYFADEOUT_OFFSET))(this, P0, P1);
		}

		::System::Void __base_SetUIWindowSetting()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UILOADINGTRANSITIONPOPWINDOWCONTROLLER___BASE_SETUIWINDOWSETTING_OFFSET))(this);
		}
	};
}
