#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_3EDF246633A325B0.h"
#include "unitysdk/Foundation/AssetPath.h"
#include "unitysdk/MoleMole/InputActionEvent.h"
#include "unitysdk/MoleMole/UIMainCityCameraControlChildWindowController_CameraSkillTipsState.h"
#include "unitysdk/MoleMole/UIMainCityCameraControlChildWindowController_EUIState.h"
#include "unitysdk/MoleMole/UIWindowController.h"
#include "unitysdk/Struct_2_C8629618711DF8B3.h"
#include "unitysdk/Struct_2_FB00E96128CAB4FE.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_211;
class Class_1_43BD383C98B4C0C5_43;
class Class_1_81BCC5A7D87EA043;
class Class_1_FE835C8461DC4CA2;
class Class_2_40B7FA2256AD419F;
class Class_2_5A5C316BDA7D0E0C_1;
class Class_2_79F6D62CE30E3F8E_178;
namespace MoleMole { class PhotoFrameCustomWidgetController; }
namespace MoleMole { class PhotoSettingContext; }
namespace MoleMole { class UIActivityQuestTipsWidgetController; }
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIGeneralNewsBubbleWidgetController; }
namespace MoleMole { class UIGeneralTipsCameraRowWidgetController; }
namespace MoleMole { class UIGeneralVirtualPlayBtnChildWindowController; }
namespace MoleMole { class UIMainCityCameraControlChildWindowController_TargetArrowUIItem; }
namespace MoleMole { class UIMainCityCameraControlContext; }
namespace MoleMole { class UIMainCityCameraControlTipsChildWindowController; }
namespace MoleMole { class UIMainCityCameraImgTrackWidgetController; }
namespace MoleMole { class UIPhotoGamePadDpadChildWindowController; }
namespace MoleMole { class UIPhotoModePlayerMoveChildWindowController; }
namespace MoleMole { class UIPhotoSettingChildWindowController; }
namespace MoleMole { class UIPhotoStickerControlPopWindowController; }
namespace MoleMole { class UIStickerShowWidgetController; }
namespace System { class Action; }
namespace System { class EventArgs; }
namespace System { class String; }
namespace System { template <typename T> class Func_1; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class IList_1; }
namespace UnityEngine { class Coroutine; }
namespace UnityEngine { class RectTransform; }
namespace UnityEngine { class RenderTexture; }
namespace UnityEngine { class Transform; }
namespace UnityEngine::EventSystems { class PointerEventData; }
namespace UnityEngine::UI::Extension { class UIImgEventTrigger_DragCallbackOld; }
namespace UnityEngine::UI::Extension { class UIImgEventTrigger_TwoPointDragCallback; }
namespace UnityEngine::UI::Extension { class UISlider; }
template <typename T> class Class_1_634159F7561ADAA0;

#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ACTIVEVIRTUALCURSOR_OFFSET UNITYSDK_OFFSET(0xCF8E7B0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ADDSLIDERWITHOUTNOTIFY_OFFSET UNITYSDK_OFFSET(0xCF91680)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_BEGINDRAGCALLBACK_OFFSET UNITYSDK_OFFSET(0xCF946B0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CAPTUREIMMEDIATELY_OFFSET UNITYSDK_OFFSET(0xCF96150)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CHANGEUISTATE_OFFSET UNITYSDK_OFFSET(0xCF952E0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CLEAROUTDATEDTARGETARROWUI_OFFSET UNITYSDK_OFFSET(0xCF98D70)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CLEARSTICKERSHOWMODULE_OFFSET UNITYSDK_OFFSET(0xCF91E60)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_DEACTIVEVIRTUALCURSOR_OFFSET UNITYSDK_OFFSET(0xCF8DFD0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ENDDRAGCALLBACK_OFFSET UNITYSDK_OFFSET(0xCF94630)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_FINDSTICKERWIDGETCONTROLLER_OFFSET UNITYSDK_OFFSET(0xCF94FA0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_FULLSCREENBTNBOTTOMCALLBACK_OFFSET UNITYSDK_OFFSET(0xCF95860)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GETACTIVESTICKERWIDGETCTRLLIST_OFFSET UNITYSDK_OFFSET(0xCF959D0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GETCUSTOMBINDER_OFFSET UNITYSDK_OFFSET(0xCF90760)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GETSTICKERROOT_OFFSET UNITYSDK_OFFSET(0xCF95A40)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_CAPTURE_OFFSET UNITYSDK_OFFSET(0xCF95AC0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_CONTROLUIFADING_OFFSET UNITYSDK_OFFSET(0xCF8F060)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_DETECTRECT_OFFSET UNITYSDK_OFFSET(0xCF964F0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_ISCONTROLHIDE_OFFSET UNITYSDK_OFFSET(0xCF8F040)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_ISENABLESWITCHBTN_OFFSET UNITYSDK_OFFSET(0xCF96630)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_ISSUPPORTFRONTCAMERAMODE_OFFSET UNITYSDK_OFFSET(0xCF96570)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_LASTUIDATA_OFFSET UNITYSDK_OFFSET(0xCF966B0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_SNAPCAPTURING_OFFSET UNITYSDK_OFFSET(0xCF8F050)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_SNAPFLASHING_OFFSET UNITYSDK_OFFSET(0xCF8F070)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_SWITCHFLASHING_OFFSET UNITYSDK_OFFSET(0xCF8F080)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET UNITYSDK_OFFSET(0xCF964E0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_HIDEBOTTOMTIPS_OFFSET UNITYSDK_OFFSET(0xCF90A40)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_HIDESTICKERCONTROLPAGE_OFFSET UNITYSDK_OFFSET(0xCF95190)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INITBOTTOMSLIDER_OFFSET UNITYSDK_OFFSET(0xCF91440)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INITCONTEXT_OFFSET UNITYSDK_OFFSET(0xCF975F0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INITSTICKERSHOWMODULE_OFFSET UNITYSDK_OFFSET(0xCF91A80)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INPUTVIRTUALCURSOR_OFFSET UNITYSDK_OFFSET(0xCF8E530)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_LATEUPDATE_OFFSET UNITYSDK_OFFSET(0xCF99310)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_LOADCONFIGSETFRAMEINNER_OFFSET UNITYSDK_OFFSET(0xCF8F790)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_LOADFRAMEASSETS_OFFSET UNITYSDK_OFFSET(0xCF90130)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONAPPLICATIONFOCUS_OFFSET UNITYSDK_OFFSET(0xCF94BD0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCAMERACONTROLTIPSCLEARALL_OFFSET UNITYSDK_OFFSET(0xCF91220)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCAMERACONTROLTIPSMODIFY_OFFSET UNITYSDK_OFFSET(0xCF91090)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCAMERASKILLBTNCHANGE_OFFSET UNITYSDK_OFFSET(0xCF90EE0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCLICKSETTINGBTN_OFFSET UNITYSDK_OFFSET(0xCF96390)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCLICKSETTINGHIDEBTN_OFFSET UNITYSDK_OFFSET(0xCF96470)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCLOSETARGETARROW_OFFSET UNITYSDK_OFFSET(0xCF99C70)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xCF98750)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONEVENTCAPTUREFINISH_OFFSET UNITYSDK_OFFSET(0xCF95BA0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONFAIRYFINISH_OFFSET UNITYSDK_OFFSET(0xCF9A6F0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONFLASHFINISH_OFFSET UNITYSDK_OFFSET(0xCF96320)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONHIDESTICKER_OFFSET UNITYSDK_OFFSET(0xCF94C40)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONHIDE_OFFSET UNITYSDK_OFFSET(0xCF984F0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0xCF98A90)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONINPUTACTIVEHANDLE_OFFSET UNITYSDK_OFFSET(0xCF8EE30)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xCF8CED0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOINNERFRAMECHANGE_OFFSET UNITYSDK_OFFSET(0xCF904A0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODECLOSESETTINGHANDLE_OFFSET UNITYSDK_OFFSET(0xCF96400)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODEEXITEDITINGSTICKERHANDLE_OFFSET UNITYSDK_OFFSET(0xCF957E0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODESTARTEDITINGSTICKERHANDLE_OFFSET UNITYSDK_OFFSET(0xCF95270)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODEUIREFRESH_OFFSET UNITYSDK_OFFSET(0xCF9A790)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPREINPUTACTION_OFFSET UNITYSDK_OFFSET(0xCF8E420)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONSHOWFAIRY_OFFSET UNITYSDK_OFFSET(0xCF9A650)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONSHOWSTICKER_OFFSET UNITYSDK_OFFSET(0xCF91ED0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONSHOW_OFFSET UNITYSDK_OFFSET(0xCF970D0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0xCF987F0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xCF989A0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xCF966D0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xCF97020)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PHOTOSETTINGHIDE_OFFSET UNITYSDK_OFFSET(0xCF8EF00)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PHOTOUIPLAYFADEIN_OFFSET UNITYSDK_OFFSET(0xCF8E970)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PHOTOUIPLAYFADEOUT_OFFSET UNITYSDK_OFFSET(0xCF8E860)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PLAYFLASHFADEIN_OFFSET UNITYSDK_OFFSET(0xCF8F090)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PLAYFLASHFADEOUT_OFFSET UNITYSDK_OFFSET(0xCF8F280)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_POINTUPCALLBACK_OFFSET UNITYSDK_OFFSET(0xCF94170)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_REFRESHSKILLBTN_OFFSET UNITYSDK_OFFSET(0xCF90F50)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_REFRESHSKILLTIPS_OFFSET UNITYSDK_OFFSET(0xCF91100)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_REFRESHSTICKERSHOWWIDGETS_OFFSET UNITYSDK_OFFSET(0xCF92230)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_RELEASECAPTURE_OFFSET UNITYSDK_OFFSET(0xCF962A0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_CONSOLETIPS_DPAD_OFFSET UNITYSDK_OFFSET(0xCF9A530)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_CONSOLETIPS_LEFTSTICK_OFFSET UNITYSDK_OFFSET(0xCF9A410)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_CONSOLETIPS_RIGHTSTICK_OFFSET UNITYSDK_OFFSET(0xCF9A4A0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_PCTIPS_WASD_OFFSET UNITYSDK_OFFSET(0xCF9A5C0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETCAMERAIMGACTIVE_OFFSET UNITYSDK_OFFSET(0xCF9A060)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETDRAGCALLBACKOLD_OFFSET UNITYSDK_OFFSET(0xCF98BD0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETDRAGTWOPOINTCALLBACK_OFFSET UNITYSDK_OFFSET(0xCF98CB0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETFRONTCAMERATIPSACTIVE_OFFSET UNITYSDK_OFFSET(0xCF9A190)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETINPUTCONTROLROOTACTIVE_OFFSET UNITYSDK_OFFSET(0xCF99FD0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETMOVEBTNROOTACTIVE_OFFSET UNITYSDK_OFFSET(0xCF9A100)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETSLIDERWITHOUTNOTIFY_OFFSET UNITYSDK_OFFSET(0xCF918A0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETSNAPBTNINTERACTABLE_OFFSET UNITYSDK_OFFSET(0xCF98B40)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETSNAPTIPS_OFFSET UNITYSDK_OFFSET(0xCF99EE0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETTIPSTATE_OFFSET UNITYSDK_OFFSET(0xCF91290)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SET_LASTUIDATA_OFFSET UNITYSDK_OFFSET(0xCF966C0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWBOTTOMSLIDERS_OFFSET UNITYSDK_OFFSET(0xCF99E00)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWBOTTOMTIPS_OFFSET UNITYSDK_OFFSET(0xCF90820)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWFULLSCREENBTN_OFFSET UNITYSDK_OFFSET(0xCF8E710)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWINNERFRAME_OFFSET UNITYSDK_OFFSET(0xCF8F700)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWLOCKADDAIMTIPS_OFFSET UNITYSDK_OFFSET(0xCF90D70)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWLOCKAIMTIPS_OFFSET UNITYSDK_OFFSET(0xCF90C00)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWSETTINGPAGE_OFFSET UNITYSDK_OFFSET(0xCF8EA80)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWSNAPTIPS_OFFSET UNITYSDK_OFFSET(0xCF8F520)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWSTICKERCONTROLPAGE_OFFSET UNITYSDK_OFFSET(0xCF8E130)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWUIFADEINPHOTOPOPCLOSED_OFFSET UNITYSDK_OFFSET(0xCF8F470)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_STICKERLISTPROPERTYCHANGED_OFFSET UNITYSDK_OFFSET(0xCF94B60)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TAKECAPTURE_OFFSET UNITYSDK_OFFSET(0xCF95ED0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TOGGLEHIDEUI_OFFSET UNITYSDK_OFFSET(0xCF90660)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TOGGLESHOWUI_OFFSET UNITYSDK_OFFSET(0xCF8F5C0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TRYSHOWPHOTOWINDOWS_OFFSET UNITYSDK_OFFSET(0xCF95D10)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UNSETDRAGCALLBACKOLD_OFFSET UNITYSDK_OFFSET(0xCF9A270)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UNSETDRAGTWOPOINTCALLBACK_OFFSET UNITYSDK_OFFSET(0xCF9A350)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATEFRAMEMASK_OFFSET UNITYSDK_OFFSET(0xCF8FD20)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATEPHOTOMODEUICONTEXT_OFFSET UNITYSDK_OFFSET(0xCF8D050)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATEUIFRAMESIZE_OFFSET UNITYSDK_OFFSET(0xCF8FC10)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0xCF991B0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xCF9A860)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER__TAKECAPTURE_B__86_0_OFFSET UNITYSDK_OFFSET(0xCF9A9D0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER__TOGGLESHOWUI_B__38_0_OFFSET UNITYSDK_OFFSET(0xCF9A9C0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_GETCUSTOMBINDER_OFFSET UNITYSDK_OFFSET(0xCF9AA40)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xCF9AAB0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONHIDE_OFFSET UNITYSDK_OFFSET(0xCF9AB20)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET UNITYSDK_OFFSET(0xCF9AB80)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET UNITYSDK_OFFSET(0xCF9ABB0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONPREINPUTACTION_OFFSET UNITYSDK_OFFSET(0xCF9AC10)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONSHOW_OFFSET UNITYSDK_OFFSET(0xCF9ACA0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0xCF9ACB0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xCF9ACC0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xCF9ACD0)
#define MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xCF9ACE0)

namespace MoleMole
{
	inline static constexpr unsigned int UIMainCityCameraControlChildWindowController_TypeDefinitionIndex = 79713;

	class UIMainCityCameraControlChildWindowController : public ::MoleMole::UIWindowController
	{
	public:
		// static const ::System::String* MainCityCameraFlashFadeIn; // 0x0
		// static const ::System::String* MainCityCameraFlashFadeOut; // 0x0
		::System::Boolean _virtualCursorActive; // 0x2F8
		::System::Boolean _snapFlashing; // 0x2F9
		::System::Boolean _snapCapturing; // 0x2FA
		::System::Boolean _controlUIFading; // 0x2FB
		::System::Boolean _isControlHide; // 0x2FC
		::System::Boolean _switchFlashing; // 0x2FD
		::System::Boolean _photoPageRealShow; // 0x2FE
		::Class_1_FE835C8461DC4CA2* _animHelper; // 0x300
		::MoleMole::PhotoFrameCustomWidgetController* _InnerWidget; // 0x308
		::Class_2_5A5C316BDA7D0E0C_1* _binder; // 0x310
		::Class_1_43BD383C98B4C0C5_43* _bottomData; // 0x318
		::UnityEngine::Coroutine* LockAimCoroutine; // 0x320
		::UnityEngine::Coroutine* LockAimAddCoroutine; // 0x328
		::MoleMole::UIMainCityCameraControlChildWindowController_CameraSkillTipsState _tipsState; // 0x330
		::UnityEngine::UI::Extension::UISlider* _Slider; // 0x338
		::Class_1_634159F7561ADAA0<::MoleMole::UIStickerShowWidgetController*>* _stickerWidgetCtrlList; // 0x340
		::System::Boolean _draging; // 0x348
		::UnityEngine::RenderTexture* _photoRT; // 0x350
		::Class_1_81BCC5A7D87EA043* _capture; // 0x358
		::MoleMole::UIMainCityCameraControlChildWindowController_EUIState _currentUIState; // 0x360
		::MoleMole::UIMainCityCameraControlChildWindowController_EUIState _oldUIState; // 0x364
		::MoleMole::PhotoSettingContext* photoSettingContext; // 0x368
		::Class_2_79F6D62CE30E3F8E_178* _view; // 0x370
		::MoleMole::UIMainCityCameraControlContext* _context; // 0x378
		::MoleMole::UIPhotoModePlayerMoveChildWindowController* _joystickCtrl; // 0x380
		::MoleMole::UIPhotoGamePadDpadChildWindowController* _dPadCtrl; // 0x388
		::MoleMole::UIPhotoSettingChildWindowController* _settingCtrl; // 0x390
		::MoleMole::UIPhotoStickerControlPopWindowController* _stickerControlCtrl; // 0x398
		::MoleMole::UIActivityQuestTipsWidgetController* _activityQuestTipsCtrl; // 0x3A0
		::MoleMole::UIMainCityCameraControlTipsChildWindowController* _cameraTipsCtrl; // 0x3A8
		::MoleMole::UIMainCityCameraImgTrackWidgetController* _cameraImgTrackCtrl; // 0x3B0
		::MoleMole::UIGeneralVirtualPlayBtnChildWindowController* _leftShoulderBtnCtrl; // 0x3B8
		::MoleMole::UIGeneralVirtualPlayBtnChildWindowController* _rightShoulderBtnCtrl; // 0x3C0
		::System::Func_1<::System::Boolean>* _isEnableSwitchBtnFunc; // 0x3C8
		::MoleMole::UIGeneralNewsBubbleWidgetController* _bubbleWidgetCtrl; // 0x3D0
		::MoleMole::UIGeneralTipsCameraRowWidgetController* _generalTutorialTipsRowWidget; // 0x3D8
		::Class_2_40B7FA2256AD419F* _LastUIData_k__BackingField; // 0x3E0
		::System::Collections::Generic::Dictionary_2<::System::String*, ::MoleMole::UIMainCityCameraControlChildWindowController_TargetArrowUIItem*>* _targetArrowUIItems; // 0x3E8

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Boolean OnPreInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPREINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Boolean InputVirtualCursor(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INPUTVIRTUALCURSOR_OFFSET))(this, inputAction);
		}

		::System::Void ActiveVirtualCursor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ACTIVEVIRTUALCURSOR_OFFSET))(this);
		}

		::System::Void DeactiveVirtualCursor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_DEACTIVEVIRTUALCURSOR_OFFSET))(this);
		}

		::System::Boolean OnInputActiveHandle(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONINPUTACTIVEHANDLE_OFFSET))(this, inputAction);
		}

		::System::Boolean get_IsControlHide()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_ISCONTROLHIDE_OFFSET))(this);
		}

		::System::Boolean get_SnapCapturing()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_SNAPCAPTURING_OFFSET))(this);
		}

		::System::Boolean get_ControlUIFading()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_CONTROLUIFADING_OFFSET))(this);
		}

		::System::Boolean get_SnapFlashing()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_SNAPFLASHING_OFFSET))(this);
		}

		::System::Boolean get_SwitchFlashing()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_SWITCHFLASHING_OFFSET))(this);
		}

		::System::Void PlayFlashFadeIn(::System::Action* playEnd)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PLAYFLASHFADEIN_OFFSET))(this, playEnd);
		}

		::System::Void PlayFlashFadeOut(::System::Action* playEnd)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PLAYFLASHFADEOUT_OFFSET))(this, playEnd);
		}

		::System::Void PhotoUIPlayFadeIn(::System::Action* end)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PHOTOUIPLAYFADEIN_OFFSET))(this, end);
		}

		::System::Void PhotoUIPlayFadeOut(::System::Action* end)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PHOTOUIPLAYFADEOUT_OFFSET))(this, end);
		}

		::System::Void ShowUIFadeInPhotoPopClosed()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWUIFADEINPHOTOPOPCLOSED_OFFSET))(this);
		}

		::System::Void ShowInnerFrame(::Struct_2_FB00E96128CAB4FE innerFrame)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_FB00E96128CAB4FE))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWINNERFRAME_OFFSET))(this, innerFrame);
		}

		::System::Void UpdateUIFrameSize()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATEUIFRAMESIZE_OFFSET))(this);
		}

		::System::Void LoadFrameAssets(::Foundation::AssetPath assetPath, ::UnityEngine::Transform* parent, ::MoleMole::PhotoFrameCustomWidgetController*& widget)
		{
			return ((::System::Void(*)(::PVOID, ::Foundation::AssetPath, ::UnityEngine::Transform*, ::MoleMole::PhotoFrameCustomWidgetController*&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_LOADFRAMEASSETS_OFFSET))(this, assetPath, parent, widget);
		}

		::System::Void LoadConfigSetFrameInner()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_LOADCONFIGSETFRAMEINNER_OFFSET))(this);
		}

		::System::Void UpdateFrameMask()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATEFRAMEMASK_OFFSET))(this);
		}

		::System::Void OnPhotoInnerFrameChange(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOINNERFRAMECHANGE_OFFSET))(this, args);
		}

		::System::Void ToggleShowUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TOGGLESHOWUI_OFFSET))(this);
		}

		::System::Void ToggleHideUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TOGGLEHIDEUI_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_211* GetCustomBinder()
		{
			return ((::Class_0_16E4307DCC419505_211*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GETCUSTOMBINDER_OFFSET))(this);
		}

		::System::Void ShowBottomTips(::System::String* messageKey, ::System::Boolean isGetIcon)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWBOTTOMTIPS_OFFSET))(this, messageKey, isGetIcon);
		}

		::System::Void HideBottomTips()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_HIDEBOTTOMTIPS_OFFSET))(this);
		}

		::System::Void ShowLockAimTips(::System::String* animName, ::System::Single& clipLength)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Single&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWLOCKAIMTIPS_OFFSET))(this, animName, clipLength);
		}

		::System::Void ShowLockAddAimTips(::System::String* animName, ::System::Single& clipLength)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Single&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWLOCKADDAIMTIPS_OFFSET))(this, animName, clipLength);
		}

		::System::Void OnCameraSKillBtnChange(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCAMERASKILLBTNCHANGE_OFFSET))(this, obj);
		}

		::System::Void OnCameraControlTipsModify(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCAMERACONTROLTIPSMODIFY_OFFSET))(this, obj);
		}

		::System::Void OnCameraControlTipsClearALl(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCAMERACONTROLTIPSCLEARALL_OFFSET))(this, obj);
		}

		::System::Void RefreshSkillBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_REFRESHSKILLBTN_OFFSET))(this);
		}

		::System::Void SetTipState(::MoleMole::UIMainCityCameraControlChildWindowController_CameraSkillTipsState state, ::System::Boolean isForce)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIMainCityCameraControlChildWindowController_CameraSkillTipsState, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETTIPSTATE_OFFSET))(this, state, isForce);
		}

		::System::Void RefreshSkillTips()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_REFRESHSKILLTIPS_OFFSET))(this);
		}

		::System::Void InitBottomSlider()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INITBOTTOMSLIDER_OFFSET))(this);
		}

		::System::Void AddSliderWithoutNotify(::System::Single offsetPercent)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ADDSLIDERWITHOUTNOTIFY_OFFSET))(this, offsetPercent);
		}

		::System::Void SetSliderWithoutNotify(::System::Single percent)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETSLIDERWITHOUTNOTIFY_OFFSET))(this, percent);
		}

		::System::Void InitStickerShowModule()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INITSTICKERSHOWMODULE_OFFSET))(this);
		}

		::System::Void ClearStickerShowModule()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CLEARSTICKERSHOWMODULE_OFFSET))(this);
		}

		::System::Void OnShowSticker()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONSHOWSTICKER_OFFSET))(this);
		}

		::System::Void PointUpCallback(::UnityEngine::EventSystems::PointerEventData* eventData)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::EventSystems::PointerEventData*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_POINTUPCALLBACK_OFFSET))(this, eventData);
		}

		::System::Void EndDragCallback(::UnityEngine::EventSystems::PointerEventData* eventData, ::UnityEngine::Vector3 wordlPoint)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::EventSystems::PointerEventData*, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ENDDRAGCALLBACK_OFFSET))(this, eventData, wordlPoint);
		}

		::System::Void BeginDragCallback(::UnityEngine::EventSystems::PointerEventData* eventData, ::UnityEngine::Vector3 worldPoint)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::EventSystems::PointerEventData*, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_BEGINDRAGCALLBACK_OFFSET))(this, eventData, worldPoint);
		}

		::System::Void StickerListPropertyChanged(::Struct_2_C8629618711DF8B3& e)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_C8629618711DF8B3&))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_STICKERLISTPROPERTYCHANGED_OFFSET))(this, e);
		}

		::System::Void OnApplicationFocus(::System::Boolean hasFocus)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONAPPLICATIONFOCUS_OFFSET))(this, hasFocus);
		}

		::System::Void OnHideSticker()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONHIDESTICKER_OFFSET))(this);
		}

		::System::Void RefreshStickerShowWidgets()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_REFRESHSTICKERSHOWWIDGETS_OFFSET))(this);
		}

		::MoleMole::UIStickerShowWidgetController* FindStickerWidgetController(::System::Int32 stickerId, ::System::Int32 stickerIndex)
		{
			return ((::MoleMole::UIStickerShowWidgetController*(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_FINDSTICKERWIDGETCONTROLLER_OFFSET))(this, stickerId, stickerIndex);
		}

		::System::Void HideStickerControlPage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_HIDESTICKERCONTROLPAGE_OFFSET))(this);
		}

		::System::Void ShowStickerControlPage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWSTICKERCONTROLPAGE_OFFSET))(this);
		}

		::System::Void OnPhotoModeStartEditingStickerHandle(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODESTARTEDITINGSTICKERHANDLE_OFFSET))(this, obj);
		}

		::System::Void OnPhotoModeExitEditingStickerHandle(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODEEXITEDITINGSTICKERHANDLE_OFFSET))(this, obj);
		}

		::System::Void FullScreenBtnBottomCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_FULLSCREENBTNBOTTOMCALLBACK_OFFSET))(this);
		}

		::System::Collections::Generic::IList_1<::MoleMole::UIStickerShowWidgetController*>* GetActiveStickerWidgetCtrlList()
		{
			return ((::System::Collections::Generic::IList_1<::MoleMole::UIStickerShowWidgetController*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GETACTIVESTICKERWIDGETCTRLLIST_OFFSET))(this);
		}

		::UnityEngine::RectTransform* GetStickerRoot()
		{
			return ((::UnityEngine::RectTransform*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GETSTICKERROOT_OFFSET))(this);
		}

		::Class_1_81BCC5A7D87EA043* get_Capture()
		{
			return ((::Class_1_81BCC5A7D87EA043*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_CAPTURE_OFFSET))(this);
		}

		::System::Void OnEventCaptureFinish(::System::EventArgs* args)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONEVENTCAPTUREFINISH_OFFSET))(this, args);
		}

		::System::Void TakeCapture()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TAKECAPTURE_OFFSET))(this);
		}

		::System::Void CaptureImmediately()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CAPTUREIMMEDIATELY_OFFSET))(this);
		}

		::System::Void ReleaseCapture()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_RELEASECAPTURE_OFFSET))(this);
		}

		::System::Void OnFlashFinish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONFLASHFINISH_OFFSET))(this);
		}

		::System::Void TryShowPhotoWindows()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_TRYSHOWPHOTOWINDOWS_OFFSET))(this);
		}

		::System::Void ChangeUIState(::MoleMole::UIMainCityCameraControlChildWindowController_EUIState newState)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIMainCityCameraControlChildWindowController_EUIState))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CHANGEUISTATE_OFFSET))(this, newState);
		}

		::System::Void PhotoSettingHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_PHOTOSETTINGHIDE_OFFSET))(this);
		}

		::System::Void ShowSettingPage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWSETTINGPAGE_OFFSET))(this);
		}

		::System::Void OnClickSettingBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCLICKSETTINGBTN_OFFSET))(this);
		}

		::System::Void OnPhotoModeCloseSettingHandle(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODECLOSESETTINGHANDLE_OFFSET))(this, obj);
		}

		::System::Void OnClickSettingHideBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCLICKSETTINGHIDEBTN_OFFSET))(this);
		}

		::Enum_3_3EDF246633A325B0 get_windowType()
		{
			return ((::Enum_3_3EDF246633A325B0(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_WINDOWTYPE_OFFSET))(this);
		}

		::UnityEngine::RectTransform* get_DetectRect()
		{
			return ((::UnityEngine::RectTransform*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_DETECTRECT_OFFSET))(this);
		}

		::System::Boolean get_IsSupportFrontCameraMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_ISSUPPORTFRONTCAMERAMODE_OFFSET))(this);
		}

		::System::Boolean get_IsEnableSwitchBtn()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_ISENABLESWITCHBTN_OFFSET))(this);
		}

		::Class_2_40B7FA2256AD419F* get_LastUIData()
		{
			return ((::Class_2_40B7FA2256AD419F*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_GET_LASTUIDATA_OFFSET))(this);
		}

		::System::Void set_LastUIData(::Class_2_40B7FA2256AD419F* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_40B7FA2256AD419F*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SET_LASTUIDATA_OFFSET))(this, value);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnShow(::MoleMole::UIControllerContextBase* showCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONSHOW_OFFSET))(this, showCtrlContext);
		}

		::System::Void OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONHIDE_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Boolean OnInputAction(::MoleMole::InputActionEvent inputAction)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONINPUTACTION_OFFSET))(this, inputAction);
		}

		::System::Void SetSnapBtnInteractable(::System::Boolean interactable)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETSNAPBTNINTERACTABLE_OFFSET))(this, interactable);
		}

		::System::Void InitContext()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_INITCONTEXT_OFFSET))(this);
		}

		::System::Void UpdatePhotoModeUIContext(::Class_2_40B7FA2256AD419F* uiData)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_40B7FA2256AD419F*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATEPHOTOMODEUICONTEXT_OFFSET))(this, uiData);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void LateUpdate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_LATEUPDATE_OFFSET))(this);
		}

		::System::Void ClearOutdatedTargetArrowUI()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_CLEAROUTDATEDTARGETARROWUI_OFFSET))(this);
		}

		::System::Void OnCloseTargetArrow(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONCLOSETARGETARROW_OFFSET))(this, obj);
		}

		::System::Void ShowBottomSliders(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWBOTTOMSLIDERS_OFFSET))(this, isActive);
		}

		::System::Void ShowSnapTips(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWSNAPTIPS_OFFSET))(this, isActive);
		}

		::System::Void SetSnapTips(::System::String* textmap)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETSNAPTIPS_OFFSET))(this, textmap);
		}

		::System::Void ShowFullScreenBtn(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SHOWFULLSCREENBTN_OFFSET))(this, isActive);
		}

		::System::Void SetInputControlRootActive(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETINPUTCONTROLROOTACTIVE_OFFSET))(this, isActive);
		}

		::System::Void SetCameraImgActive(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETCAMERAIMGACTIVE_OFFSET))(this, isActive);
		}

		::System::Void SetMoveBtnRootActive(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETMOVEBTNROOTACTIVE_OFFSET))(this, isActive);
		}

		::System::Void SetFrontCameraTipsActive(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETFRONTCAMERATIPSACTIVE_OFFSET))(this, isActive);
		}

		::System::Void SetDragCallbackOld(::UnityEngine::UI::Extension::UIImgEventTrigger_DragCallbackOld* dragCallback)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::UI::Extension::UIImgEventTrigger_DragCallbackOld*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETDRAGCALLBACKOLD_OFFSET))(this, dragCallback);
		}

		::System::Void SetDragTwoPointCallback(::UnityEngine::UI::Extension::UIImgEventTrigger_TwoPointDragCallback* dragTwoPointCallback)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::UI::Extension::UIImgEventTrigger_TwoPointDragCallback*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETDRAGTWOPOINTCALLBACK_OFFSET))(this, dragTwoPointCallback);
		}

		::System::Void UnSetDragCallbackOld(::UnityEngine::UI::Extension::UIImgEventTrigger_DragCallbackOld* dragCallback)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::UI::Extension::UIImgEventTrigger_DragCallbackOld*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UNSETDRAGCALLBACKOLD_OFFSET))(this, dragCallback);
		}

		::System::Void UnSetDragTwoPointCallback(::UnityEngine::UI::Extension::UIImgEventTrigger_TwoPointDragCallback* dragTwoPointCallback)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::UI::Extension::UIImgEventTrigger_TwoPointDragCallback*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_UNSETDRAGTWOPOINTCALLBACK_OFFSET))(this, dragTwoPointCallback);
		}

		::System::Void SetActive_ConsoleTips_LeftStick(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_CONSOLETIPS_LEFTSTICK_OFFSET))(this, isActive);
		}

		::System::Void SetActive_ConsoleTips_RightStick(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_CONSOLETIPS_RIGHTSTICK_OFFSET))(this, isActive);
		}

		::System::Void SetActive_ConsoleTips_DPad(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_CONSOLETIPS_DPAD_OFFSET))(this, isActive);
		}

		::System::Void SetActive_PCTips_WASD(::System::Boolean isActive)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_SETACTIVE_PCTIPS_WASD_OFFSET))(this, isActive);
		}

		::System::Void OnShowFairy(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONSHOWFAIRY_OFFSET))(this, obj);
		}

		::System::Void OnFairyFinish(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONFAIRYFINISH_OFFSET))(this, obj);
		}

		::System::Void OnPhotoModeUIRefresh(::System::EventArgs* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::EventArgs*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER_ONPHOTOMODEUIREFRESH_OFFSET))(this, obj);
		}

		::System::Void _ToggleShowUI_b__38_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER__TOGGLESHOWUI_B__38_0_OFFSET))(this);
		}

		::System::Void _TakeCapture_b__86_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER__TAKECAPTURE_B__86_0_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_211* __base_GetCustomBinder()
		{
			return ((::Class_0_16E4307DCC419505_211*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_GETCUSTOMBINDER_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONHIDE_OFFSET))(this);
		}

		::System::Boolean __base_OnInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnLayoutPlatformChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONLAYOUTPLATFORMCHANGED_OFFSET))(this);
		}

		::System::Boolean __base_OnPreInputAction(::MoleMole::InputActionEvent P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::MoleMole::InputActionEvent))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONPREINPUTACTION_OFFSET))(this, P0);
		}

		::System::Void __base_OnShow(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONSHOW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINCITYCAMERACONTROLCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
