#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/ScrollViewItemWidgetController.h"

class Class_2_79F6D62CE30E3F8E_136;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class Object; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }

#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONCLICKGOTBTN_OFFSET UNITYSDK_OFFSET(0x6CD1BB0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x6CD07E0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONSCROLLITEMUPDATE_OFFSET UNITYSDK_OFFSET(0x6CD0C10)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x6CD1070)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x6CD10E0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x6CD0880)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x6CD0B60)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_REFRESHBTNVIEW_OFFSET UNITYSDK_OFFSET(0x6CD14A0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0x6CD0EF0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_SETEMPTY_OFFSET UNITYSDK_OFFSET(0x6CD0E20)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_SETREWARD_OFFSET UNITYSDK_OFFSET(0x6CD11B0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_UPDATEFINISHEDNOTGOTBTN_OFFSET UNITYSDK_OFFSET(0x6CD1500)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_UPDATENOTFINISHEDBTN_OFFSET UNITYSDK_OFFSET(0x6CD1990)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_UPDATEREWARDGOTBTN_OFFSET UNITYSDK_OFFSET(0x6CD1790)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x6CD1C10)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x6CD1C20)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONSCROLLITEMUPDATE_OFFSET UNITYSDK_OFFSET(0x6CD1C90)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET UNITYSDK_OFFSET(0x6CD1D10)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x6CD1D20)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x6CD1DA0)
#define MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x6CD1E00)

namespace MoleMole
{
	inline static constexpr unsigned int UIMainStoryRewardRowChildWindowController_TypeDefinitionIndex = 55679;

	class UIMainStoryRewardRowChildWindowController : public ::MoleMole::ScrollViewItemWidgetController
	{
	public:
		::Class_2_79F6D62CE30E3F8E_136* _view; // 0x2D0
		::System::Int32 _vhsTemplateID; // 0x2D8
		::System::UInt16 _star; // 0x2DC
		::System::Int32 _curdiff; // 0x2E0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnScrollItemUpdate(::System::Int32 index, ::System::Object* data, ::System::Boolean init)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONSCROLLITEMUPDATE_OFFSET))(this, index, data, init);
		}

		::System::Void OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUICLOSE_OFFSET))(this);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void RefreshView(::System::Int32 vhsTemplateID, ::System::UInt16 star, ::System::Int32 diff)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::UInt16, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_REFRESHVIEW_OFFSET))(this, vhsTemplateID, star, diff);
		}

		::System::Void SetEmpty(::System::Boolean isEmpty)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_SETEMPTY_OFFSET))(this, isEmpty);
		}

		::System::Void SetReward(::System::Collections::Generic::Dictionary_2<::System::Int32, ::System::Int32>* rewards)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::Dictionary_2<::System::Int32, ::System::Int32>*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_SETREWARD_OFFSET))(this, rewards);
		}

		::System::Void RefreshBtnView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_REFRESHBTNVIEW_OFFSET))(this);
		}

		::System::Void UpdateFinishedNotGotBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_UPDATEFINISHEDNOTGOTBTN_OFFSET))(this);
		}

		::System::Void UpdateRewardGotBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_UPDATEREWARDGOTBTN_OFFSET))(this);
		}

		::System::Void UpdateNotFinishedBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_UPDATENOTFINISHEDBTN_OFFSET))(this);
		}

		::System::Void OnClickGotBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER_ONCLICKGOTBTN_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnScrollItemUpdate(::System::Int32 P0, ::System::Object* P1, ::System::Boolean P2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONSCROLLITEMUPDATE_OFFSET))(this, P0, P1, P2);
		}

		::System::Void __base_OnUIClose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUICLOSE_OFFSET))(this);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIMAINSTORYREWARDROWCHILDWINDOWCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
