#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/ScrollViewItemWidgetController.h"

class Class_2_208CC9941471731A_71;
class Class_2_79AE422BA06F6D26_20;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace System { class Object; }

#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_BINDVIEWCALLBACKS_OFFSET UNITYSDK_OFFSET(0xAE3F8B0)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_GETCURAQUARIUMDECORATIONCONFIG_OFFSET UNITYSDK_OFFSET(0xAE40A80)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xAE3FC90)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONITEMSELECT_OFFSET UNITYSDK_OFFSET(0xAE40840)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONPOPULARITYICONBUTTON_OFFSET UNITYSDK_OFFSET(0xAE40930)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONSCROLLITEMUPDATE_OFFSET UNITYSDK_OFFSET(0xAE3FE10)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xAE3FD30)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xAE3F530)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xAE3F7F0)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_REFRESHVIEW_OFFSET UNITYSDK_OFFSET(0xAE40060)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0xAE40AF0)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0xAE40B00)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONITEMSELECT_OFFSET UNITYSDK_OFFSET(0xAE40B70)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONSCROLLITEMUPDATE_OFFSET UNITYSDK_OFFSET(0xAE40BE0)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0xAE40C60)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0xAE40CE0)
#define MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0xAE40D40)

namespace MoleMole
{
	inline static constexpr unsigned int UISummerFishAquariumDecorationRowWidgetController_TypeDefinitionIndex = 38420;

	class UISummerFishAquariumDecorationRowWidgetController : public ::MoleMole::ScrollViewItemWidgetController
	{
	public:
		::Class_2_79AE422BA06F6D26_20* _view; // 0x2D0
		::Class_2_208CC9941471731A_71* _curAquariumDecorationConfig; // 0x2D8

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void OnScrollItemUpdate(::System::Int32 index, ::System::Object* data, ::System::Boolean init)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONSCROLLITEMUPDATE_OFFSET))(this, index, data, init);
		}

		::System::Void OnItemSelect(::System::Boolean isSelect)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONITEMSELECT_OFFSET))(this, isSelect);
		}

		::System::Void BindViewCallbacks()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_BINDVIEWCALLBACKS_OFFSET))(this);
		}

		::System::Void OnPopularityIconButton()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_ONPOPULARITYICONBUTTON_OFFSET))(this);
		}

		::System::Void RefreshView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_REFRESHVIEW_OFFSET))(this);
		}

		::Class_2_208CC9941471731A_71* GetCurAquariumDecorationConfig()
		{
			return ((::Class_2_208CC9941471731A_71*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER_GETCURAQUARIUMDECORATIONCONFIG_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnItemSelect(::System::Boolean P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONITEMSELECT_OFFSET))(this, P0);
		}

		::System::Void __base_OnScrollItemUpdate(::System::Int32 P0, ::System::Object* P1, ::System::Boolean P2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONSCROLLITEMUPDATE_OFFSET))(this, P0, P1, P2);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUMMERFISHAQUARIUMDECORATIONROWWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
