#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_F57C3EEEB03201AF.h"

class Class_2_01B22E9930E7BB4D;
template <typename T> class Class_0_16E4307DCC419505_102;
template <typename T> class Class_0_16E4307DCC419505_119;

#define MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL_GET_TEMPLEBUDDY_OFFSET UNITYSDK_OFFSET(0xAB9FFF0)
#define MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL_ONCREATEPROPERTY_OFFSET UNITYSDK_OFFSET(0xABA00B0)
#define MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL_SET_TEMPLEBUDDY_OFFSET UNITYSDK_OFFSET(0xABA0000)
#define MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xABA0500)
#define MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL__ONCREATEPROPERTY_B__8_0_OFFSET UNITYSDK_OFFSET(0xABA0580)

namespace MoleMole
{
	inline static constexpr unsigned int UISuibianTempleBuddyAddPointPopWindowController_ViewModel_TypeDefinitionIndex = 64755;

	class UISuibianTempleBuddyAddPointPopWindowController_ViewModel : public ::Class_1_F57C3EEEB03201AF
	{
	public:
		::Class_0_16E4307DCC419505_119<::System::Int32>* DurabilityAddPoint; // 0x60
		::Class_0_16E4307DCC419505_119<::System::Int32>* SimulationAddPoint; // 0x68
		::Class_0_16E4307DCC419505_119<::System::Int32>* ExpeditionAddPoint; // 0x70
		::Class_2_01B22E9930E7BB4D* _templeBuddy; // 0x78
		::Class_0_16E4307DCC419505_102<::System::Int32>* AvailablePoint; // 0x80

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL__CTOR_OFFSET))(this);
		}

		::Class_2_01B22E9930E7BB4D* get_TempleBuddy()
		{
			return ((::Class_2_01B22E9930E7BB4D*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL_GET_TEMPLEBUDDY_OFFSET))(this);
		}

		::System::Void set_TempleBuddy(::Class_2_01B22E9930E7BB4D* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_01B22E9930E7BB4D*))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL_SET_TEMPLEBUDDY_OFFSET))(this, value);
		}

		::System::Void OnCreateProperty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL_ONCREATEPROPERTY_OFFSET))(this);
		}

		::System::Int32 _OnCreateProperty_b__8_0()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UISUIBIANTEMPLEBUDDYADDPOINTPOPWINDOWCONTROLLER_VIEWMODEL__ONCREATEPROPERTY_B__8_0_OFFSET))(this);
		}
	};
}
