#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/UIWidgetController.h"

class Class_1_6C36C0127DB30EF4;
class Class_1_884ED93DC98FC7FA;
class Class_2_208CC9941471731A_98;
class Class_2_56AF18CD74DA940A_3;
namespace MoleMole { class UIControlReference; }
namespace MoleMole { class UIControllerContextBase; }
namespace MoleMole { class UIYorozuyaChapterMap3DModelController; }
namespace MoleMole { class UIYorozuyaMapTipsChildWindowController; }
namespace MoleMole::Config { class HollowPosConfig; }
namespace System { class String; }
namespace UnityEngine { class Animation; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Transform; }

#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_DOHIDE_OFFSET UNITYSDK_OFFSET(0x68532C0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_DOSHOW_OFFSET UNITYSDK_OFFSET(0x6853600)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETFADEINANINAME_OFFSET UNITYSDK_OFFSET(0x68539D0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETFADEOUTANINAME_OFFSET UNITYSDK_OFFSET(0x6853570)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETHIDEANI_OFFSET UNITYSDK_OFFSET(0x6854A10)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETHOLLOWCONFIGID_OFFSET UNITYSDK_OFFSET(0x6854DB0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETIDLEANI_OFFSET UNITYSDK_OFFSET(0x68541F0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETLOCKFADEIN_OFFSET UNITYSDK_OFFSET(0x6854630)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETLOCKFADEOUT_OFFSET UNITYSDK_OFFSET(0x6854820)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETMODELRES_OFFSET UNITYSDK_OFFSET(0x6854BF0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETSHOWANI_OFFSET UNITYSDK_OFFSET(0x6854450)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETSPHEREPROPERTIES_OFFSET UNITYSDK_OFFSET(0x6854C70)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETUNLOCKANI_OFFSET UNITYSDK_OFFSET(0x6854000)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_EXCELCONFIG_OFFSET UNITYSDK_OFFSET(0x6855450)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_MODELCONTROLLER_OFFSET UNITYSDK_OFFSET(0x68554F0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_POSCONFIG_OFFSET UNITYSDK_OFFSET(0x6855430)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_SPHEREMODEL_OFFSET UNITYSDK_OFFSET(0x68554D0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ISRALLYSPHERE_OFFSET UNITYSDK_OFFSET(0x6854CE0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_LOADSHPERE_OFFSET UNITYSDK_OFFSET(0x6852A80)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONCLICK_1_OFFSET UNITYSDK_OFFSET(0x6854EB0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONCLICK_OFFSET UNITYSDK_OFFSET(0x6854E40)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x6852450)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x68524F0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x68522A0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x68523A0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_PLAYIDLEANI_OFFSET UNITYSDK_OFFSET(0x6853A90)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_PLAYTRACKFADEANI_OFFSET UNITYSDK_OFFSET(0x6853070)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_PLAYUNLOCKANI_OFFSET UNITYSDK_OFFSET(0x6853BB0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SETDATA_OFFSET UNITYSDK_OFFSET(0x68527F0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SETTIP_OFFSET UNITYSDK_OFFSET(0x6853250)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SET_MODELCONTROLLER_OFFSET UNITYSDK_OFFSET(0x6855500)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SET_POSCONFIG_OFFSET UNITYSDK_OFFSET(0x6855440)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SET_SPHEREMODEL_OFFSET UNITYSDK_OFFSET(0x68554E0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_UPDATETEST_OFFSET UNITYSDK_OFFSET(0x6855310)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_UPDATE_OFFSET UNITYSDK_OFFSET(0x6852780)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__CTOR_OFFSET UNITYSDK_OFFSET(0x6855510)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__DOSHOW_B__9_0_OFFSET UNITYSDK_OFFSET(0x6855540)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__DOSHOW_B__9_1_OFFSET UNITYSDK_OFFSET(0x6855570)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__PLAYUNLOCKANI_B__10_0_OFFSET UNITYSDK_OFFSET(0x6855610)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET UNITYSDK_OFFSET(0x68556B0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET UNITYSDK_OFFSET(0x6855720)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET UNITYSDK_OFFSET(0x68557A0)
#define MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET UNITYSDK_OFFSET(0x6855800)

namespace MoleMole
{
	inline static constexpr unsigned int UIYorozuyaSphereItemWidgetController_TypeDefinitionIndex = 49624;

	class UIYorozuyaSphereItemWidgetController : public ::MoleMole::UIWidgetController
	{
	public:
		// static const ::System::String* sphere_urgent_s_res; // 0x0
		// static const ::System::String* sphere_urgent_m_res; // 0x0
		// static const ::System::String* sphere_urgent_l_res; // 0x0
		::Class_2_56AF18CD74DA940A_3* _view; // 0x2A0
		::Class_1_884ED93DC98FC7FA* _data; // 0x2A8
		::Class_1_6C36C0127DB30EF4* sphereProperties; // 0x2B0
		::MoleMole::Config::HollowPosConfig* _PosConfig_k__BackingField; // 0x2B8
		::UnityEngine::GameObject* _SphereModel_k__BackingField; // 0x2C0
		::UnityEngine::Transform* trackEffect; // 0x2C8
		::UnityEngine::Animation* trackAni; // 0x2D0
		::MoleMole::UIYorozuyaChapterMap3DModelController* _ModelController_k__BackingField; // 0x2D8
		::UnityEngine::Animation* sphereAnimation; // 0x2E0
		::MoleMole::UIYorozuyaMapTipsChildWindowController* tipCtrl; // 0x2E8
		::System::String* HideAni; // 0x2F0
		::System::String* ShowAni; // 0x2F8
		::System::String* IdleAni; // 0x300
		::System::String* LockFadeIn; // 0x308
		::System::String* LockFadeOut; // 0x310
		::System::String* UnlockAni; // 0x318

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__CTOR_OFFSET))(this);
		}

		::System::Void OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONUIINIT_OFFSET))(this);
		}

		::System::Void OnUIOpen(::MoleMole::UIControllerContextBase* openCtrlContext)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONUIOPEN_OFFSET))(this, openCtrlContext);
		}

		::System::Void OnCreateView(::MoleMole::UIControlReference* controlReference)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONCREATEVIEW_OFFSET))(this, controlReference);
		}

		::System::Void OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_UPDATE_OFFSET))(this);
		}

		::System::Void SetData(::Class_1_884ED93DC98FC7FA* data)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_884ED93DC98FC7FA*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SETDATA_OFFSET))(this, data);
		}

		::System::Void SetTip(::MoleMole::UIYorozuyaMapTipsChildWindowController* tipCtrl)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIYorozuyaMapTipsChildWindowController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SETTIP_OFFSET))(this, tipCtrl);
		}

		::System::Single DoHide()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_DOHIDE_OFFSET))(this);
		}

		::System::Single DoShow()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_DOSHOW_OFFSET))(this);
		}

		::System::Void PlayUnLockAni()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_PLAYUNLOCKANI_OFFSET))(this);
		}

		::System::Void PlayIdleAni(::System::Single delay)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_PLAYIDLEANI_OFFSET))(this, delay);
		}

		::System::String* GetFadeInAniName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETFADEINANINAME_OFFSET))(this);
		}

		::System::String* GetFadeOutAniName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETFADEOUTANINAME_OFFSET))(this);
		}

		::System::Void LoadShpere()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_LOADSHPERE_OFFSET))(this);
		}

		::System::Void PlayTrackFadeAni(::System::Boolean isFadeIn, ::System::Boolean direct)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_PLAYTRACKFADEANI_OFFSET))(this, isFadeIn, direct);
		}

		::Class_1_6C36C0127DB30EF4* GetSphereProperties()
		{
			return ((::Class_1_6C36C0127DB30EF4*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETSPHEREPROPERTIES_OFFSET))(this);
		}

		::System::Boolean IsRallySphere()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ISRALLYSPHERE_OFFSET))(this);
		}

		::System::Int32 GetHollowConfigID()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETHOLLOWCONFIGID_OFFSET))(this);
		}

		::System::Void OnClick()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONCLICK_OFFSET))(this);
		}

		::System::Void OnClick_1(::System::Int32 defaultQuestID)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_ONCLICK_1_OFFSET))(this, defaultQuestID);
		}

		::System::Void UpdateTest()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_UPDATETEST_OFFSET))(this);
		}

		::System::String* GetModelRes()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETMODELRES_OFFSET))(this);
		}

		::System::String* GetShowAni()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETSHOWANI_OFFSET))(this);
		}

		::System::String* GetHideAni()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETHIDEANI_OFFSET))(this);
		}

		::System::String* GetIdleAni()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETIDLEANI_OFFSET))(this);
		}

		::System::String* GetLockFadeIn()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETLOCKFADEIN_OFFSET))(this);
		}

		::System::String* GetLockFadeOut()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETLOCKFADEOUT_OFFSET))(this);
		}

		::System::String* GetUnlockAni()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GETUNLOCKANI_OFFSET))(this);
		}

		::MoleMole::Config::HollowPosConfig* get_PosConfig()
		{
			return ((::MoleMole::Config::HollowPosConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_POSCONFIG_OFFSET))(this);
		}

		::System::Void set_PosConfig(::MoleMole::Config::HollowPosConfig* value)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::Config::HollowPosConfig*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SET_POSCONFIG_OFFSET))(this, value);
		}

		::Class_2_208CC9941471731A_98* get_ExcelConfig()
		{
			return ((::Class_2_208CC9941471731A_98*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_EXCELCONFIG_OFFSET))(this);
		}

		::UnityEngine::GameObject* get_SphereModel()
		{
			return ((::UnityEngine::GameObject*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_SPHEREMODEL_OFFSET))(this);
		}

		::System::Void set_SphereModel(::UnityEngine::GameObject* value)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SET_SPHEREMODEL_OFFSET))(this, value);
		}

		::MoleMole::UIYorozuyaChapterMap3DModelController* get_ModelController()
		{
			return ((::MoleMole::UIYorozuyaChapterMap3DModelController*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_GET_MODELCONTROLLER_OFFSET))(this);
		}

		::System::Void set_ModelController(::MoleMole::UIYorozuyaChapterMap3DModelController* value)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIYorozuyaChapterMap3DModelController*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER_SET_MODELCONTROLLER_OFFSET))(this, value);
		}

		::System::Void _DoShow_b__9_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__DOSHOW_B__9_0_OFFSET))(this);
		}

		::System::Void _DoShow_b__9_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__DOSHOW_B__9_1_OFFSET))(this);
		}

		::System::Void _PlayUnLockAni_b__10_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER__PLAYUNLOCKANI_B__10_0_OFFSET))(this);
		}

		::System::Void __base_OnCreateView(::MoleMole::UIControlReference* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControlReference*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONCREATEVIEW_OFFSET))(this, P0);
		}

		::System::Void __base_OnUIDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONUIDESTROY_OFFSET))(this);
		}

		::System::Void __base_OnUIInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONUIINIT_OFFSET))(this);
		}

		::System::Void __base_OnUIOpen(::MoleMole::UIControllerContextBase* P0)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::UIControllerContextBase*))((::PBYTE)hIl2Cpp + MOLEMOLE_UIYOROZUYASPHEREITEMWIDGETCONTROLLER___BASE_ONUIOPEN_OFFSET))(this, P0);
		}
	};
}
