#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/MoleMole/EffectSimulate/ESMatFloatAnimation.h"

namespace UnityEngine { class GameObject; }

#define MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_3930520F0E246403_OFFSET UNITYSDK_OFFSET(0xD7E1670)
#define MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_6C9DB194C334F348_1_OFFSET UNITYSDK_OFFSET(0xD7E1620)
#define MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_6C9DB194C334F348_OFFSET UNITYSDK_OFFSET(0xD7E14B0)
#define MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_E6D10C319383FEBA_OFFSET UNITYSDK_OFFSET(0xD7E1410)
#define MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION__CTOR_OFFSET UNITYSDK_OFFSET(0xD7E1580)

namespace MoleMole::EffectSimulate
{
	inline static constexpr unsigned int ESMatFloatAnimationParticleCustomDataVersion_TypeDefinitionIndex = 51650;

	class ESMatFloatAnimationParticleCustomDataVersion : public ::MoleMole::EffectSimulate::ESMatFloatAnimation
	{
	public:
		::System::Boolean m_bHasSetOffset; // 0xA8

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION__CTOR_OFFSET))(this);
		}

		::System::Void Method_6_E6D10C319383FEBA(::UnityEngine::GameObject* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_E6D10C319383FEBA_OFFSET))(this, a1);
		}

		::System::Void Method_6_6C9DB194C334F348(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_6C9DB194C334F348_OFFSET))(this, a1);
		}

		::System::Void Method_6_6C9DB194C334F348_1(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_6C9DB194C334F348_1_OFFSET))(this, a1);
		}

		::System::Void Method_6_3930520F0E246403(::UnityEngine::GameObject* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESMATFLOATANIMATIONPARTICLECUSTOMDATAVERSION_METHOD_6_3930520F0E246403_OFFSET))(this, a1);
		}
	};
}
