#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_17B78A87EAE1DCED.h"
#include "unitysdk/MoleMole/EffectSimulate/IEffectSimulate.h"
#include "unitysdk/UnityEngine/ParticleSystem_MinMaxCurve.h"
#include "unitysdk/UnityEngine/Vector2Int.h"

namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class AnimationCurve; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Material; }
namespace UnityEngine { class MaterialPropertyBlock; }
namespace UnityEngine { class Renderer; }

#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_FRAMEOVERTIME_OFFSET UNITYSDK_OFFSET(0xC9B0A80)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRCURVE_OFFSET UNITYSDK_OFFSET(0xC9B0D10)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRLOOP_OFFSET UNITYSDK_OFFSET(0xC9B0E10)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRONELOOPDURATION_OFFSET UNITYSDK_OFFSET(0xC9B0F10)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRTEXNAME_OFFSET UNITYSDK_OFFSET(0xC9B1010)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_TILES_OFFSET UNITYSDK_OFFSET(0xC9B0390)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_1D4018D4200358D0_OFFSET UNITYSDK_OFFSET(0xC9B2A50)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_2685B6183E614529_OFFSET UNITYSDK_OFFSET(0xC9B2BF0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_31F1C58AB372DEB4_OFFSET UNITYSDK_OFFSET(0xC9B12E0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_35B574BF35040A2E_OFFSET UNITYSDK_OFFSET(0xC9B2760)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_1_OFFSET UNITYSDK_OFFSET(0xC9B2450)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_2_OFFSET UNITYSDK_OFFSET(0xC9B2700)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_3_OFFSET UNITYSDK_OFFSET(0xC9B2AD0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_4_OFFSET UNITYSDK_OFFSET(0xC9B2D00)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0xC9B22D0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_49AC00594530B714_1_OFFSET UNITYSDK_OFFSET(0xC9B2B90)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_49AC00594530B714_OFFSET UNITYSDK_OFFSET(0xC9B24B0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_4B2CD7086A8CA682_OFFSET UNITYSDK_OFFSET(0xC9B04E0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_4F6948586D063855_OFFSET UNITYSDK_OFFSET(0xC9B06D0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_581A5078A2F29034_OFFSET UNITYSDK_OFFSET(0xC9B2690)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_595E641DF1B4387D_OFFSET UNITYSDK_OFFSET(0xC9B1110)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_5BF0E61BD5CA40A5_OFFSET UNITYSDK_OFFSET(0xC9B2510)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_88B60F3B95FAA4F1_1_OFFSET UNITYSDK_OFFSET(0xC9B23C0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_88B60F3B95FAA4F1_OFFSET UNITYSDK_OFFSET(0xC9B2330)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_8EA91B93B34817EA_OFFSET UNITYSDK_OFFSET(0xC9B2C60)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_C433AF37CE9D6E5B_OFFSET UNITYSDK_OFFSET(0xC9B29E0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_DA1BF2C227DC3D86_1_OFFSET UNITYSDK_OFFSET(0xC9B2B30)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_DA1BF2C227DC3D86_OFFSET UNITYSDK_OFFSET(0xC9B26A0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_EC8E696CD17E914C_OFFSET UNITYSDK_OFFSET(0xC9B17F0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_FRAMEOVERTIME_OFFSET UNITYSDK_OFFSET(0xC9B0BD0)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRCURVE_OFFSET UNITYSDK_OFFSET(0xC9B0D90)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRLOOP_OFFSET UNITYSDK_OFFSET(0xC9B0E90)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRONELOOPDURATION_OFFSET UNITYSDK_OFFSET(0xC9B0F80)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRTEXNAME_OFFSET UNITYSDK_OFFSET(0xC9B1090)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_TILES_OFFSET UNITYSDK_OFFSET(0xC9B0930)
#define MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION__CTOR_OFFSET UNITYSDK_OFFSET(0xC9B2640)

namespace MoleMole::EffectSimulate
{
	inline static constexpr unsigned int ESTextureSheetAnimation_TypeDefinitionIndex = 42008;

	class ESTextureSheetAnimation : public ::MoleMole::EffectSimulate::IEffectSimulate
	{
	public:
		// static const ::System::String* MESH_RENDERER_GROUP_NAME; // 0x0
		::UnityEngine::Vector2Int m_stTiles; // 0x48
		::UnityEngine::AnimationCurve* m_stMRCurve; // 0x50
		::System::Boolean m_bMRLoop; // 0x58
		::System::Single m_fOneLoopDuration; // 0x5C
		::System::String* m_sTexName; // 0x60
		::UnityEngine::Material* psMat; // 0x68
		::UnityEngine::Material* mrMat; // 0x70
		::UnityEngine::MaterialPropertyBlock* mrPropBlock; // 0x78
		::UnityEngine::Renderer* mrRenderer; // 0x80

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION__CTOR_OFFSET))(this);
		}

		::UnityEngine::Vector2Int get_tiles()
		{
			return ((::UnityEngine::Vector2Int(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_TILES_OFFSET))(this);
		}

		::System::Void set_tiles(::UnityEngine::Vector2Int a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2Int))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_TILES_OFFSET))(this, a1);
		}

		::UnityEngine::ParticleSystem_MinMaxCurve get_frameOverTime()
		{
			return ((::UnityEngine::ParticleSystem_MinMaxCurve(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_FRAMEOVERTIME_OFFSET))(this);
		}

		::System::Void set_frameOverTime(::UnityEngine::ParticleSystem_MinMaxCurve a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem_MinMaxCurve))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_FRAMEOVERTIME_OFFSET))(this, a1);
		}

		::UnityEngine::AnimationCurve* get_mrCurve()
		{
			return ((::UnityEngine::AnimationCurve*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRCURVE_OFFSET))(this);
		}

		::System::Void set_mrCurve(::UnityEngine::AnimationCurve* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::AnimationCurve*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRCURVE_OFFSET))(this, a1);
		}

		::System::Boolean get_mrLoop()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRLOOP_OFFSET))(this);
		}

		::System::Void set_mrLoop(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRLOOP_OFFSET))(this, a1);
		}

		::System::Single get_mrOneLoopDuration()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRONELOOPDURATION_OFFSET))(this);
		}

		::System::Void set_mrOneLoopDuration(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRONELOOPDURATION_OFFSET))(this, a1);
		}

		::System::String* get_mrTexName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_GET_MRTEXNAME_OFFSET))(this);
		}

		::System::Void set_mrTexName(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_SET_MRTEXNAME_OFFSET))(this, a1);
		}

		::System::Boolean Method_2_595E641DF1B4387D()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_595E641DF1B4387D_OFFSET))(this);
		}

		::System::Void Method_2_31F1C58AB372DEB4(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_31F1C58AB372DEB4_OFFSET))(this, a1);
		}

		::System::Void Method_2_EC8E696CD17E914C(::UnityEngine::GameObject* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_EC8E696CD17E914C_OFFSET))(this, a1);
		}

		::System::Boolean Method_2_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_OFFSET))(this);
		}

		::System::String* Method_2_88B60F3B95FAA4F1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_88B60F3B95FAA4F1_OFFSET))(this);
		}

		::System::String* Method_2_88B60F3B95FAA4F1_1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_88B60F3B95FAA4F1_1_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_1()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_1_OFFSET))(this);
		}

		::Enum_3_17B78A87EAE1DCED Method_2_49AC00594530B714()
		{
			return ((::Enum_3_17B78A87EAE1DCED(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_49AC00594530B714_OFFSET))(this);
		}

		::System::String* Method_2_5BF0E61BD5CA40A5()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_5BF0E61BD5CA40A5_OFFSET))(this);
		}

		::System::String* Method_2_581A5078A2F29034()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_581A5078A2F29034_OFFSET))(this);
		}

		::System::String* Method_2_DA1BF2C227DC3D86()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_DA1BF2C227DC3D86_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_2()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_2_OFFSET))(this);
		}

		::System::Boolean Method_2_35B574BF35040A2E()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_35B574BF35040A2E_OFFSET))(this);
		}

		::System::Void Method_2_C433AF37CE9D6E5B(::UnityEngine::GameObject* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_C433AF37CE9D6E5B_OFFSET))(this, a1);
		}

		::System::Boolean Method_2_4B2CD7086A8CA682()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_4B2CD7086A8CA682_OFFSET))(this);
		}

		::System::Boolean Method_2_1D4018D4200358D0()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_1D4018D4200358D0_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_3()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_3_OFFSET))(this);
		}

		::System::String* Method_2_DA1BF2C227DC3D86_1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_DA1BF2C227DC3D86_1_OFFSET))(this);
		}

		::Enum_3_17B78A87EAE1DCED Method_2_49AC00594530B714_1()
		{
			return ((::Enum_3_17B78A87EAE1DCED(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_49AC00594530B714_1_OFFSET))(this);
		}

		::System::Void Method_2_2685B6183E614529(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_2685B6183E614529_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::String*>* Method_2_8EA91B93B34817EA()
		{
			return ((::System::Collections::Generic::List_1<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_8EA91B93B34817EA_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_4()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_391A84BCD9F51317_4_OFFSET))(this);
		}

		::System::Boolean Method_2_4F6948586D063855()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESTEXTURESHEETANIMATION_METHOD_2_4F6948586D063855_OFFSET))(this);
		}
	};
}
