#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_17B78A87EAE1DCED.h"
#include "unitysdk/MoleMole/EffectSimulate/ESUniformRenderer_Enum_3_C37AFA0B254297DF.h"
#include "unitysdk/MoleMole/EffectSimulate/EffectMeshRendererBillboardComponent_Enum_3_59C412D4F0EDC7CB.h"
#include "unitysdk/MoleMole/EffectSimulate/EffectMeshRendererBillboardComponent_Enum_3_9CFC503A0B3454AC.h"
#include "unitysdk/MoleMole/EffectSimulate/IEffectSimulate.h"
#include "unitysdk/UnityEngine/ParticleSystemRenderMode.h"
#include "unitysdk/UnityEngine/Rendering/ShadowCastingMode.h"

namespace MoleMole::EffectSimulate { class EffectMeshRendererBillboardComponent; }
namespace System { class String; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Material; }
namespace UnityEngine { class Mesh; }
namespace UnityEngine { class Renderer; }

#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_BILLBOARDMODE_OFFSET UNITYSDK_OFFSET(0x8203650)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_MESHRENDERERMAT_OFFSET UNITYSDK_OFFSET(0x8204AE0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_MESHRENDERERMESH_OFFSET UNITYSDK_OFFSET(0x8204510)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_PSMAT_OFFSET UNITYSDK_OFFSET(0x82048C0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_PSMESH_OFFSET UNITYSDK_OFFSET(0x82042F0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_PSRENDERMODE_OFFSET UNITYSDK_OFFSET(0x8203140)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_RECEIVESHADOWS_OFFSET UNITYSDK_OFFSET(0x82050A0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_SHADOWCASTINGMODE_OFFSET UNITYSDK_OFFSET(0x8204ED0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_SORTINGFUDGE_OFFSET UNITYSDK_OFFSET(0x8204D40)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_STRETCHED_ANGLEOFFSET_OFFSET UNITYSDK_OFFSET(0x8203F40)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_STRETCHED_LOCKAXIS_OFFSET UNITYSDK_OFFSET(0x8203B30)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_1D3E0D19D91C431C_OFFSET UNITYSDK_OFFSET(0x8205270)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_1D4018D4200358D0_OFFSET UNITYSDK_OFFSET(0x8206270)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_1_OFFSET UNITYSDK_OFFSET(0x8205730)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_2_OFFSET UNITYSDK_OFFSET(0x8203D00)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_3_OFFSET UNITYSDK_OFFSET(0x82065C0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_4_OFFSET UNITYSDK_OFFSET(0x8206620)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0x82055B0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_3E7178C5ECF017DB_OFFSET UNITYSDK_OFFSET(0x8206470)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_49AC00594530B714_1_OFFSET UNITYSDK_OFFSET(0x8206210)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_49AC00594530B714_OFFSET UNITYSDK_OFFSET(0x8205790)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_4EE1B02AD2C54F52_OFFSET UNITYSDK_OFFSET(0x82057F0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_508D4DD02D3DB74E_OFFSET UNITYSDK_OFFSET(0x8206300)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_581A5078A2F29034_OFFSET UNITYSDK_OFFSET(0x82065B0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_6BCD3AA9C59860B7_OFFSET UNITYSDK_OFFSET(0x8204650)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_88B60F3B95FAA4F1_1_OFFSET UNITYSDK_OFFSET(0x82056A0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_88B60F3B95FAA4F1_OFFSET UNITYSDK_OFFSET(0x8205610)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_99053D1AE5A59190_OFFSET UNITYSDK_OFFSET(0x8205AB0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_A1890A50C1817E55_OFFSET UNITYSDK_OFFSET(0x8203240)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_AD52119E0AD66D16_OFFSET UNITYSDK_OFFSET(0x8205FA0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_B09E78EE7EE4F8FA_OFFSET UNITYSDK_OFFSET(0x82054C0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_C433AF37CE9D6E5B_OFFSET UNITYSDK_OFFSET(0x82064E0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_CA373AA1C7054598_OFFSET UNITYSDK_OFFSET(0x82066E0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_D3129FE8DF635B48_OFFSET UNITYSDK_OFFSET(0x82062F0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_DA1BF2C227DC3D86_1_OFFSET UNITYSDK_OFFSET(0x8206680)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_DA1BF2C227DC3D86_OFFSET UNITYSDK_OFFSET(0x8206550)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_BILLBOARDMODE_OFFSET UNITYSDK_OFFSET(0x82038C0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_MESHRENDERERMAT_OFFSET UNITYSDK_OFFSET(0x8204C00)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_MESHRENDERERMESH_OFFSET UNITYSDK_OFFSET(0x8204770)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_PSMAT_OFFSET UNITYSDK_OFFSET(0x82049C0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_PSMESH_OFFSET UNITYSDK_OFFSET(0x82043F0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_PSRENDERMODE_OFFSET UNITYSDK_OFFSET(0x8203540)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_RECEIVESHADOWS_OFFSET UNITYSDK_OFFSET(0x8205180)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_SHADOWCASTINGMODE_OFFSET UNITYSDK_OFFSET(0x8204FB0)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_SORTINGFUDGE_OFFSET UNITYSDK_OFFSET(0x8204E00)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_STRETCHED_ANGLEOFFSET_OFFSET UNITYSDK_OFFSET(0x8204110)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_STRETCHED_LOCKAXIS_OFFSET UNITYSDK_OFFSET(0x8203D70)
#define MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER__CTOR_OFFSET UNITYSDK_OFFSET(0x82061F0)

namespace MoleMole::EffectSimulate
{
	inline static constexpr unsigned int ESUniformRenderer_TypeDefinitionIndex = 56761;

	class ESUniformRenderer : public ::MoleMole::EffectSimulate::IEffectSimulate
	{
	public:
		::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent* m_stBillboardCom; // 0x48

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER__CTOR_OFFSET))(this);
		}

		::UnityEngine::ParticleSystemRenderMode get_psRenderMode()
		{
			return ((::UnityEngine::ParticleSystemRenderMode(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_PSRENDERMODE_OFFSET))(this);
		}

		::System::Void set_psRenderMode(::UnityEngine::ParticleSystemRenderMode a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemRenderMode))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_PSRENDERMODE_OFFSET))(this, a1);
		}

		::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_59C412D4F0EDC7CB get_billboardMode()
		{
			return ((::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_59C412D4F0EDC7CB(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_BILLBOARDMODE_OFFSET))(this);
		}

		::System::Void set_billboardMode(::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_59C412D4F0EDC7CB a1)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_59C412D4F0EDC7CB))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_BILLBOARDMODE_OFFSET))(this, a1);
		}

		::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_9CFC503A0B3454AC get_Stretched_lockAxis()
		{
			return ((::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_9CFC503A0B3454AC(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_STRETCHED_LOCKAXIS_OFFSET))(this);
		}

		::System::Void set_Stretched_lockAxis(::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_9CFC503A0B3454AC a1)
		{
			return ((::System::Void(*)(::PVOID, ::MoleMole::EffectSimulate::EffectMeshRendererBillboardComponent_Enum_3_9CFC503A0B3454AC))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_STRETCHED_LOCKAXIS_OFFSET))(this, a1);
		}

		::System::Single get_Stretched_angleOffset()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_STRETCHED_ANGLEOFFSET_OFFSET))(this);
		}

		::System::Void set_Stretched_angleOffset(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_STRETCHED_ANGLEOFFSET_OFFSET))(this, a1);
		}

		::UnityEngine::Mesh* get_psMesh()
		{
			return ((::UnityEngine::Mesh*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_PSMESH_OFFSET))(this);
		}

		::System::Void set_psMesh(::UnityEngine::Mesh* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Mesh*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_PSMESH_OFFSET))(this, a1);
		}

		::UnityEngine::Mesh* get_meshRendererMesh()
		{
			return ((::UnityEngine::Mesh*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_MESHRENDERERMESH_OFFSET))(this);
		}

		::System::Void set_meshRendererMesh(::UnityEngine::Mesh* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Mesh*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_MESHRENDERERMESH_OFFSET))(this, a1);
		}

		::UnityEngine::Material* get_psMat()
		{
			return ((::UnityEngine::Material*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_PSMAT_OFFSET))(this);
		}

		::System::Void set_psMat(::UnityEngine::Material* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Material*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_PSMAT_OFFSET))(this, a1);
		}

		::UnityEngine::Material* get_meshRendererMat()
		{
			return ((::UnityEngine::Material*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_MESHRENDERERMAT_OFFSET))(this);
		}

		::System::Void set_meshRendererMat(::UnityEngine::Material* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Material*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_MESHRENDERERMAT_OFFSET))(this, a1);
		}

		::System::Single get_sortingFudge()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_SORTINGFUDGE_OFFSET))(this);
		}

		::System::Void set_sortingFudge(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_SORTINGFUDGE_OFFSET))(this, a1);
		}

		::UnityEngine::Rendering::ShadowCastingMode get_shadowCastingMode()
		{
			return ((::UnityEngine::Rendering::ShadowCastingMode(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_SHADOWCASTINGMODE_OFFSET))(this);
		}

		::System::Void set_shadowCastingMode(::UnityEngine::Rendering::ShadowCastingMode a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Rendering::ShadowCastingMode))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_SHADOWCASTINGMODE_OFFSET))(this, a1);
		}

		::System::Boolean get_receiveShadows()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_GET_RECEIVESHADOWS_OFFSET))(this);
		}

		::System::Void set_receiveShadows(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_SET_RECEIVESHADOWS_OFFSET))(this, a1);
		}

		::System::Void Method_2_1D3E0D19D91C431C(::UnityEngine::GameObject* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_1D3E0D19D91C431C_OFFSET))(this, a1);
		}

		::System::Void Method_2_B09E78EE7EE4F8FA()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_B09E78EE7EE4F8FA_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_OFFSET))(this);
		}

		::System::String* Method_2_88B60F3B95FAA4F1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_88B60F3B95FAA4F1_OFFSET))(this);
		}

		::System::String* Method_2_88B60F3B95FAA4F1_1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_88B60F3B95FAA4F1_1_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_1()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_1_OFFSET))(this);
		}

		::Enum_3_17B78A87EAE1DCED Method_2_49AC00594530B714()
		{
			return ((::Enum_3_17B78A87EAE1DCED(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_49AC00594530B714_OFFSET))(this);
		}

		::System::String* Method_2_4EE1B02AD2C54F52()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_4EE1B02AD2C54F52_OFFSET))(this);
		}

		::System::Void Method_2_99053D1AE5A59190()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_99053D1AE5A59190_OFFSET))(this);
		}

		::System::Void Method_2_AD52119E0AD66D16(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_AD52119E0AD66D16_OFFSET))(this, a1);
		}

		::Enum_3_17B78A87EAE1DCED Method_2_49AC00594530B714_1()
		{
			return ((::Enum_3_17B78A87EAE1DCED(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_49AC00594530B714_1_OFFSET))(this);
		}

		::System::Boolean Method_2_1D4018D4200358D0()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_1D4018D4200358D0_OFFSET))(this);
		}

		::System::Void Method_2_D3129FE8DF635B48()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_D3129FE8DF635B48_OFFSET))(this);
		}

		::System::Void Method_2_508D4DD02D3DB74E()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_508D4DD02D3DB74E_OFFSET))(this);
		}

		::System::Void Method_2_3E7178C5ECF017DB(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_3E7178C5ECF017DB_OFFSET))(this, a1);
		}

		::UnityEngine::Renderer* Method_2_A1890A50C1817E55()
		{
			return ((::UnityEngine::Renderer*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_A1890A50C1817E55_OFFSET))(this);
		}

		::System::Void Method_2_C433AF37CE9D6E5B(::UnityEngine::GameObject* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GameObject*))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_C433AF37CE9D6E5B_OFFSET))(this, a1);
		}

		::System::String* Method_2_DA1BF2C227DC3D86()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_DA1BF2C227DC3D86_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_2()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_2_OFFSET))(this);
		}

		::MoleMole::EffectSimulate::ESUniformRenderer_Enum_3_C37AFA0B254297DF Method_2_6BCD3AA9C59860B7()
		{
			return ((::MoleMole::EffectSimulate::ESUniformRenderer_Enum_3_C37AFA0B254297DF(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_6BCD3AA9C59860B7_OFFSET))(this);
		}

		::System::String* Method_2_581A5078A2F29034()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_581A5078A2F29034_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_3()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_3_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317_4()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_391A84BCD9F51317_4_OFFSET))(this);
		}

		::System::String* Method_2_DA1BF2C227DC3D86_1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_DA1BF2C227DC3D86_1_OFFSET))(this);
		}

		::System::Void Method_2_CA373AA1C7054598()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + MOLEMOLE_EFFECTSIMULATE_ESUNIFORMRENDERER_METHOD_2_CA373AA1C7054598_OFFSET))(this);
		}
	};
}
